// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/Bots.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { i32, intArray, objArray } from '../java.js';

export class Bots {
  constructor() {
    this.timer = 0;
    this.upgo = null;
    this.leftgo = null;
    this.rightgo = null;
    this.downgo = null;
    this.handbgo = null;
    this.oneloaded = null;
    this.botoffset = null;
    this.writecode = false;
    this.doneload = false;
    this.botbreak = null;
    this.specialtimer = null;
    this.resetonce = false;
    this.whichbotcode = null;
    this.codeup = null;
    this.codedown = null;
    this.codeleft = null;
    this.coderight = null;
    this.codehandb = null;
    this.codeup = objArray(20000);
    this.codedown = objArray(20000);
    this.codeleft = objArray(20000);
    this.coderight = objArray(20000);
    this.codehandb = objArray(20000);
    this.timer = 0;
    this.whichbotcode = intArray(101);
    this.specialtimer = intArray(101);
    this.writecode = false;
    this.doneload = false;
    this.botbreak = new Array(101).fill(false);
    this.oneloaded = new Array(101).fill(false);
    this.upgo = objArray(20000).map(() => new Array(101).fill(false));
    this.leftgo = objArray(20000).map(() => new Array(101).fill(false));
    this.rightgo = objArray(20000).map(() => new Array(101).fill(false));
    this.handbgo = objArray(20000).map(() => new Array(101).fill(false));
    this.downgo = objArray(20000).map(() => new Array(101).fill(false));
    this.botoffset = objArray(10).map(() => intArray(101));
    this.resetonce = false;
  }

  reset() {
    this.timer = 0;
    this.doneload = false;
    for (let a = 0; a < 101; a = i32(a + 1)) {
      this.specialtimer[a] = 0;
      this.whichbotcode[a] = 0;
      this.oneloaded[a] = false;
      this.botbreak[a] = false;
      for (let b = 0; b < 10; b = i32(b + 1)) {
        this.botoffset[b][a] = 0;
      }
    }
    for (let a = 0; a < 20000; a = i32(a + 1)) {
      for (let b = 0; b < 101; b = i32(b + 1)) {
        this.upgo[a][b] = false;
        this.leftgo[a][b] = false;
        this.rightgo[a][b] = false;
        this.downgo[a][b] = false;
        this.handbgo[a][b] = false;
      }
      this.codeup[a] = '';
      this.codedown[a] = '';
      this.codeleft[a] = '';
      this.coderight[a] = '';
      this.codehandb[a] = '';
    }
    this.writecode = false;
  }

  resettimer() {
    this.timer = 0;
    for (let a = 0; a < 101; a = i32(a + 1)) {
      this.specialtimer[a] = 0;
      this.whichbotcode[a] = 0;
      this.botbreak[a] = false;
    }
  }

  runbots(control, usebots, i, timerflag) {
    let whichtimer = this.timer;
    if (timerflag) {
      whichtimer = this.specialtimer[i];
    }
    if (usebots) {
      control[i].up = false;
      control[i].down = false;
      control[i].left = false;
      control[i].right = false;
      control[i].handb = false;
      if (this.upgo[whichtimer][i]) {
        control[i].up = true;
      }
      if (this.downgo[whichtimer][i]) {
        control[i].down = true;
      }
      if (this.leftgo[whichtimer][i]) {
        control[i].left = true;
      }
      if (this.rightgo[whichtimer][i]) {
        control[i].right = true;
      }
      if (this.handbgo[whichtimer][i]) {
        control[i].handb = true;
      }
    }
  }
}
