// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/CheckPoints.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { i32, idiv, intArray } from '../java.js';

export class CheckPoints {
  constructor() {
    this.x = null;
    this.z = null;
    this.y = null;
    this.typ = null;
    this.pcs = 0;
    this.nsp = 0;
    this.n = 0;
    this.fx = null;
    this.fz = null;
    this.fy = null;
    this.roted = null;
    this.special = null;
    this.fn = 0;
    this.stage = 0;
    this.nlaps = 0;
    this.name = null;
    this.pos = null;
    this.clear = null;
    this.dested = null;
    this.wasted = 0;
    this.haltall = false;
    this.pcleared = 0;
    this.opx = null;
    this.opz = null;
    this.onscreen = null;
    this.omxz = null;
    this.catchfin = 0;
    this.postwo = 0;
    this.rotation = null;
    this.chkcode = null;
    this.telefloor = null;
    this.floor = null;
    this.pos = Int32Array.from([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]);
    this.x = intArray(2000);
    this.z = intArray(2000);
    this.y = intArray(2000);
    this.telefloor = intArray(2000);
    this.floor = intArray(2000);
    this.typ = intArray(2000);
    this.rotation = intArray(2000);
    this.chkcode = intArray(2000);
    this.pcs = 0;
    this.nsp = 0;
    this.n = 0;
    this.fx = intArray(50);
    this.fz = intArray(50);
    this.fy = intArray(50);
    this.roted = new Array(50).fill(false);
    this.special = new Array(50).fill(false);
    this.fn = 0;
    this.stage = 1;
    this.nlaps = 0;
    this.name = 'hogan rewish';
    this.clear = intArray(101);
    this.dested = intArray(101);
    this.wasted = 0;
    this.haltall = false;
    this.pcleared = 0;
    this.opx = intArray(101);
    this.opz = intArray(101);
    this.onscreen = intArray(101);
    this.omxz = intArray(101);
    this.catchfin = 0;
    this.postwo = 0;
  }

  checkstat(amadness, aconto, record, xtgraphics) {
    if (!this.haltall) {
      this.pcleared = amadness[0].pcleared;
      let i = 0;
      do {
        this.pos[i] = 0;
        this.onscreen[i] = aconto[i].dist;
        this.opx[i] = aconto[i].x;
        this.opz[i] = aconto[i].z;
        this.omxz[i] = amadness[i].mxz;
        if ((this.dested[i] === 0) || ((xtgraphics.careermode && (this.stage === 20)))) {
          this.clear[i] = amadness[i].clear;
        } else {
          this.clear[i] = -1;
        }
      } while (++i < xtgraphics.nplayers);
      i = 0;
      do {
        for (let l = i32(i + 1); l < xtgraphics.nplayers; l = i32(l + 1)) {
          if (this.clear[i] !== this.clear[l]) {
            if (this.clear[i] < this.clear[l]) {
              let pos = this.pos;
              let n = i;
              ++pos[n];
            } else {
              let pos2 = this.pos;
              let n2 = l;
              ++pos2[n2];
            }
          } else {
            let j1 = 0;
            j1 = i32(amadness[i].pcleared + 1);
            while (this.typ[j1] <= 0) {
              if (++j1 === this.n) {
                j1 = 0;
              }
            }
            if (this.py(idiv(aconto[i].x, 100), idiv(this.x[j1], 100), idiv(aconto[i].z, 100), idiv(this.z[j1], 100)) > this.py(idiv(aconto[l].x, 100), idiv(this.x[j1], 100), idiv(aconto[l].z, 100), idiv(this.z[j1], 100))) {
              let pos3 = this.pos;
              let n3 = i;
              ++pos3[n3];
            } else {
              let pos4 = this.pos;
              let n4 = l;
              ++pos4[n4];
            }
          }
        }
      } while (++i < xtgraphics.nplayers);
      if (this.stage > 2) {
        for (let k = 0; k < xtgraphics.nplayers; k = i32(k + 1)) {
          if ((this.clear[k] === (Math.imul(this.nlaps, this.nsp))) && (this.pos[k] === 0)) {
            if (k === 0) {
              for (let i2 = 0; i2 < xtgraphics.nplayers; i2 = i32(i2 + 1)) {
                if (this.pos[i2] === 1) {
                  this.postwo = i2;
                }
              }
              if ((this.py(idiv(this.opx[0], 100), idiv(this.opx[this.postwo], 100), idiv(this.opz[0], 100), idiv(this.opz[this.postwo], 100)) < 14000) && ((i32(this.clear[0] - this.clear[this.postwo])) === 1)) {
                this.catchfin = 30;
              }
            } else if (((this.pos[0] === 1) && (this.py(idiv(this.opx[0], 100), idiv(this.opx[k], 100), idiv(this.opz[0], 100), idiv(this.opz[k], 100)) < 14000)) && ((i32(this.clear[k] - this.clear[0])) === 1)) {
              this.catchfin = 30;
              this.postwo = k;
            }
          }
        }
      }
    }
    this.wasted = 0;
    let m = 1;
    do {
      if (amadness[m].dest || amadness[m].fakedest) {
        this.wasted = i32(this.wasted + 1);
      }
    } while (++m < xtgraphics.nplayers);
    if (this.catchfin !== 0) {
      this.catchfin = i32(this.catchfin - 1);
      if (this.catchfin === 0) {
        record.cotchinow(this.postwo, xtgraphics.nplayers);
        record.closefinish = i32(this.pos[0] + 1);
      }
    }
  }

  py(i, j, k, l) {
    return i32((Math.imul(((i32(i - j))), (i32(i - j)))) + (Math.imul(((i32(k - l))), (i32(k - l)))));
  }
}
