// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/Contva.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { fr, i32, idiv, intArray } from '../java.js';
import { id } from './newcars.js';   // ext-ident (web/tools/ext-ident.mjs)

export class Contva {
  constructor() {
    this.freeze = null;
    this.weaken = null;
    this.swapped = null;
    this.leeching = null;
    this.vulnerable = null;
    this.specon = null;
    this.urgency = false;
    this.biglead = null;
    this.incatt = null;
    this.offatt = null;
    this.completed = null;
    this.lotswasted = false;
    this.needhelp = null;
    this.fixpoint = null;
    this.numfixes = 0;
    this.whichfix = 0;
    this.camping = null;
    this.nearchk = null;
    this.chkcircle = null;
    this.slowdown = null;
    this.slowrange = null;
    this.moreslow = null;
    this.opbackloops = null;
    this.dontdistract = null;
    this.dontstunt = null;
    this.spdexception = null;
    this.dontmiss = null;
    this.hugelead = null;
    this.layoff = null;
    this.sharpturn = null;
    this.vulnerable = new Array(101).fill(false);
    this.freeze = new Array(101).fill(false);
    this.swapped = new Array(101).fill(false);
    this.leeching = new Array(101).fill(false);
    this.weaken = new Array(101).fill(false);
    this.specon = new Array(101).fill(false);
    this.completed = intArray(101);
    this.sharpturn = intArray(101);
    this.fixpoint = intArray(50);
    this.numfixes = 0;
    this.lotswasted = false;
    this.spdexception = new Array(101).fill(false);
    this.urgency = false;
    this.biglead = new Array(101).fill(false);
    this.dontmiss = new Array(101).fill(false);
    this.needhelp = new Array(101).fill(false);
    this.whichfix = 0;
    this.camping = new Array(101).fill(false);
    this.chkcircle = intArray(101);
    this.moreslow = intArray(101);
    this.nearchk = new Array(101).fill(false);
    this.slowdown = intArray(101);
    this.slowrange = intArray(101);
    this.opbackloops = new Array(101).fill(false);
    this.dontdistract = new Array(101).fill(false);
    this.dontstunt = new Array(101).fill(false);
    this.hugelead = new Array(101).fill(false);
    this.layoff = new Array(101).fill(false);
  }

  resetfp() {
    for (let a = 0; a < 50; a = i32(a + 1)) {
      this.fixpoint[a] = 0;
    }
    this.numfixes = 0;
    this.whichfix = 0;
  }

  reset() {
    for (let a = 0; a < 101; a = i32(a + 1)) {
      this.vulnerable[a] = false;
      this.freeze[a] = false;
      this.swapped[a] = false;
      this.leeching[a] = false;
      this.weaken[a] = false;
      this.specon[a] = false;
      this.needhelp[a] = false;
      this.camping[a] = false;
      this.dontstunt[a] = false;
      this.nearchk[a] = false;
      this.sharpturn[a] = 0;
      this.opbackloops[a] = false;
      this.biglead[a] = false;
      this.completed[a] = 0;
      this.spdexception[a] = false;
      this.slowdown[a] = 240;
      this.slowrange[a] = 4000;
      this.chkcircle[a] = 0;
      this.moreslow[a] = 0;
      this.dontdistract[a] = false;
      this.dontmiss[a] = false;
      this.hugelead[a] = false;
      this.layoff[a] = false;
    }
    this.lotswasted = false;
    this.whichfix = 0;
    this.urgency = false;
  }

  sortvariables(madness, checkpoints, u, careermode, nplayers) {
    if (madness.frozen) {
      this.vulnerable[madness.im] = true;
      this.freeze[madness.im] = true;
    } else {
      this.freeze[madness.im] = false;
    }
    if (madness.redstr) {
      this.vulnerable[madness.im] = true;
      this.weaken[madness.im] = true;
    } else {
      this.weaken[madness.im] = false;
    }
    if (madness.strswap) {
      this.swapped[madness.im] = true;
      this.vulnerable[madness.im] = true;
    } else {
      this.swapped[madness.im] = false;
    }
    if (madness.leech) {
      this.leeching[madness.im] = true;
    } else {
      this.leeching[madness.im] = false;
    }
    if ((!madness.frozen && !madness.redstr) && !madness.strswap) {
      this.vulnerable[madness.im] = false;
    }
    if (madness.specialact) {
      this.specon[madness.im] = true;
    } else {
      this.specon[madness.im] = false;
    }
    for (let a = 0; a < nplayers; a = i32(a + 1)) {
      if ((checkpoints.pos[madness.im] === 0) && (checkpoints.pos[a] === 1)) {
        if (checkpoints.clear[madness.im] > (i32(checkpoints.clear[a] + 2))) {
          this.biglead[madness.im] = true;
          if (checkpoints.clear[madness.im] > (i32(checkpoints.clear[a] + 6))) {
            this.hugelead[madness.im] = true;
          } else {
            this.hugelead[madness.im] = false;
          }
        } else {
          this.biglead[madness.im] = false;
          this.hugelead[madness.im] = false;
        }
      } else {
        this.biglead[madness.im] = false;
        this.hugelead[madness.im] = false;
      }
    }
    this.completed[madness.im] = idiv((Math.imul(checkpoints.clear[madness.im], 100)), (Math.imul(checkpoints.nsp, checkpoints.nlaps)));
    if (checkpoints.wasted >= (i32(nplayers - 5))) {
      this.lotswasted = true;
    } else {
      this.lotswasted = false;
    }
    if ((u[madness.im].trfix >= 2) || madness.dest) {
      this.needhelp[madness.im] = true;
    } else {
      this.needhelp[madness.im] = false;
    }
    let bitmore = intArray(101);
    if (madness.beast[madness.im]) {
      bitmore[madness.im] = 1000;
    } else {
      bitmore[madness.im] = 0;
    }
    if ((madness.swits[madness.cn][2] >= 340) && (madness.swits[madness.cn][2] < 380)) {
      this.slowdown[madness.im] = 180;
    }
    if ((madness.swits[madness.cn][2] >= 380) && (madness.swits[madness.cn][2] < 420)) {
      this.slowdown[madness.im] = 170;
    }
    if (madness.swits[madness.cn][2] >= 420) {
      this.slowdown[madness.im] = 150;
    }
    if (madness.swits[madness.cn][2] >= 340) {
      this.slowrange[madness.im] = i32(2500 + bitmore[madness.im]);
    }
    if (this.nearchk[madness.im]) {
      let chkcircle = this.chkcircle;
      let im = madness.im;
      ++chkcircle[im];
    } else {
      this.chkcircle[madness.im] = 0;
    }
    if (this.chkcircle[madness.im] > 120) {
      let moreslow = this.moreslow;
      let im2 = madness.im;
      ++moreslow[im2];
    } else {
      this.moreslow[madness.im] = 0;
    }
    if (this.moreslow[madness.im] > 80) {
      this.moreslow[madness.im] = 80;
    }
    if (careermode) {
      if (this.dontmiss[madness.im]) {
        let range = 9000;
        if (checkpoints.stage >= 23) {
          range = 5000;
        }
        if (checkpoints.stage === 19) {
          if ((id(madness.cn) === 17) || madness.shadowcar) {
            let extrarange = 0;
            if (madness.specialact) {
              extrarange = 1300;
            }
            range = i32(3200 + extrarange);
          } else {
            range = 6000;
          }
        }
        this.slowrange[madness.im] = range;
        let slowby = 150;
        if (checkpoints.stage >= 21) {
          slowby = 210;
        }
        if (checkpoints.stage === 9) {
          range = 3000;
          slowby = 240;
        }
        this.slowdown[madness.im] = slowby;
      }
      if ((checkpoints.stage === 7) || (checkpoints.stage === 8)) {
        this.slowrange[madness.im] = 0;
      }
      if ((checkpoints.stage === 22) && (madness.im === (i32(nplayers - 1)))) {
        let health = fr((fr(100.0 * fr(madness.hitmag))) / fr(madness.maxmag[madness.cn]));
        if (health > 85.0) {
          this.layoff[madness.im] = true;
        } else {
          this.layoff[madness.im] = false;
        }
      }
      if ((checkpoints.stage === 11) || (checkpoints.stage === 12)) {
        if (id(madness.cn) === 10) {
          this.spdexception[madness.im] = true;
        } else {
          this.spdexception[madness.im] = false;
        }
        this.slowdown[madness.im] = 180;
        this.slowrange[madness.im] = 4500;
      }
      if ((checkpoints.stage === 13) && (id(madness.cn) === 13)) {
        this.spdexception[madness.im] = true;
        this.slowdown[madness.im] = 200;
        this.slowrange[madness.im] = 4000;
      }
      if (checkpoints.stage === 14) {
        if (id(madness.cn) === 14) {
          if ((madness.power === 98.0) && (madness.pcleared === 321)) {
            this.opbackloops[madness.im] = true;
          } else {
            this.opbackloops[madness.im] = false;
          }
        }
        if ((((((madness.pcleared === 130) && !madness.specialact)) || (madness.pcleared === 221)) || (madness.pcleared === 261)) || (madness.pcleared === 248)) {
          if (madness.point < madness.pcleared) {
            this.dontdistract[madness.im] = true;
          } else {
            this.dontdistract[madness.im] = false;
          }
        } else {
          this.dontdistract[madness.im] = false;
        }
      }
    }
  }
}
