// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/Medium.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { floatArray, fr, i32, idiv, intArray, objArray, random, trunc } from '../java.js';
import { Arrays, Color, Random, StringBuilder, System } from './jawt.js';

export class Medium {
  constructor() {
    this.focus_point = 0;
    this.ground = 0;
    this.skyline = 0;
    this.fade = null;
    this.originalfade = null;
    this.csky = null;
    this.cgrnd = null;
    this.cpol = null;
    this.cfade = null;
    this.snap = null;
    this.osnap = null;
    this.polyoutline = null;
    this.osky = null;
    this.cldd = null;
    this.clds = null;
    this.clx = null;
    this.stx = null;
    this.pvr = null;
    this.nst = 0;
    this.cgpx = null;
    this.pcv = null;
    this.cgpz = null;
    this.pmx = null;
    this.stz = null;
    this.stc = null;
    this.bst = null;
    this.twn = null;
    this.resdown = 0;
    this.rescnt = 0;
    this.mgen = 0;
    this.clz = null;
    this.cmx = null;
    this.clax = null;
    this.clay = null;
    this.claz = null;
    this.clc = null;
    this.origfade = 0;
    this.noc = 0;
    this.nmt = 0;
    this.glassfade = 0;
    this.fogd = 0;
    this.lightson = false;
    this.lightn = 0;
    this.lilo = 0;
    this.flex = 0;
    this.mrd = null;
    this.nmv = null;
    this.mtx = null;
    this.mty = null;
    this.mtz = null;
    this.mtc = null;
    this.ogrnd = null;
    this.crgrnd = null;
    this.trk = false;
    this.crs = false;
    this.cx = 0;
    this.cy = 0;
    this.showsnow = false;
    this.showwater = false;
    this.cz = 0;
    this.xz = 0;
    this.zy = 0;
    this.x = 0;
    this.y = 0;
    this.z = 0;
    this.w = 0;
    this.h = 0;
    this.effect = null;
    this.ih = 0;
    this.iw = 0;
    this.nsp = 0;
    this.spx = null;
    this.spz = null;
    this.sprad = null;
    this.td = false;
    this.bcxz = 0;
    this.bcxzwatch = 0;
    this.bt = false;
    this.vxz = 0;
    this.adv = 0;
    this.vert = false;
    this.trns = 0;
    this.dispolys = 0;
    this.ogpx = null;
    this.ogpz = null;
    this.sgpx = 0;
    this.sgpz = 0;
    this.nrw = 0;
    this.ncl = 0;
    this.tcos = null;
    this.tsin = null;
    this.lastmaf = 0;
    this.checkpoint = 0;
    this.lastcheck = false;
    this.elecr = 0;
    this.cpflik = false;
    this.nochekflk = false;
    this.cntrn = 0;
    this.diup = null;
    this.rand = null;
    this.trn = 0;
    this.hit = 0;
    this.ptr = 0;
    this.ptcnt = 0;
    this.nrnd = 0;
    this.trx = 0;
    this.trz = 0;
    this.atrx = 0;
    this.atrz = 0;
    this.fallen = 0;
    this.fo = 0;
    this.gofo = 0;
    this.decrease = false;
    this.switchfase = 0;
    this.glowfase = 0;
    this.makefase = 0;
    this.darklevel = 0;
    this.oneffect = null;
    this.ocsky = null;
    this.ocfade = null;
    this.wallside = null;
    this.groundcolour = false;
    this.darken = false;
    this.darkenfor = 0;
    this.skycolour = null;
    this.fadecolour = null;
    this.grndcolour = null;
    this.polycolour = null;
    this.effecttime = 0;
    this.snowno = 0;
    this.changingsnap = false;
    this.shadowtrans = 0;
    this.verydark = false;
    this.snowheight = 0;
    this.drowned = false;
    this.icehills = false;
    this.reducepolys = 0;
    this.greystage = 0;
    this.starfase = null;
    this.fade = Int32Array.from([3000, 4500, 6000, 7500, 9000, 10500, 12000, 13500, 15000, 16500, 18000, 19500, 21000, 22500, 24000, 25500]);
    this.originalfade = Int32Array.from([3000, 4500, 6000, 7500, 9000, 10500, 12000, 13500, 15000, 16500, 18000, 19500, 21000, 22500, 24000, 25500]);
    this.csky = Int32Array.from([170, 220, 255]);
    this.cgrnd = Int32Array.from([205, 200, 200]);
    this.cpol = Int32Array.from([215, 210, 210]);
    this.cfade = Int32Array.from([255, 220, 220]);
    this.osky = Int32Array.from([170, 220, 255]);
    this.cldd = Int32Array.from([210, 210, 210, 1, -1000]);
    this.clds = Int32Array.from([210, 210, 210]);
    this.clx = null;
    this.stx = null;
    this.pvr = null;
    this.nst = 0;
    this.cgpx = null;
    this.pcv = null;
    this.cgpz = null;
    this.pmx = null;
    this.stz = null;
    this.stc = null;
    this.bst = null;
    this.twn = null;
    this.resdown = 0;
    this.rescnt = 0;
    this.mgen = trunc((random() * 100000.0));
    this.clz = null;
    this.cmx = null;
    this.clax = null;
    this.clay = null;
    this.claz = null;
    this.clc = null;
    this.noc = 0;
    this.nmt = 0;
    this.mrd = null;
    this.nmv = null;
    this.mtx = null;
    this.mty = null;
    this.mtz = null;
    this.mtc = null;
    this.ogrnd = Int32Array.from([205, 200, 200]);
    this.crgrnd = Int32Array.from([205, 200, 200]);
    this.ocsky = intArray(3);
    this.ocfade = intArray(3);
    this.starfase = intArray(1000);
    this.focus_point = 400;
    this.ground = 250;
    this.skyline = -300;
    this.snap = intArray(3);
    this.osnap = intArray(3);
    this.polyoutline = intArray(3);
    this.origfade = 3000;
    this.fogd = 7;
    this.switchfase = 0;
    this.icehills = false;
    this.makefase = 0;
    this.darklevel = 0;
    this.glassfade = 65;
    this.changingsnap = false;
    this.snowheight = 0;
    this.oneffect = new Array(100).fill(false);
    this.effect = new Array(100).fill(false);
    this.darken = false;
    this.darkenfor = 0;
    this.reducepolys = 1.0;
    this.shadowtrans = 80;
    this.decrease = false;
    this.glowfase = 0;
    this.drowned = false;
    this.lightson = false;
    this.verydark = false;
    this.lightn = -1;
    this.lilo = 217;
    this.greystage = 0;
    this.iw = 0;
    this.ih = 0;
    this.snowno = 0;
    this.effecttime = 0;
    this.flex = 0;
    this.trk = false;
    this.groundcolour = false;
    this.crs = false;
    this.cx = 435;
    this.cy = 240;
    this.skycolour = intArray(3);
    this.fadecolour = intArray(3);
    this.grndcolour = intArray(3);
    this.polycolour = intArray(3);
    this.cz = 50;
    this.xz = 0;
    this.zy = 0;
    this.wallside = intArray(4);
    this.x = 0;
    this.y = 0;
    this.z = 0;
    this.w = 870;
    this.h = 480;
    this.nsp = 0;
    this.showsnow = false;
    this.showwater = false;
    this.spx = intArray(101);
    this.spz = intArray(101);
    this.sprad = intArray(101);
    this.td = false;
    this.bcxz = 0;
    this.bcxzwatch = 0.0;
    this.bt = false;
    this.vxz = 180;
    this.adv = 500;
    this.vert = false;
    this.trns = 1;
    this.dispolys = 0;
    this.ogpx = objArray(200000).map(() => intArray(8));
    this.ogpz = objArray(200000).map(() => intArray(8));
    this.cgpx = intArray(200000);
    this.cgpz = intArray(200000);
    this.sgpx = 0;
    this.sgpz = 0;
    this.nrw = 0;
    this.ncl = 0;
    this.tcos = floatArray(360);
    this.tsin = floatArray(360);
    this.lastmaf = 0;
    this.checkpoint = -1;
    this.lastcheck = false;
    this.elecr = 0.0;
    this.cpflik = false;
    this.nochekflk = false;
    this.cntrn = 0;
    this.diup = new Array(3).fill(false);
    this.rand = intArray(3);
    this.trn = 0;
    this.hit = 45000;
    this.ptr = 0;
    this.ptcnt = -10;
    this.nrnd = 0;
    this.trx = 0;
    this.trz = 0;
    this.atrx = 0;
    this.atrz = 0;
    this.fallen = 0;
    this.fo = 1.0;
    this.gofo = fr((0.33000001311302185 + (random() * 1.34)));
    let i = 0;
    do {
      this.tcos[i] = fr(Math.cos(i * 0.017453292519943295));
    } while (++i < 360);
    i = 0;
    do {
      this.tsin[i] = fr(Math.sin(i * 0.017453292519943295));
    } while (++i < 360);
  }

  random() {
    if (this.cntrn === 0) {
      let i = 0;
      do {
        this.rand[i] = trunc((10.0 * random()));
        if (random() > random()) {
          this.diup[i] = false;
        } else {
          this.diup[i] = true;
        }
      } while (++i < 3);
      this.cntrn = 20;
    } else {
      this.cntrn = i32(this.cntrn - 1);
    }
    let j = 0;
    do {
      if (this.diup[j]) {
        let rand = this.rand;
        let n = j;
        ++rand[n];
        if (this.rand[j] !== 10) {
          continue;
        }
        this.rand[j] = 0;
      } else {
        let rand2 = this.rand;
        let n2 = j;
        --rand2[n2];
        if (this.rand[j] !== -1) {
          continue;
        }
        this.rand[j] = 9;
      }
    } while (++j < 3);
    this.trn = i32(this.trn + 1);
    if (this.trn === 3) {
      this.trn = 0;
    }
    return fr(fr(this.rand[this.trn]) / 10.0);
  }

  groundpolys(g) {
    let extra = 1.0;
    if (this.effect[4]) {
      extra = 2.0;
    }
    let i = i32((idiv(((i32(this.x - this.sgpx))), trunc((1200.0 * this.reducepolys)))) - trunc((7.0 * extra)));
    if (i < 0) {
      i = 0;
    }
    let j = i32(i + trunc((15.0 * extra)));
    if (j > this.nrw) {
      j = this.nrw;
    }
    let k = i32((idiv(((i32(this.z - this.sgpz))), trunc((1200.0 * this.reducepolys)))) - trunc((7.0 * extra)));
    if (k < 0) {
      k = 0;
    }
    let l = i32(k + trunc((15.0 * extra)));
    if (l > this.ncl) {
      l = this.ncl;
    }
    for (let i2 = i; i2 < j; i2 = i32(i2 + 1)) {
      for (let j2 = k; j2 < l; j2 = i32(j2 + 1)) {
        let k2 = i32(i2 + (Math.imul(j2, this.nrw)));
        let l2 = i32(this.cx + trunc((fr((fr(fr(((i32((i32(this.cgpx[k2] - this.x)) - this.cx)))) * this.cos(this.xz))) - (fr(fr(((i32((i32(this.cgpz[k2] - this.z)) - this.cz)))) * this.sin(this.xz)))))));
        let i3 = i32(this.cz + trunc((fr((fr(fr(((i32((i32(this.cgpx[k2] - this.x)) - this.cx)))) * this.sin(this.xz))) + (fr(fr(((i32((i32(this.cgpz[k2] - this.z)) - this.cz)))) * this.cos(this.xz)))))));
        let j3 = i32(this.cz + trunc((fr((fr(fr(((i32((i32(this.ground - this.y)) - this.cy)))) * this.sin(this.zy))) + (fr(fr(((i32(i3 - this.cz)))) * this.cos(this.zy)))))));
        if ((((((this.xs(i32(l2 + 700), j3) > 0) && (this.xs(i32(l2 - 700), j3) < this.w)) && (j3 > -700)) && (j3 < (idiv(((i32(this.fade[0] + this.fade[1]))), 2))))) || this.effect[4]) {
          let ai = objArray(4).map(() => intArray(8));
          let ai2 = objArray(4).map(() => intArray(8));
          let ai3 = objArray(4).map(() => intArray(8));
          let groundloc = this.ground;
          if (this.effect[4]) {
            groundloc = i32(this.ground + 2500);
          }
          let groundlevels = Int32Array.from([groundloc, -10000, -20000, -30000]);
          let polylimit = 1;
          let b2 = this.effect[9];
          for (let a = 0; a < polylimit; a = i32(a + 1)) {
            let k3 = 0;
            do {
              ai[a][k3] = i32((i32(this.ogpx[k2][k3] + this.cgpx[k2])) - this.x);
              ai2[a][k3] = i32((i32(this.ogpz[k2][k3] + this.cgpz[k2])) - this.z);
              ai3[a][k3] = groundlevels[a];
            } while (++k3 < 8);
            this.rot(ai[a], ai2[a], this.cx, this.cz, this.xz, 8);
            this.rot(ai3[a], ai2[a], this.cy, this.cz, this.zy, 8);
          }
          let ai4 = objArray(4).map(() => intArray(8));
          let ai5 = objArray(4).map(() => intArray(8));
          let l3 = 0;
          let i4 = 0;
          let j4 = 0;
          let k4 = 0;
          let flag = true;
          for (let a2 = 0; a2 < polylimit; a2 = i32(a2 + 1)) {
            let l4 = 0;
            do {
              ai4[a2][l4] = this.xs(ai[a2][l4], ai2[a2][l4]);
              ai5[a2][l4] = this.ys(ai3[a2][l4], ai2[a2][l4]);
              if ((ai5[a2][l4] < 0) || (ai2[a2][l4] < 10)) {
                l3 = i32(l3 + 1);
              }
              if ((ai5[a2][l4] > this.h) || (ai2[a2][l4] < 10)) {
                i4 = i32(i4 + 1);
              }
              if ((ai4[a2][l4] < 0) || (ai2[a2][l4] < 10)) {
                j4 = i32(j4 + 1);
              }
              if ((ai4[a2][l4] > this.w) || (ai2[a2][l4] < 10)) {
                k4 = i32(k4 + 1);
              }
            } while (++l4 < 8);
            if ((((j4 === 8) || (l3 === 8)) || (i4 === 8)) || (k4 === 8)) {
              flag = false;
            }
          }
          if (flag) {
            for (let a2 = 0; a2 < polylimit; a2 = i32(a2 + 1)) {
              let i5 = this.cpol[0];
              let j5 = this.cpol[1];
              let k5 = this.cpol[2];
              if (j3 > this.fade[0]) {
                i5 = idiv(((i32((Math.imul(i5, 3)) + this.cfade[0]))), 4);
                j5 = idiv(((i32((Math.imul(j5, 3)) + this.cfade[1]))), 4);
                k5 = idiv(((i32((Math.imul(k5, 3)) + this.cfade[2]))), 4);
              }
              g.setColor(i5, j5, k5);
              g.fillPolygon(ai4[a2], ai5[a2], 8);
              let glowingpolys = false;
              if (this.effect[0] && ((((this.polyoutline[0] > 0) || (this.polyoutline[1] > 0)) || (this.polyoutline[2] > 0)))) {
                glowingpolys = true;
              }
              if (this.effect[5] && (this.polyoutline[1] > 20)) {
                glowingpolys = true;
              }
              if (glowingpolys) {
                for (let b = 0; b < 3; b = i32(b + 1)) {
                  if (this.polyoutline[b] > 255) {
                    this.polyoutline[b] = 255;
                  }
                  if (this.polyoutline[b] < 0) {
                    this.polyoutline[b] = 0;
                  }
                }
                g.setColor(this.polyoutline[0], this.polyoutline[1], this.polyoutline[2]);
                g.drawPolygon(ai4[a2], ai5[a2], 8);
              }
            }
          }
        }
      }
    }
  }

  setcloads(i, i_252_, i_253_, i_254_, i_255_) {
    if (i_254_ < 0) {
      i_254_ = 0;
    }
    if (i_254_ > 10) {
      i_254_ = 10;
    }
    if (i_255_ < -1500) {
      i_255_ = -1500;
    }
    if (i_255_ > -500) {
      i_255_ = -500;
    }
    this.cldd[0] = i;
    this.cldd[1] = i_252_;
    this.cldd[2] = i_253_;
    this.cldd[3] = i_254_;
    this.cldd[4] = i_255_;
    if (this.effect[9]) {
      this.cldd[4] = Math.imul(i_255_, 5);
    }
    for (let i_256_ = 0; i_256_ < 3; i_256_ = i32(i_256_ + 1)) {
      this.clds[i_256_] = idiv(((i32((Math.imul(this.osky[i_256_], this.cldd[3])) + this.cldd[i_256_]))), (i32(this.cldd[3] + 1)));
      this.clds[i_256_] = trunc(fr(fr(this.clds[i_256_]) + ((fr(fr(this.clds[i_256_]) * ((fr(fr(this.snap[i_256_]) / 100.0))))))));
      if (this.clds[i_256_] > 255) {
        this.clds[i_256_] = 255;
      }
      if (this.clds[i_256_] < 0) {
        this.clds[i_256_] = 0;
      }
    }
  }

  newclouds(i, i_88_, i_89_, i_90_, x, xtgraphics) {
    this.clx = null;
    this.clz = null;
    this.cmx = null;
    this.clax = null;
    this.clay = null;
    this.claz = null;
    this.clc = null;
    i = i32((idiv(i, 20)) - 10000);
    i_88_ = i32((idiv(i_88_, 20)) + 10000);
    i_89_ = i32((idiv(i_89_, 20)) - 10000);
    i_90_ = i32((idiv(i_90_, 20)) + 10000);
    this.noc = idiv((Math.imul(((i32(i_88_ - i))), (i32(i_90_ - i_89_)))), 16666667);
    if (xtgraphics.careermode) {
      if (x === 11) {
        this.noc = trunc(((idiv((Math.imul(((i32(i_88_ - i))), (i32(i_90_ - i_89_)))), 16666667)) / 2.5));
      }
      if (((((this.effect[8] || this.effect[11]) || (x === 18)) || (x === 22)) || (x === 24)) || (x === 16)) {
        this.noc = 0;
      }
    }
    this.clx = intArray(this.noc);
    this.clz = intArray(this.noc);
    this.cmx = intArray(this.noc);
    this.clax = objArray(this.noc).map(() => objArray(3).map(() => intArray(12)));
    this.clay = objArray(this.noc).map(() => objArray(3).map(() => intArray(12)));
    this.claz = objArray(this.noc).map(() => objArray(3).map(() => intArray(12)));
    this.clc = objArray(this.noc).map(() => objArray(2).map(() => objArray(6).map(() => intArray(3))));
    for (let i_91_ = 0; i_91_ < this.noc; i_91_ = i32(i_91_ + 1)) {
      this.clx[i_91_] = trunc((i + (((i32(i_88_ - i))) * random())));
      this.clz[i_91_] = trunc((i_89_ + (((i32(i_90_ - i_89_))) * random())));
      let f = fr((0.25 + (random() * 1.25)));
      let f_92_ = fr((((200.0 + (random() * 700.0))) * f));
      if (xtgraphics.careermode) {
      }
      this.clax[i_91_][0][0] = trunc((f_92_ * 0.3826));
      this.claz[i_91_][0][0] = trunc((f_92_ * 0.9238));
      this.clay[i_91_][0][0] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][1] = trunc((f_92_ * 0.7071));
      this.claz[i_91_][0][1] = trunc((f_92_ * 0.7071));
      this.clay[i_91_][0][1] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][2] = trunc((f_92_ * 0.9238));
      this.claz[i_91_][0][2] = trunc((f_92_ * 0.3826));
      this.clay[i_91_][0][2] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][3] = trunc((f_92_ * 0.9238));
      this.claz[i_91_][0][3] = i32(-trunc((f_92_ * 0.3826)));
      this.clay[i_91_][0][3] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][4] = trunc((f_92_ * 0.7071));
      this.claz[i_91_][0][4] = i32(-trunc((f_92_ * 0.7071)));
      this.clay[i_91_][0][4] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][5] = trunc((f_92_ * 0.3826));
      this.claz[i_91_][0][5] = i32(-trunc((f_92_ * 0.9238)));
      this.clay[i_91_][0][5] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][6] = i32(-trunc((f_92_ * 0.3826)));
      this.claz[i_91_][0][6] = i32(-trunc((f_92_ * 0.9238)));
      this.clay[i_91_][0][6] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][7] = i32(-trunc((f_92_ * 0.7071)));
      this.claz[i_91_][0][7] = i32(-trunc((f_92_ * 0.7071)));
      this.clay[i_91_][0][7] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][8] = i32(-trunc((f_92_ * 0.9238)));
      this.claz[i_91_][0][8] = i32(-trunc((f_92_ * 0.3826)));
      this.clay[i_91_][0][8] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][9] = i32(-trunc((f_92_ * 0.9238)));
      this.claz[i_91_][0][9] = trunc((f_92_ * 0.3826));
      this.clay[i_91_][0][9] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][10] = i32(-trunc((f_92_ * 0.7071)));
      this.claz[i_91_][0][10] = trunc((f_92_ * 0.7071));
      this.clay[i_91_][0][10] = trunc((((25.0 - (random() * 50.0))) * f));
      this.clax[i_91_][0][11] = i32(-trunc((f_92_ * 0.3826)));
      this.claz[i_91_][0][11] = trunc((f_92_ * 0.9238));
      this.clay[i_91_][0][11] = trunc((((25.0 - (random() * 50.0))) * f));
      for (let i_93_ = 0; i_93_ < 12; i_93_ = i32(i_93_ + 1)) {
        let i_94_ = i32(i_93_ - 1);
        if (i_94_ === -1) {
          i_94_ = 11;
        }
        let i_95_ = i32(i_93_ + 1);
        if (i_95_ === 12) {
          i_95_ = 0;
        }
        this.clax[i_91_][0][i_93_] = idiv(((i32((idiv(((i32(this.clax[i_91_][0][i_94_] + this.clax[i_91_][0][i_95_]))), 2)) + this.clax[i_91_][0][i_93_]))), 2);
        this.clay[i_91_][0][i_93_] = idiv(((i32((idiv(((i32(this.clay[i_91_][0][i_94_] + this.clay[i_91_][0][i_95_]))), 2)) + this.clay[i_91_][0][i_93_]))), 2);
        this.claz[i_91_][0][i_93_] = idiv(((i32((idiv(((i32(this.claz[i_91_][0][i_94_] + this.claz[i_91_][0][i_95_]))), 2)) + this.claz[i_91_][0][i_93_]))), 2);
      }
      for (let i_96_ = 0; i_96_ < 12; i_96_ = i32(i_96_ + 1)) {
        f_92_ = fr((1.2 + (0.6 * random())));
        this.clax[i_91_][1][i_96_] = trunc((fr(fr(this.clax[i_91_][0][i_96_]) * f_92_)));
        this.claz[i_91_][1][i_96_] = trunc((fr(fr(this.claz[i_91_][0][i_96_]) * f_92_)));
        this.clay[i_91_][1][i_96_] = trunc((this.clay[i_91_][0][i_96_] - (100.0 * random())));
        f_92_ = fr((1.1 + (0.3 * random())));
        this.clax[i_91_][2][i_96_] = trunc((fr(fr(this.clax[i_91_][1][i_96_]) * f_92_)));
        this.claz[i_91_][2][i_96_] = trunc((fr(fr(this.claz[i_91_][1][i_96_]) * f_92_)));
        this.clay[i_91_][2][i_96_] = trunc((this.clay[i_91_][1][i_96_] - (240.0 * random())));
      }
      this.cmx[i_91_] = 0;
      for (let i_97_ = 0; i_97_ < 12; i_97_ = i32(i_97_ + 1)) {
        let i_98_ = i32(i_97_ - 1);
        if (i_98_ === -1) {
          i_98_ = 11;
        }
        let i_99_ = i32(i_97_ + 1);
        if (i_99_ === 12) {
          i_99_ = 0;
        }
        this.clay[i_91_][1][i_97_] = idiv(((i32((idiv(((i32(this.clay[i_91_][1][i_98_] + this.clay[i_91_][1][i_99_]))), 2)) + this.clay[i_91_][1][i_97_]))), 2);
        this.clay[i_91_][2][i_97_] = idiv(((i32((idiv(((i32(this.clay[i_91_][2][i_98_] + this.clay[i_91_][2][i_99_]))), 2)) + this.clay[i_91_][2][i_97_]))), 2);
        let i_100_ = trunc(Math.sqrt(i32((Math.imul(this.clax[i_91_][2][i_97_], this.clax[i_91_][2][i_97_])) + (Math.imul(this.claz[i_91_][2][i_97_], this.claz[i_91_][2][i_97_])))));
        if (i_100_ > this.cmx[i_91_]) {
          this.cmx[i_91_] = i_100_;
        }
      }
      for (let i_101_ = 0; i_101_ < 6; i_101_ = i32(i_101_ + 1)) {
        let d = random();
        let d_102_ = random();
        for (let i_103_ = 0; i_103_ < 3; i_103_ = i32(i_103_ + 1)) {
          f_92_ = fr((fr(fr(this.clds[i_103_]) * 1.0499999523162842)) - fr(this.clds[i_103_]));
          this.clc[i_91_][0][i_101_][i_103_] = trunc((this.clds[i_103_] + (f_92_ * d)));
          if (this.clc[i_91_][0][i_101_][i_103_] > 255) {
            this.clc[i_91_][0][i_101_][i_103_] = 255;
          }
          if (this.clc[i_91_][0][i_101_][i_103_] < 0) {
            this.clc[i_91_][0][i_101_][i_103_] = 0;
          }
          this.clc[i_91_][1][i_101_][i_103_] = trunc(((fr(fr(this.clds[i_103_]) * 1.0499999523162842)) + (f_92_ * d_102_)));
          if (this.clc[i_91_][1][i_101_][i_103_] > 255) {
            this.clc[i_91_][1][i_101_][i_103_] = 255;
          }
          if (this.clc[i_91_][1][i_101_][i_103_] < 0) {
            this.clc[i_91_][1][i_101_][i_103_] = 0;
          }
        }
      }
    }
  }

  drawclouds(graphics2d) {
    for (let i = 0; i < this.noc; i = i32(i + 1)) {
      let i_104_ = i32(this.cx + trunc((fr((fr(fr(((i32((i32(this.clx[i] - (idiv(this.x, 20)))) - this.cx)))) * this.cos(this.xz))) - (fr(fr(((i32((i32(this.clz[i] - (idiv(this.z, 20)))) - this.cz)))) * this.sin(this.xz)))))));
      let i_105_ = i32(this.cz + trunc((fr((fr(fr(((i32((i32(this.clx[i] - (idiv(this.x, 20)))) - this.cx)))) * this.sin(this.xz))) + (fr(fr(((i32((i32(this.clz[i] - (idiv(this.z, 20)))) - this.cz)))) * this.cos(this.xz)))))));
      let i_106_ = i32(this.cz + trunc((fr((fr(fr(((i32((i32(this.cldd[4] - (idiv(this.y, 20)))) - this.cy)))) * this.sin(this.zy))) + (fr(fr(((i32(i_105_ - this.cz)))) * this.cos(this.zy)))))));
      let i_107_ = this.xs(i32(i_104_ + this.cmx[i]), i_106_);
      let i_108_ = this.xs(i32(i_104_ - this.cmx[i]), i_106_);
      if ((((i_107_ > 0) && (i_108_ < this.w)) && (i_106_ > i32(-this.cmx[i]))) && ((i32(i_107_ - i_108_)) > 20)) {
        let is = objArray(3).map(() => intArray(12));
        let is_109_ = objArray(3).map(() => intArray(12));
        let is_110_ = objArray(3).map(() => intArray(12));
        let is_111_ = intArray(12);
        let is_112_ = intArray(12);
        let bool_116_ = true;
        for (let i_120_ = 0; i_120_ < 3; i_120_ = i32(i_120_ + 1)) {
          for (let i_121_ = 0; i_121_ < 12; i_121_ = i32(i_121_ + 1)) {
            is[i_120_][i_121_] = i32((i32(this.clax[i][i_120_][i_121_] + this.clx[i])) - (idiv(this.x, 20)));
            is_110_[i_120_][i_121_] = i32((i32(this.claz[i][i_120_][i_121_] + this.clz[i])) - (idiv(this.z, 20)));
            is_109_[i_120_][i_121_] = i32((i32(this.clay[i][i_120_][i_121_] + this.cldd[4])) - (idiv(this.y, 20)));
          }
          this.rot(is[i_120_], is_110_[i_120_], this.cx, this.cz, this.xz, 12);
          this.rot(is_109_[i_120_], is_110_[i_120_], this.cy, this.cz, this.zy, 12);
        }
        for (let i_122_ = 0; i_122_ < 12; i_122_ = i32(i_122_ + 2)) {
          let i_123_ = 0;
          let i_124_ = 0;
          let i_125_ = 0;
          let i_126_ = 0;
          bool_116_ = true;
          let i_127_ = 0;
          let i_128_ = 0;
          let i_129_ = 0;
          for (let i_130_ = 0; i_130_ < 6; i_130_ = i32(i_130_ + 1)) {
            let i_131_ = 0;
            let i_132_ = 1;
            if (i_130_ === 0) {
              i_131_ = i_122_;
            }
            if (i_130_ === 1) {
              i_131_ = i32(i_122_ + 1);
              if (i_131_ >= 12) {
                i_131_ = i32(i_131_ - 12);
              }
            }
            if (i_130_ === 2) {
              i_131_ = i32(i_122_ + 2);
              if (i_131_ >= 12) {
                i_131_ = i32(i_131_ - 12);
              }
            }
            if (i_130_ === 3) {
              i_131_ = i32(i_122_ + 2);
              if (i_131_ >= 12) {
                i_131_ = i32(i_131_ - 12);
              }
              i_132_ = 2;
            }
            if (i_130_ === 4) {
              i_131_ = i32(i_122_ + 1);
              if (i_131_ >= 12) {
                i_131_ = i32(i_131_ - 12);
              }
              i_132_ = 2;
            }
            if (i_130_ === 5) {
              i_131_ = i_122_;
              i_132_ = 2;
            }
            is_111_[i_130_] = this.xs(is[i_132_][i_131_], is_110_[i_132_][i_131_]);
            is_112_[i_130_] = this.ys(is_109_[i_132_][i_131_], is_110_[i_132_][i_131_]);
            i_128_ = i32(i_128_ + is[i_132_][i_131_]);
            i_127_ = i32(i_127_ + is_109_[i_132_][i_131_]);
            i_129_ = i32(i_129_ + is_110_[i_132_][i_131_]);
            if ((is_112_[i_130_] < 0) || (is_110_[0][i_130_] < 10)) {
              i_123_ = i32(i_123_ + 1);
            }
            if ((is_112_[i_130_] > this.h) || (is_110_[0][i_130_] < 10)) {
              i_124_ = i32(i_124_ + 1);
            }
            if ((is_111_[i_130_] < 0) || (is_110_[0][i_130_] < 10)) {
              i_125_ = i32(i_125_ + 1);
            }
            if ((is_111_[i_130_] > this.w) || (is_110_[0][i_130_] < 10)) {
              i_126_ = i32(i_126_ + 1);
            }
          }
          if ((((i_125_ === 6) || (i_123_ === 6)) || (i_124_ === 6)) || (i_126_ === 6)) {
            bool_116_ = false;
          }
          if (bool_116_) {
            i_128_ = idiv(i_128_, 6);
            i_127_ = idiv(i_127_, 6);
            i_129_ = idiv(i_129_, 6);
            let i_133_ = trunc(Math.sqrt(i32((i32((Math.imul(((i32(this.cy - i_127_))), (i32(this.cy - i_127_)))) + (Math.imul(((i32(this.cx - i_128_))), (i32(this.cx - i_128_)))))) + (Math.imul(i_129_, i_129_)))));
            if (i_133_ < this.fade[7]) {
              let i_134_ = this.clc[i][1][idiv(i_122_, 2)][0];
              let i_135_ = this.clc[i][1][idiv(i_122_, 2)][1];
              let i_136_ = this.clc[i][1][idiv(i_122_, 2)][2];
              for (let i_137_ = 0; i_137_ < 16; i_137_ = i32(i_137_ + 1)) {
                if (i_133_ > this.fade[i_137_]) {
                  i_134_ = idiv(((i32((Math.imul(i_134_, this.fogd)) + this.cfade[0]))), (i32(this.fogd + 1)));
                  i_135_ = idiv(((i32((Math.imul(i_135_, this.fogd)) + this.cfade[1]))), (i32(this.fogd + 1)));
                  i_136_ = idiv(((i32((Math.imul(i_136_, this.fogd)) + this.cfade[2]))), (i32(this.fogd + 1)));
                }
              }
              graphics2d.setColor(i_134_, i_135_, i_136_);
              graphics2d.fillPolygon(is_111_, is_112_, 6);
              if (this.effect[5]) {
                let n = this.polyoutline[1];
              }
            }
          }
        }
        for (let i_138_ = 0; i_138_ < 12; i_138_ = i32(i_138_ + 2)) {
          let i_139_ = 0;
          let i_140_ = 0;
          let i_141_ = 0;
          let i_142_ = 0;
          bool_116_ = true;
          let i_143_ = 0;
          let i_144_ = 0;
          let i_145_ = 0;
          for (let i_146_ = 0; i_146_ < 6; i_146_ = i32(i_146_ + 1)) {
            let i_147_ = 0;
            let i_148_ = 0;
            if (i_146_ === 0) {
              i_147_ = i_138_;
            }
            if (i_146_ === 1) {
              i_147_ = i32(i_138_ + 1);
              if (i_147_ >= 12) {
                i_147_ = i32(i_147_ - 12);
              }
            }
            if (i_146_ === 2) {
              i_147_ = i32(i_138_ + 2);
              if (i_147_ >= 12) {
                i_147_ = i32(i_147_ - 12);
              }
            }
            if (i_146_ === 3) {
              i_147_ = i32(i_138_ + 2);
              if (i_147_ >= 12) {
                i_147_ = i32(i_147_ - 12);
              }
              i_148_ = 1;
            }
            if (i_146_ === 4) {
              i_147_ = i32(i_138_ + 1);
              if (i_147_ >= 12) {
                i_147_ = i32(i_147_ - 12);
              }
              i_148_ = 1;
            }
            if (i_146_ === 5) {
              i_147_ = i_138_;
              i_148_ = 1;
            }
            is_111_[i_146_] = this.xs(is[i_148_][i_147_], is_110_[i_148_][i_147_]);
            is_112_[i_146_] = this.ys(is_109_[i_148_][i_147_], is_110_[i_148_][i_147_]);
            i_144_ = i32(i_144_ + is[i_148_][i_147_]);
            i_143_ = i32(i_143_ + is_109_[i_148_][i_147_]);
            i_145_ = i32(i_145_ + is_110_[i_148_][i_147_]);
            if ((is_112_[i_146_] < 0) || (is_110_[0][i_146_] < 10)) {
              i_139_ = i32(i_139_ + 1);
            }
            if ((is_112_[i_146_] > this.h) || (is_110_[0][i_146_] < 10)) {
              i_140_ = i32(i_140_ + 1);
            }
            if ((is_111_[i_146_] < 0) || (is_110_[0][i_146_] < 10)) {
              i_141_ = i32(i_141_ + 1);
            }
            if ((is_111_[i_146_] > this.w) || (is_110_[0][i_146_] < 10)) {
              i_142_ = i32(i_142_ + 1);
            }
          }
          if ((((i_141_ === 6) || (i_139_ === 6)) || (i_140_ === 6)) || (i_142_ === 6)) {
            bool_116_ = false;
          }
          if (bool_116_) {
            i_144_ = idiv(i_144_, 6);
            i_143_ = idiv(i_143_, 6);
            i_145_ = idiv(i_145_, 6);
            let i_149_ = trunc(Math.sqrt(i32((i32((Math.imul(((i32(this.cy - i_143_))), (i32(this.cy - i_143_)))) + (Math.imul(((i32(this.cx - i_144_))), (i32(this.cx - i_144_)))))) + (Math.imul(i_145_, i_145_)))));
            if (i_149_ < this.fade[7]) {
              let i_150_ = this.clc[i][0][idiv(i_138_, 2)][0];
              let i_151_ = this.clc[i][0][idiv(i_138_, 2)][1];
              let i_152_ = this.clc[i][0][idiv(i_138_, 2)][2];
              for (let i_153_ = 0; i_153_ < 16; i_153_ = i32(i_153_ + 1)) {
                if (i_149_ > this.fade[i_153_]) {
                  i_150_ = idiv(((i32((Math.imul(i_150_, this.fogd)) + this.cfade[0]))), (i32(this.fogd + 1)));
                  i_151_ = idiv(((i32((Math.imul(i_151_, this.fogd)) + this.cfade[1]))), (i32(this.fogd + 1)));
                  i_152_ = idiv(((i32((Math.imul(i_152_, this.fogd)) + this.cfade[2]))), (i32(this.fogd + 1)));
                }
              }
              graphics2d.setColor(i_150_, i_151_, i_152_);
              graphics2d.fillPolygon(is_111_, is_112_, 6);
              if (this.effect[5]) {
                let n2 = this.polyoutline[1];
              }
            }
          }
        }
        let i_154_ = 0;
        let i_155_ = 0;
        let i_156_ = 0;
        let i_157_ = 0;
        bool_116_ = true;
        let i_158_ = 0;
        let i_159_ = 0;
        let i_160_ = 0;
        for (let i_161_ = 0; i_161_ < 12; i_161_ = i32(i_161_ + 1)) {
          is_111_[i_161_] = this.xs(is[0][i_161_], is_110_[0][i_161_]);
          is_112_[i_161_] = this.ys(is_109_[0][i_161_], is_110_[0][i_161_]);
          i_159_ = i32(i_159_ + is[0][i_161_]);
          i_158_ = i32(i_158_ + is_109_[0][i_161_]);
          i_160_ = i32(i_160_ + is_110_[0][i_161_]);
          if ((is_112_[i_161_] < 0) || (is_110_[0][i_161_] < 10)) {
            i_154_ = i32(i_154_ + 1);
          }
          if ((is_112_[i_161_] > this.h) || (is_110_[0][i_161_] < 10)) {
            i_155_ = i32(i_155_ + 1);
          }
          if ((is_111_[i_161_] < 0) || (is_110_[0][i_161_] < 10)) {
            i_156_ = i32(i_156_ + 1);
          }
          if ((is_111_[i_161_] > this.w) || (is_110_[0][i_161_] < 10)) {
            i_157_ = i32(i_157_ + 1);
          }
        }
        if ((((i_156_ === 12) || (i_154_ === 12)) || (i_155_ === 12)) || (i_157_ === 12)) {
          bool_116_ = false;
        }
        if (bool_116_) {
          i_159_ = idiv(i_159_, 12);
          i_158_ = idiv(i_158_, 12);
          i_160_ = idiv(i_160_, 12);
          let i_162_ = trunc(Math.sqrt(i32((i32((Math.imul(((i32(this.cy - i_158_))), (i32(this.cy - i_158_)))) + (Math.imul(((i32(this.cx - i_159_))), (i32(this.cx - i_159_)))))) + (Math.imul(i_160_, i_160_)))));
          if (i_162_ < this.fade[7]) {
            let i_163_ = this.clds[0];
            let i_164_ = this.clds[1];
            let i_165_ = this.clds[2];
            for (let i_166_ = 0; i_166_ < 16; i_166_ = i32(i_166_ + 1)) {
              if (i_162_ > this.fade[i_166_]) {
                i_163_ = idiv(((i32((Math.imul(i_163_, this.fogd)) + this.cfade[0]))), (i32(this.fogd + 1)));
                i_164_ = idiv(((i32((Math.imul(i_164_, this.fogd)) + this.cfade[1]))), (i32(this.fogd + 1)));
                i_165_ = idiv(((i32((Math.imul(i_165_, this.fogd)) + this.cfade[2]))), (i32(this.fogd + 1)));
              }
            }
            graphics2d.setColor(i_163_, i_164_, i_165_);
            graphics2d.fillPolygon(is_111_, is_112_, 12);
            if (this.effect[5]) {
              let n3 = this.polyoutline[1];
            }
          }
        }
      }
    }
  }

  newmountains(paramInt1, paramInt2, paramInt3, paramInt4, x, xtgraphics) {
    let localRandom = new Random(this.mgen);
    this.nmt = trunc((20.0 + (10.0 * localRandom.nextDouble())));
    if (xtgraphics.careermode && ((((((this.effect[8] || (x === 11)) || this.effect[11]) || (x === 22)) || (x === 24)) || (x === 7)))) {
      this.nmt = 0;
    }
    let i = idiv(((i32(paramInt1 + paramInt2))), 60);
    let j = idiv(((i32(paramInt3 + paramInt4))), 60);
    let k = idiv(Math.max(i32(paramInt2 - paramInt1), i32(paramInt4 - paramInt3)), 60);
    this.mrd = null;
    this.nmv = null;
    this.mtx = null;
    this.mty = null;
    this.mtz = null;
    this.mtc = null;
    this.mrd = intArray(this.nmt);
    this.nmv = intArray(this.nmt);
    this.mtx = objArray(this.nmt);
    this.mty = objArray(this.nmt);
    this.mtz = objArray(this.nmt);
    this.mtc = objArray(this.nmt);
    let arrayOfInt1 = intArray(this.nmt);
    let arrayOfInt2 = intArray(this.nmt);
    for (let m = 0; m < this.nmt; m = i32(m + 1)) {
      let n = 85;
      let f1 = 0.5;
      let f2 = 0.5;
      arrayOfInt1[m] = trunc((10000.0 + (localRandom.nextDouble() * 10000.0)));
      let i2 = trunc((localRandom.nextDouble() * 360.0));
      if (localRandom.nextDouble() > localRandom.nextDouble()) {
        f1 = fr((0.2 + (localRandom.nextDouble() * 0.35)));
        f2 = fr((0.2 + (localRandom.nextDouble() * 0.35)));
        this.nmv[m] = trunc((f1 * ((24.0 + (16.0 * localRandom.nextDouble())))));
        n = trunc((85.0 + (10.0 * localRandom.nextDouble())));
      } else {
        f1 = fr((0.3 + (localRandom.nextDouble() * 1.1)));
        f2 = fr((0.2 + (localRandom.nextDouble() * 0.35)));
        this.nmv[m] = trunc((f1 * ((12.0 + (8.0 * localRandom.nextDouble())))));
        n = trunc((104.0 - (10.0 * localRandom.nextDouble())));
      }
      this.mtx[m] = intArray(Math.imul(this.nmv[m], 2));
      this.mty[m] = intArray(Math.imul(this.nmv[m], 2));
      this.mtz[m] = intArray(Math.imul(this.nmv[m], 2));
      this.mtc[m] = objArray(this.nmv[m]).map(() => intArray(3));
      for (let i3 = 0; i3 < this.nmv[m]; i3 = i32(i3 + 1)) {
        this.mtx[m][i3] = trunc((((((Math.imul(i3, 500)) + (((localRandom.nextDouble() * 800.0) - 400.0))) - (Math.imul(250, (i32(this.nmv[m] - 1)))))) * f1));
        this.mtx[m][i32(i3 + this.nmv[m])] = trunc((((((Math.imul(i3, 500)) + (((localRandom.nextDouble() * 800.0) - 400.0))) - (Math.imul(250, (i32(this.nmv[m] - 1)))))) * f1));
        this.mtx[m][this.nmv[m]] = trunc((this.mtx[m][0] - (((100.0 + (localRandom.nextDouble() * 600.0))) * f1)));
        this.mtx[m][i32((Math.imul(this.nmv[m], 2)) - 1)] = trunc((this.mtx[m][i32(this.nmv[m] - 1)] + (((100.0 + (localRandom.nextDouble() * 600.0))) * f1)));
        if ((i3 === 0) || (i3 === (i32(this.nmv[m] - 1)))) {
          this.mty[m][i3] = trunc(((((-400.0 - (1200.0 * localRandom.nextDouble()))) * f2) + this.ground));
        }
        if ((i3 === 1) || (i3 === (i32(this.nmv[m] - 2)))) {
          this.mty[m][i3] = trunc(((((-1000.0 - (1450.0 * localRandom.nextDouble()))) * f2) + this.ground));
        }
        if ((i3 > 1) && (i3 < (i32(this.nmv[m] - 2)))) {
          this.mty[m][i3] = trunc(((((-1600.0 - (1700.0 * localRandom.nextDouble()))) * f2) + this.ground));
        }
        this.mty[m][i32(i3 + this.nmv[m])] = i32(this.ground - 70);
        this.mtz[m][i3] = i32((i32(j + k)) + arrayOfInt1[m]);
        this.mtz[m][i32(i3 + this.nmv[m])] = i32((i32(j + k)) + arrayOfInt1[m]);
        let f3 = fr((0.5 + (localRandom.nextDouble() * 0.5)));
        this.mtc[m][i3][0] = trunc((fr((fr(170.0 * f3)) + (fr((fr(170.0 * f3)) * ((fr(fr(this.snap[0]) / 100.0))))))));
        if (this.mtc[m][i3][0] > 255) {
          this.mtc[m][i3][0] = 255;
        }
        if (this.mtc[m][i3][0] < 0) {
          this.mtc[m][i3][0] = 0;
        }
        this.mtc[m][i3][1] = trunc((fr((fr(fr(n) * f3)) + (fr((fr(85.0 * f3)) * ((fr(fr(this.snap[1]) / 100.0))))))));
        if (this.mtc[m][i3][1] > 255) {
          this.mtc[m][i3][1] = 255;
        }
        if (this.mtc[m][i3][1] < 1) {
          this.mtc[m][i3][1] = 0;
        }
        this.mtc[m][i3][2] = 0;
      }
      for (let i3 = 1; i3 < (i32(this.nmv[m] - 1)); i3 = i32(i3 + 1)) {
        let i4 = i32(i3 - 1);
        let i5 = i32(i3 + 1);
        this.mty[m][i3] = idiv(((i32((idiv(((i32(this.mty[m][i4] + this.mty[m][i5]))), 2)) + this.mty[m][i3]))), 2);
      }
      this.rot(this.mtx[m], this.mtz[m], i, j, i2, Math.imul(this.nmv[m], 2));
      arrayOfInt2[m] = 0;
    }
    for (let m = 0; m < this.nmt; m = i32(m + 1)) {
      for (let n = i32(m + 1); n < this.nmt; n = i32(n + 1)) {
        if (arrayOfInt1[m] < arrayOfInt1[n]) {
          let array = arrayOfInt2;
          let n2 = m;
          ++array[n2];
        } else {
          let array2 = arrayOfInt2;
          let n3 = n;
          ++array2[n3];
        }
      }
      this.mrd[arrayOfInt2[m]] = m;
    }
  }

  drawmountains(paramGraphics) {
    for (let i = 0; i < this.nmt; i = i32(i + 1)) {
      let j = this.mrd[i];
      let k = i32(this.cx + trunc((fr((fr(fr(((i32((i32(this.mtx[j][0] - (idiv(this.x, 30)))) - this.cx)))) * this.cos(this.xz))) - (fr(fr(((i32((i32(this.mtz[j][0] - (idiv(this.z, 30)))) - this.cz)))) * this.sin(this.xz)))))));
      let m = i32(this.cz + trunc((fr((fr(fr(((i32((i32(this.mtx[j][0] - (idiv(this.x, 30)))) - this.cx)))) * this.sin(this.xz))) + (fr(fr(((i32((i32(this.mtz[j][0] - (idiv(this.z, 30)))) - this.cz)))) * this.cos(this.xz)))))));
      let n = i32(this.cz + trunc((fr((fr(fr(((i32((i32(this.mty[j][0] - (idiv(this.y, 30)))) - this.cy)))) * this.sin(this.zy))) + (fr(fr(((i32(m - this.cz)))) * this.cos(this.zy)))))));
      let i2 = i32(this.cx + trunc((fr((fr(fr(((i32((i32(this.mtx[j][i32(this.nmv[j] - 1)] - (idiv(this.x, 30)))) - this.cx)))) * this.cos(this.xz))) - (fr(fr(((i32((i32(this.mtz[j][i32(this.nmv[j] - 1)] - (idiv(this.z, 30)))) - this.cz)))) * this.sin(this.xz)))))));
      let i3 = i32(this.cz + trunc((fr((fr(fr(((i32((i32(this.mtx[j][i32(this.nmv[j] - 1)] - (idiv(this.x, 30)))) - this.cx)))) * this.sin(this.xz))) + (fr(fr(((i32((i32(this.mtz[j][i32(this.nmv[j] - 1)] - (idiv(this.z, 30)))) - this.cz)))) * this.cos(this.xz)))))));
      let i4 = i32(this.cz + trunc((fr((fr(fr(((i32((i32(this.mty[j][i32(this.nmv[j] - 1)] - (idiv(this.y, 30)))) - this.cy)))) * this.sin(this.zy))) + (fr(fr(((i32(i3 - this.cz)))) * this.cos(this.zy)))))));
      if ((this.xs(i2, i4) > 0) && (this.xs(k, n) < this.w)) {
        let arrayOfInt1 = intArray(Math.imul(this.nmv[j], 2));
        let arrayOfInt2 = intArray(Math.imul(this.nmv[j], 2));
        let arrayOfInt3 = intArray(Math.imul(this.nmv[j], 2));
        for (let i5 = 0; i5 < (Math.imul(this.nmv[j], 2)); i5 = i32(i5 + 1)) {
          arrayOfInt1[i5] = i32(this.mtx[j][i5] - (idiv(this.x, 30)));
          arrayOfInt2[i5] = i32(this.mty[j][i5] - (idiv(this.y, 30)));
          arrayOfInt3[i5] = i32(this.mtz[j][i5] - (idiv(this.z, 30)));
        }
        let i5 = trunc(Math.sqrt(i32((Math.imul(arrayOfInt1[idiv(this.nmv[j], 4)], arrayOfInt1[idiv(this.nmv[j], 4)])) + (Math.imul(arrayOfInt3[idiv(this.nmv[j], 4)], arrayOfInt3[idiv(this.nmv[j], 4)])))));
        this.rot(arrayOfInt1, arrayOfInt3, this.cx, this.cz, this.xz, Math.imul(this.nmv[j], 2));
        this.rot(arrayOfInt2, arrayOfInt3, this.cy, this.cz, this.zy, Math.imul(this.nmv[j], 2));
        let arrayOfInt4 = intArray(4);
        let arrayOfInt5 = intArray(4);
        let i6 = 0;
        let i7 = 0;
        let i8 = 0;
        let i9 = 0;
        let i10 = 1;
        for (let i11 = 0; i11 < (i32(this.nmv[j] - 1)); i11 = i32(i11 + 1)) {
          i6 = 0;
          i7 = 0;
          i8 = 0;
          i9 = 0;
          i10 = 1;
          for (let i12 = 0; i12 < 4; i12 = i32(i12 + 1)) {
            let i13 = i32(i12 + i11);
            if (i12 === 2) {
              i13 = i32((i32(i11 + this.nmv[j])) + 1);
            }
            if (i12 === 3) {
              i13 = i32(i11 + this.nmv[j]);
            }
            arrayOfInt4[i12] = this.xs(arrayOfInt1[i13], arrayOfInt3[i13]);
            arrayOfInt5[i12] = this.ys(arrayOfInt2[i13], arrayOfInt3[i13]);
            if ((arrayOfInt5[i12] < 0) || (arrayOfInt3[i13] < 10)) {
              i6 = i32(i6 + 1);
            }
            if ((arrayOfInt5[i12] > this.h) || (arrayOfInt3[i13] < 10)) {
              i7 = i32(i7 + 1);
            }
            if ((arrayOfInt4[i12] < 0) || (arrayOfInt3[i13] < 10)) {
              i8 = i32(i8 + 1);
            }
            if ((arrayOfInt4[i12] > this.w) || (arrayOfInt3[i13] < 10)) {
              i9 = i32(i9 + 1);
            }
          }
          if ((((i8 === 4) || (i6 === 4)) || (i7 === 4)) || (i9 === 4)) {
            i10 = 0;
          }
          if (i10 !== 0) {
            let f = fr((fr((fr((fr(fr(i5) / 2500.0)) + (fr(((fr(8000.0 - fr(this.fade[0])))) / 1000.0)))) - 2.0)) - (fr(((fr(fr((Math.abs(this.y) | 0)) - 250.0))) / 5000.0)));
            if ((f > 0.0) && (f < 10.0)) {
              if (f < 3.5) {
                f = 3.5;
              }
              let i13 = trunc((fr(((fr((fr(fr((i32(this.mtc[j][i11][0] + this.cgrnd[0]))) + (fr(fr(this.csky[0]) * f)))) + (fr(fr(this.cfade[0]) * f))))) / ((fr(2.0 + (fr(f * 2.0))))))));
              let i14 = trunc((fr(((fr((fr(fr((i32(this.mtc[j][i11][1] + this.cgrnd[1]))) + (fr(fr(this.csky[1]) * f)))) + (fr(fr(this.cfade[1]) * f))))) / ((fr(2.0 + (fr(f * 2.0))))))));
              let i15 = trunc((fr(((fr((fr(fr((i32(this.mtc[j][i11][2] + this.cgrnd[2]))) + (fr(fr(this.csky[2]) * f)))) + (fr(fr(this.cfade[2]) * f))))) / ((fr(2.0 + (fr(f * 2.0))))))));
              paramGraphics.setColor(i13, i14, i15);
              paramGraphics.fillPolygon(arrayOfInt4, arrayOfInt5, 4);
            }
          }
        }
      }
    }
  }

  newstars(x, xtgraphics) {
    this.stx = null;
    this.stz = null;
    this.stc = null;
    this.bst = null;
    this.twn = null;
    this.nst = 0;
    if (this.lightson) {
      let random = new Random(100000);
      this.nst = 50;
      if (xtgraphics.careermode) {
        if (((x === 11) || (x === 24)) || (x === 16)) {
          this.nst = 0;
        }
        if (this.effect[8]) {
          this.nst = 120;
        }
        if (this.effect[11]) {
          this.nst = 180;
        }
      }
      let starrange = 2000.0;
      if (this.effect[8]) {
        starrange = 20000.0;
      }
      this.stx = intArray(this.nst);
      this.stz = intArray(this.nst);
      this.stc = objArray(this.nst).map(() => objArray(2).map(() => intArray(3)));
      this.bst = new Array(this.nst).fill(false);
      this.twn = intArray(this.nst);
      for (let i = 0; i < this.nst; i = i32(i + 1)) {
        this.stx[i] = trunc(((starrange * random.nextDouble()) - (starrange / 2.0)));
        this.stz[i] = trunc(((starrange * random.nextDouble()) - (starrange / 2.0)));
        let i_212_ = trunc((3.0 * random.nextDouble()));
        if (i_212_ >= 3) {
          i_212_ = 0;
        }
        if (i_212_ <= -1) {
          i_212_ = 2;
        }
        let i_213_ = i32(i_212_ + 1);
        if (random.nextDouble() > random.nextDouble()) {
          i_213_ = i32(i_212_ - 1);
        }
        if (i_213_ === 3) {
          i_213_ = 0;
        }
        if (i_213_ === -1) {
          i_213_ = 2;
        }
        for (let i_214_ = 0; i_214_ < 3; i_214_ = i32(i_214_ + 1)) {
          this.stc[i][0][i_214_] = 200;
          if (i_212_ === i_214_) {
            let array = this.stc[i][0];
            let n = i_214_;
            array[n] = i32(array[n] + trunc((55.0 * random.nextDouble())));
          }
          if (i_213_ === i_214_) {
            let array2 = this.stc[i][0];
            let n2 = i_214_;
            array2[n2] = i32(array2[n2] + 55);
          }
          this.stc[i][0][i_214_] = idiv(((i32((Math.imul(this.stc[i][0][i_214_], 2)) + this.csky[i_214_]))), 3);
          this.stc[i][1][i_214_] = idiv(((i32(this.stc[i][0][i_214_] + this.csky[i_214_]))), 2);
        }
        this.twn[i] = trunc((4.0 * random.nextDouble()));
        if (random.nextDouble() > 0.8) {
          this.bst[i] = true;
        } else {
          this.bst[i] = false;
        }
      }
    }
  }

  drawstars(graphics2d) {
    if (this.effect[8]) {
      this.effecttime = i32(this.effecttime + 1);
    }
    let newstz = intArray(this.nst);
    let starzsort = intArray(this.nst);
    for (let a = 0; a < this.nst; a = i32(a + 1)) {
      starzsort[a] = this.stz[a];
    }
    Arrays.sort(starzsort);
    let minstarz = starzsort[0];
    let maxstarz = starzsort[i32(this.nst - 1)];
    let totalstarz = i32(maxstarz - minstarz);
    let starraise = 0;
    if (this.effect[8]) {
      starraise = 1500;
    }
    for (let i = 0; i < this.nst; i = i32(i + 1)) {
      newstz[i] = this.stz[i];
      if (this.effect[8]) {
        let starspeed = 500;
        if ((i32((i32(this.stz[i] + (Math.imul(this.effecttime, starspeed)))) - (Math.imul(this.starfase[i], totalstarz)))) <= maxstarz) {
          newstz[i] = i32((i32(this.stz[i] + (Math.imul(this.effecttime, starspeed)))) - (Math.imul(this.starfase[i], totalstarz)));
        } else {
          let starfase = this.starfase;
          let n = i;
          ++starfase[n];
        }
      }
      let i_215_ = i32(this.cx + trunc((fr((fr(fr(this.stx[i]) * this.cos(this.xz))) - (fr(fr(newstz[i]) * this.sin(this.xz)))))));
      let i_216_ = i32(this.cz + trunc((fr((fr(fr(this.stx[i]) * this.sin(this.xz))) + (fr(fr(newstz[i]) * this.cos(this.xz)))))));
      let starsections = 6;
      if (this.effect[11]) {
        for (let a2 = 0; a2 < starsections; a2 = i32(a2 + 1)) {
          if ((i >= (idiv((Math.imul(this.nst, a2)), starsections))) && (i < (idiv((Math.imul(this.nst, (i32(a2 + 1)))), starsections)))) {
            starraise = i32(-600 + (Math.imul(a2, (idiv(600, (i32(starsections - 1)))))));
          }
        }
      }
      let i_217_ = i32((i32(this.cy - starraise)) + trunc((fr((fr(-200.0 * this.cos(this.zy))) - (fr(fr(i_216_) * this.sin(this.zy)))))));
      let i_218_ = i32(this.cz + trunc((fr((fr(-200.0 * this.sin(this.zy))) + (fr(fr(i_216_) * this.cos(this.zy)))))));
      i_215_ = this.xs(i_215_, i_218_);
      i_217_ = this.ys(i_217_, i_218_);
      let starception = false;
      if (this.effect[11] && ((((i === 121) || (i === 125)) || (i === 129)))) {
        starception = true;
      }
      if ((((((i32(i_215_ - 1)) > this.iw) && ((i32(i_215_ + 3)) < this.w)) && ((i32(i_217_ - 1)) > this.ih)) && ((i32(i_217_ + 3)) < this.h)) && !starception) {
        if (this.twn[i] === 0) {
          let i_219_ = trunc((3.0 * random()));
          if (i_219_ >= 3) {
            i_219_ = 0;
          }
          if (i_219_ <= -1) {
            i_219_ = 2;
          }
          let i_220_ = i32(i_219_ + 1);
          if (random() > random()) {
            i_220_ = i32(i_219_ - 1);
          }
          if (i_220_ === 3) {
            i_220_ = 0;
          }
          if (i_220_ === -1) {
            i_220_ = 2;
          }
          for (let i_221_ = 0; i_221_ < 3; i_221_ = i32(i_221_ + 1)) {
            this.stc[i][0][i_221_] = 200;
            if (i_219_ === i_221_) {
              let array = this.stc[i][0];
              let n2 = i_221_;
              array[n2] = i32(array[n2] + trunc((55.0 * random())));
            }
            if (i_220_ === i_221_) {
              let array2 = this.stc[i][0];
              let n3 = i_221_;
              array2[n3] = i32(array2[n3] + 55);
            }
            this.stc[i][0][i_221_] = idiv(((i32((Math.imul(this.stc[i][0][i_221_], 2)) + this.csky[i_221_]))), 3);
            this.stc[i][1][i_221_] = idiv(((i32(this.stc[i][0][i_221_] + this.csky[i_221_]))), 2);
          }
          this.twn[i] = 3;
        } else {
          let twn = this.twn;
          let n4 = i;
          --twn[n4];
        }
        let i_222_ = 0;
        if (this.bst[i]) {
          i_222_ = 1;
        }
        if (this.effect[5]) {
          for (let a3 = 0; a3 < 2; a3 = i32(a3 + 1)) {
          }
        }
        graphics2d.setColor(this.stc[i][1][0], this.stc[i][1][1], this.stc[i][1][2]);
        graphics2d.fillRect(i32(i_215_ - 1), i_217_, i32(3 + i_222_), i32(1 + i_222_));
        graphics2d.fillRect(i_215_, i32(i_217_ - 1), i32(1 + i_222_), i32(3 + i_222_));
        graphics2d.setColor(this.stc[i][0][0], this.stc[i][0][1], this.stc[i][0][2]);
        graphics2d.fillRect(i_215_, i_217_, i32(1 + i_222_), i32(1 + i_222_));
      }
    }
  }

  setpolys(i, j, k) {
    this.polycolour[0] = i;
    this.polycolour[1] = j;
    this.polycolour[2] = k;
    this.cpol[0] = trunc((fr(fr(i) + (fr(fr(i) * ((fr(fr(this.snap[0]) / 100.0))))))));
    if (this.cpol[0] > 255) {
      this.cpol[0] = 255;
    }
    if (this.cpol[0] < 0) {
      this.cpol[0] = 0;
    }
    this.cpol[1] = trunc((fr(fr(j) + (fr(fr(j) * ((fr(fr(this.snap[1]) / 100.0))))))));
    if (this.cpol[1] > 255) {
      this.cpol[1] = 255;
    }
    if (this.cpol[1] < 0) {
      this.cpol[1] = 0;
    }
    this.cpol[2] = trunc((fr(fr(k) + (fr(fr(k) * ((fr(fr(this.snap[2]) / 100.0))))))));
    if (this.cpol[2] > 255) {
      this.cpol[2] = 255;
    }
    if (this.cpol[2] < 0) {
      this.cpol[2] = 0;
    }
    this.dispolys = 0;
    for (i = 0; i < 3; i = i32(i + 1)) {
      this.crgrnd[i] = trunc(((((this.cpol[i] * 0.99) + this.cgrnd[i])) / 2.0));
      this.ogrnd[i] = trunc(((((this.cpol[i] * 0.99) + this.cgrnd[i])) / 2.0));
    }
  }

  ys(i, j) {
    if (j < 10) {
      j = 10;
    }
    return i32((idiv((Math.imul(((i32(j - this.focus_point))), (i32(this.cy - i)))), j)) + i);
  }

  sin(i) {
    while (i >= 360) {
      i = i32(i - 360);
    }
    while (i < 0) {
      i = i32(i + 360);
    }
    return this.tsin[i];
  }

  reset() {
    this.vxz = 180;
    this.trx = 0;
    this.trz = 0;
    this.atrx = 0;
    this.atrz = 0;
    this.fallen = 0;
    this.fo = 1.0;
    this.gofo = fr((0.33000001311302185 + (random() * 1.34)));
    for (let a = 0; a < 3; a = i32(a + 1)) {
      this.snap[a] = 0;
      this.osnap[a] = 0;
      this.skycolour[a] = 0;
      this.fadecolour[a] = 0;
      this.grndcolour[a] = 0;
      this.polycolour[a] = 0;
    }
    for (let a = 0; a < 8; a = i32(a + 1)) {
    }
    for (let a = 0; a < 100; a = i32(a + 1)) {
      this.effect[a] = false;
      this.oneffect[a] = false;
    }
    for (let a = 0; a < 1000; a = i32(a + 1)) {
      this.starfase[a] = 0;
    }
    this.csky[0] = 170;
    this.csky[1] = 220;
    this.csky[2] = 255;
    this.reducepolys = 1.0;
    this.glassfade = 65;
    this.verydark = false;
    this.makefase = 0;
    this.darklevel = 0;
    this.shadowtrans = 80;
    this.changingsnap = false;
    this.snowheight = 0;
    this.cfade[0] = 255;
    this.icehills = false;
    this.greystage = 0;
    this.darken = false;
    this.effecttime = 0;
    this.trk = false;
    this.snowno = 0;
    this.darkenfor = 0;
    this.switchfase = 0;
    this.groundcolour = false;
    this.drowned = false;
    for (let a = 1; a < 3; a = i32(a + 1)) {
      this.cfade[a] = 220;
    }
    this.fade[0] = 3000;
  }

  setfade(i, j, k) {
    this.fadecolour[0] = i;
    this.fadecolour[1] = j;
    this.fadecolour[2] = k;
    this.cfade[0] = trunc((fr(fr(i) + (fr(fr(i) * ((fr(fr(this.snap[0]) / 100.0))))))));
    if (this.cfade[0] > 255) {
      this.cfade[0] = 255;
    }
    if (this.cfade[0] < 0) {
      this.cfade[0] = 0;
    }
    this.cfade[1] = trunc((fr(fr(j) + (fr(fr(j) * ((fr(fr(this.snap[1]) / 100.0))))))));
    if (this.cfade[1] > 255) {
      this.cfade[1] = 255;
    }
    if (this.cfade[1] < 0) {
      this.cfade[1] = 0;
    }
    this.cfade[2] = trunc((fr(fr(k) + (fr(fr(k) * ((fr(fr(this.snap[2]) / 100.0))))))));
    if (this.cfade[2] > 255) {
      this.cfade[2] = 255;
    }
    if (this.cfade[2] < 0) {
      this.cfade[2] = 0;
    }
    this.ocfade[0] = this.cfade[0];
    this.ocfade[1] = this.cfade[1];
    this.ocfade[2] = this.cfade[2];
  }

  d(paramGraphics2D) {
    this.nsp = 0;
    if (this.zy > 90) {
      this.zy = 90;
    }
    if (this.zy < -90) {
      this.zy = -90;
    }
    if (this.xz > 360) {
      this.xz = i32(this.xz - 360);
    }
    if (this.xz < 0) {
      this.xz = i32(this.xz + 360);
    }
    if (this.y > 0) {
      this.y = 0;
    }
    this.ground = i32(250 - this.y);
    if (this.greystage > 0) {
      for (let a = 0; a < 4; a = i32(a + 1)) {
        if (this.greystage === (i32(a + 2))) {
          if (this.grndcolour[0] > (i32(99 - (Math.imul(a, 7))))) {
            let grndcolour = this.grndcolour;
            let n2 = 0;
            --grndcolour[n2];
            let polycolour = this.polycolour;
            let n3 = 0;
            --polycolour[n3];
          }
          if (this.grndcolour[1] > (i32(186 - (Math.imul(a, 36))))) {
            let grndcolour2 = this.grndcolour;
            let n4 = 1;
            grndcolour2[n4] = i32(grndcolour2[n4] - 3);
            let polycolour2 = this.polycolour;
            let n5 = 1;
            polycolour2[n5] = i32(polycolour2[n5] - 3);
          }
          if (this.grndcolour[2] > (i32(102 - (Math.imul(a, 8))))) {
            let grndcolour3 = this.grndcolour;
            let n6 = 2;
            --grndcolour3[n6];
            let polycolour3 = this.polycolour;
            let n7 = 2;
            --polycolour3[n7];
          }
        }
      }
      for (let a = 0; a < 3; a = i32(a + 1)) {
        this.cgrnd[a] = trunc((fr(fr(this.grndcolour[a]) + (fr(fr(this.grndcolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
        this.cpol[a] = trunc((fr(fr(this.polycolour[a]) + (fr(fr(this.polycolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
        this.crgrnd[a] = trunc(((((this.cpol[a] * 0.99) + this.cgrnd[a])) / 2.0));
      }
    }
    if (this.effect[11]) {
      for (let a = 0; a < 3; a = i32(a + 1)) {
        this.crgrnd[a] = this.cgrnd[a];
      }
    }
    if (this.effect[3]) {
      if (this.makefase > 250) {
        this.oneffect[3] = true;
      } else {
        this.makefase = i32(this.makefase + 1);
      }
      if (this.oneffect[3]) {
        this.effecttime = i32(this.effecttime + 1);
        for (let a = 0; a < 3; a = i32(a + 1)) {
          this.cgrnd[a] = trunc((fr(fr(this.grndcolour[a]) + (fr(fr(this.grndcolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
          this.cpol[a] = trunc((fr(fr(this.polycolour[a]) + (fr(fr(this.polycolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
          this.crgrnd[a] = trunc(((((this.cpol[a] * 0.99) + this.cgrnd[a])) / 2.0));
        }
        if ((this.effecttime > 0) && (this.effecttime < 250)) {
          for (let a = 1; a < 3; a = i32(a + 1)) {
            if (this.grndcolour[a] > 150) {
              let grndcolour4 = this.grndcolour;
              let n8 = a;
              grndcolour4[n8] = i32(grndcolour4[n8] - 8);
            }
            if (this.polycolour[a] > 140) {
              let polycolour4 = this.polycolour;
              let n9 = a;
              polycolour4[n9] = i32(polycolour4[n9] - 8);
            }
          }
        }
        if ((this.effecttime >= 250) && (this.effecttime < 500)) {
          if (this.grndcolour[0] > 150) {
            let grndcolour5 = this.grndcolour;
            let n10 = 0;
            grndcolour5[n10] = i32(grndcolour5[n10] - 8);
          }
          if (this.polycolour[0] > 140) {
            let polycolour5 = this.polycolour;
            let n11 = 0;
            polycolour5[n11] = i32(polycolour5[n11] - 8);
          }
          if (this.grndcolour[2] < 230) {
            let grndcolour6 = this.grndcolour;
            let n12 = 2;
            grndcolour6[n12] = i32(grndcolour6[n12] + 8);
          }
          if (this.polycolour[2] < 220) {
            let polycolour6 = this.polycolour;
            let n13 = 2;
            polycolour6[n13] = i32(polycolour6[n13] + 8);
          }
        }
        if ((this.effecttime >= 500) && (this.effecttime < 750)) {
          if (this.grndcolour[2] > 150) {
            let grndcolour7 = this.grndcolour;
            let n14 = 2;
            grndcolour7[n14] = i32(grndcolour7[n14] - 8);
          }
          if (this.polycolour[2] > 140) {
            let polycolour7 = this.polycolour;
            let n15 = 2;
            polycolour7[n15] = i32(polycolour7[n15] - 8);
          }
          if (this.grndcolour[0] < 230) {
            let grndcolour8 = this.grndcolour;
            let n16 = 0;
            grndcolour8[n16] = i32(grndcolour8[n16] + 8);
          }
          if (this.polycolour[0] < 220) {
            let polycolour8 = this.polycolour;
            let n17 = 0;
            polycolour8[n17] = i32(polycolour8[n17] + 8);
          }
          if (this.grndcolour[1] < 190) {
            let grndcolour9 = this.grndcolour;
            let n18 = 1;
            grndcolour9[n18] = i32(grndcolour9[n18] + 4);
          }
          if (this.polycolour[1] < 180) {
            let polycolour9 = this.polycolour;
            let n19 = 1;
            polycolour9[n19] = i32(polycolour9[n19] + 4);
          }
        }
        if ((this.effecttime >= 750) && (this.effecttime < 1000)) {
          if (this.grndcolour[0] > 150) {
            let grndcolour10 = this.grndcolour;
            let n20 = 0;
            grndcolour10[n20] = i32(grndcolour10[n20] - 8);
          }
          if (this.polycolour[0] > 140) {
            let polycolour10 = this.polycolour;
            let n21 = 0;
            polycolour10[n21] = i32(polycolour10[n21] - 8);
          }
          if (this.grndcolour[1] < 230) {
            let grndcolour11 = this.grndcolour;
            let n22 = 1;
            grndcolour11[n22] = i32(grndcolour11[n22] + 4);
          }
          if (this.polycolour[1] < 220) {
            let polycolour11 = this.polycolour;
            let n23 = 1;
            polycolour11[n23] = i32(polycolour11[n23] + 4);
          }
        }
        if (this.effecttime >= 1000) {
          for (let a = 0; a < 3; a = i32(a + 1)) {
            if (a !== 1) {
              if (this.grndcolour[a] < 230) {
                let grndcolour12 = this.grndcolour;
                let n24 = a;
                grndcolour12[n24] = i32(grndcolour12[n24] + 8);
              }
              if (this.polycolour[a] < 220) {
                let polycolour12 = this.polycolour;
                let n25 = a;
                polycolour12[n25] = i32(polycolour12[n25] + 8);
              }
            }
          }
          if (this.effecttime >= 1025) {
            this.effecttime = 0;
            this.oneffect[3] = false;
            this.makefase = 0;
          }
        }
      }
    }
    if (this.effect[2] && !this.trk) {
      if (this.makefase > 1000) {
        this.oneffect[2] = true;
      } else {
        this.makefase = i32(this.makefase + 1);
      }
      if (this.oneffect[2]) {
        this.effecttime = i32(this.effecttime + 1);
        if (this.switchfase < 10) {
          for (let a = 0; a < 3; a = i32(a + 1)) {
            let snap = this.snap;
            let n26 = a;
            snap[n26] = i32(snap[n26] - 2);
            this.csky[a] = trunc((fr(fr(this.skycolour[a]) + (fr(fr(this.skycolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
            this.cfade[a] = trunc((fr(fr(this.fadecolour[a]) + (fr(fr(this.fadecolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
            this.cgrnd[a] = trunc((fr(fr(this.grndcolour[a]) + (fr(fr(this.grndcolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
            this.cpol[a] = trunc((fr(fr(this.polycolour[a]) + (fr(fr(this.polycolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
            this.crgrnd[a] = trunc(((((this.cpol[a] * 0.99) + this.cgrnd[a])) / 2.0));
          }
          this.shadowtrans = i32(this.shadowtrans - 8);
          this.changingsnap = true;
          this.switchfase = i32(this.switchfase + 1);
        } else {
          this.changingsnap = false;
          this.verydark = true;
        }
        if (this.effecttime > 500) {
          for (let a = 0; a < 3; a = i32(a + 1)) {
            if (this.snap[a] < this.osnap[a]) {
              let snap2 = this.snap;
              let n27 = a;
              snap2[n27] = i32(snap2[n27] + 2);
              this.csky[a] = trunc((fr(fr(this.skycolour[a]) + (fr(fr(this.skycolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
              this.cfade[a] = trunc((fr(fr(this.fadecolour[a]) + (fr(fr(this.fadecolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
              this.cgrnd[a] = trunc((fr(fr(this.grndcolour[a]) + (fr(fr(this.grndcolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
              this.cpol[a] = trunc((fr(fr(this.polycolour[a]) + (fr(fr(this.polycolour[a]) * ((fr(fr(this.snap[a]) / 100.0))))))));
              this.crgrnd[a] = trunc(((((this.cpol[a] * 0.99) + this.cgrnd[a])) / 2.0));
              this.changingsnap = true;
              if (a === 0) {
                this.shadowtrans = i32(this.shadowtrans + 8);
              }
            } else {
              this.verydark = false;
              this.shadowtrans = 80;
              this.changingsnap = false;
              this.makefase = 0;
              this.switchfase = 0;
              this.oneffect[2] = false;
              this.effecttime = 0;
            }
          }
        }
      }
    }
    let arrayOfInt1 = intArray(4);
    let arrayOfInt2 = intArray(4);
    let i = this.cgrnd[0];
    let j = this.cgrnd[1];
    let k = this.cgrnd[2];
    let m = this.crgrnd[0];
    let n = this.crgrnd[1];
    let i2 = this.crgrnd[2];
    let i3 = this.h;
    for (let i4 = 0; i4 < 16; i4 = i32(i4 + 1)) {
      let i5 = this.fade[i4];
      let groundloc = this.ground;
      if (this.effect[4]) {
        groundloc = i32(this.ground + 2500);
      }
      let i6 = groundloc;
      if (this.zy !== 0) {
        i6 = i32(this.cy + trunc((fr((fr(fr(((i32(groundloc - this.cy)))) * this.cos(this.zy))) - (fr(fr(((i32(this.fade[i4] - this.cz)))) * this.sin(this.zy)))))));
        i5 = i32(this.cz + trunc((fr((fr(fr(((i32(groundloc - this.cy)))) * this.sin(this.zy))) + (fr(fr(((i32(this.fade[i4] - this.cz)))) * this.cos(this.zy)))))));
      }
      arrayOfInt1[0] = this.iw;
      arrayOfInt2[0] = this.ys(i6, i5);
      if (arrayOfInt2[0] < this.ih) {
        arrayOfInt2[0] = this.ih;
      }
      if (arrayOfInt2[0] > this.h) {
        arrayOfInt2[0] = this.h;
      }
      arrayOfInt1[1] = this.iw;
      arrayOfInt2[1] = i3;
      arrayOfInt1[2] = this.w;
      arrayOfInt2[2] = i3;
      arrayOfInt1[3] = this.w;
      arrayOfInt2[3] = arrayOfInt2[0];
      i3 = arrayOfInt2[0];
      if (i4 > 0) {
        m = idiv(((i32((Math.imul(m, 7)) + this.cfade[0]))), 8);
        n = idiv(((i32((Math.imul(n, 7)) + this.cfade[1]))), 8);
        i2 = idiv(((i32((Math.imul(i2, 7)) + this.cfade[2]))), 8);
        if (i4 < 3) {
          i = idiv(((i32((Math.imul(i, 7)) + this.cfade[0]))), 8);
          j = idiv(((i32((Math.imul(j, 7)) + this.cfade[1]))), 8);
          k = idiv(((i32((Math.imul(k, 7)) + this.cfade[2]))), 8);
        } else {
          i = m;
          j = n;
          k = i2;
        }
      }
      if ((arrayOfInt2[0] < this.h) && (arrayOfInt2[1] > this.ih)) {
        paramGraphics2D.setColor(i, j, k);
        paramGraphics2D.fillPolygon(arrayOfInt1, arrayOfInt2, 4);
      }
    }
    if (this.effect[0]) {
      this.makefase = i32(this.makefase + 1);
      if (((this.makefase % 90)) === 0) {
        this.oneffect[0] = true;
        this.makefase = 0;
      }
      if (this.oneffect[0]) {
        this.switchfase = i32(this.switchfase + 1);
        if (this.switchfase > 30) {
          this.switchfase = 30;
        }
        if (((this.switchfase % 30)) !== 0) {
          if (((this.switchfase % 15)) === 0) {
            if (this.decrease) {
              this.decrease = false;
            } else {
              this.decrease = true;
            }
            this.glowfase = 1;
          }
        } else {
          this.glowfase = 2;
        }
        if (!this.decrease) {
          let polyoutline = this.polyoutline;
          let n28 = 0;
          polyoutline[n28] = i32(polyoutline[n28] + 15);
        } else if (this.polyoutline[0] >= 15) {
          let polyoutline2 = this.polyoutline;
          let n29 = 0;
          polyoutline2[n29] = i32(polyoutline2[n29] - 15);
        }
        if (this.glowfase === 2) {
          this.polyoutline[0] = 0;
          this.decrease = false;
          this.switchfase = 0;
          this.glowfase = 0;
          this.oneffect[0] = false;
        }
      }
      this.polyoutline[1] = 0;
      this.polyoutline[2] = 0;
    }
    if (this.lightn !== -1) {
      if (!this.effect[1]) {
        if (this.lightn < 16) {
          if (this.lilo > (i32(this.lightn + 217))) {
            this.lilo = i32(this.lilo - 3);
          } else {
            this.lightn = trunc((fr(16.0 + (fr(16.0 * this.random())))));
          }
        } else if (this.lilo < (i32(this.lightn + 217))) {
          this.lilo = i32(this.lilo + 7);
        } else {
          this.lightn = trunc((fr(16.0 * this.random())));
        }
      } else {
        if (this.lightn < 16) {
          if (this.lilo > (i32(this.lightn + 217))) {
            this.lilo = i32(this.lilo - 5);
          } else {
            this.lightn = trunc((fr(24.0 + (fr(24.0 * this.random())))));
          }
        } else if (this.lilo < (i32(this.lightn + 217))) {
          this.lilo = i32(this.lilo + 12);
        } else {
          this.lightn = trunc((fr(24.0 * this.random())));
        }
        for (let a2 = 0; a2 < 3; a2 = i32(a2 + 1)) {
          this.cgrnd[a2] = i32(trunc((fr(fr(this.lilo) + (fr(fr(this.lilo) * ((fr(fr(this.snap[a2]) / 100.0)))))))) + 25);
          if (this.cgrnd[a2] > 255) {
            this.cgrnd[a2] = 255;
          }
          if (this.cgrnd[a2] < 0) {
            this.cgrnd[a2] = 0;
          }
          this.cpol[a2] = i32(this.cgrnd[a2] - 7);
          if (this.cpol[a2] < 0) {
            this.cpol[a2] = 0;
          }
          this.cfade[a2] = i32(this.csky[a2] + 10);
          if (this.cfade[a2] < 0) {
            this.cpol[a2] = 0;
          }
        }
      }
      for (let a2 = 0; a2 < 3; a2 = i32(a2 + 1)) {
        this.csky[a2] = trunc((fr(fr(this.lilo) + (fr(fr(this.lilo) * ((fr(fr(this.snap[a2]) / 100.0))))))));
        if (this.csky[a2] > 255) {
          this.csky[a2] = 255;
        }
        if (this.csky[a2] < 0) {
          this.csky[a2] = 0;
        }
      }
    }
    i = this.csky[0];
    j = this.csky[1];
    k = this.csky[2];
    let i4 = i;
    let i5 = j;
    let i7 = k;
    let i8 = i32(this.cy + trunc((fr((fr(fr(((i32((i32(this.skyline - 700)) - this.cy)))) * this.cos(this.zy))) - (fr(fr(((i32(7000 - this.cz)))) * this.sin(this.zy)))))));
    let i9 = i32(this.cz + trunc((fr((fr(fr(((i32((i32(this.skyline - 700)) - this.cy)))) * this.sin(this.zy))) + (fr(fr(((i32(7000 - this.cz)))) * this.cos(this.zy)))))));
    i8 = this.ys(i8, i9);
    let i10 = this.ih;
    for (let i11 = 0; i11 < 16; i11 = i32(i11 + 1)) {
      let i12 = this.fade[i11];
      let i13 = this.skyline;
      if (this.zy !== 0) {
        i13 = i32(this.cy + trunc((fr((fr(fr(((i32(this.skyline - this.cy)))) * this.cos(this.zy))) - (fr(fr(((i32(this.fade[i11] - this.cz)))) * this.sin(this.zy)))))));
        i12 = i32(this.cz + trunc((fr((fr(fr(((i32(this.skyline - this.cy)))) * this.sin(this.zy))) + (fr(fr(((i32(this.fade[i11] - this.cz)))) * this.cos(this.zy)))))));
      }
      arrayOfInt1[0] = this.iw;
      arrayOfInt2[0] = this.ys(i13, i12);
      if (arrayOfInt2[0] > this.h) {
        arrayOfInt2[0] = this.h;
      }
      if (arrayOfInt2[0] < this.ih) {
        arrayOfInt2[0] = this.ih;
      }
      arrayOfInt1[1] = this.iw;
      arrayOfInt2[1] = i10;
      arrayOfInt1[2] = this.w;
      arrayOfInt2[2] = i10;
      arrayOfInt1[3] = this.w;
      arrayOfInt2[3] = arrayOfInt2[0];
      i10 = arrayOfInt2[0];
      if (i11 > 0) {
        i = idiv(((i32((Math.imul(i, 7)) + this.cfade[0]))), 8);
        j = idiv(((i32((Math.imul(j, 7)) + this.cfade[1]))), 8);
        k = idiv(((i32((Math.imul(k, 7)) + this.cfade[2]))), 8);
      }
      if (arrayOfInt2[1] < i8) {
        i4 = i;
        i5 = j;
        i7 = k;
      }
      if ((arrayOfInt2[0] > this.ih) && (arrayOfInt2[1] < this.h)) {
        paramGraphics2D.setColor(i, j, k);
        paramGraphics2D.fillPolygon(arrayOfInt1, arrayOfInt2, 4);
      }
    }
    arrayOfInt1[0] = this.iw;
    arrayOfInt2[0] = i10;
    arrayOfInt1[1] = this.iw;
    arrayOfInt2[1] = i3;
    arrayOfInt1[2] = this.w;
    arrayOfInt2[2] = i3;
    arrayOfInt1[3] = this.w;
    arrayOfInt2[3] = i10;
    if ((arrayOfInt2[0] < this.h) && (arrayOfInt2[1] > this.ih)) {
      let f = fr(((fr(fr((Math.abs(this.y) | 0)) - 250.0))) / fr(((Math.imul(this.fade[0], 2)))));
      if (f < 0.0) {
        f = 0.0;
      }
      if (f > 1.0) {
        f = 1.0;
      }
      i = trunc((fr(((fr((fr(fr(i) * ((fr(1.0 - f))))) + (fr(fr(m) * ((fr(1.0 + f)))))))) / 2.0)));
      j = trunc((fr(((fr((fr(fr(j) * ((fr(1.0 - f))))) + (fr(fr(n) * ((fr(1.0 + f)))))))) / 2.0)));
      k = trunc((fr(((fr((fr(fr(k) * ((fr(1.0 - f))))) + (fr(fr(i2) * ((fr(1.0 + f)))))))) / 2.0)));
      paramGraphics2D.setColor(i, j, k);
      paramGraphics2D.fillPolygon(arrayOfInt1, arrayOfInt2, 4);
    }
    if (this.resdown !== 2) {
      for (let i14 = 1; i14 < 20; i14 = i32(i14 + 1)) {
        let i12 = 7000;
        let i13 = i32((i32(this.skyline - 700)) - (Math.imul(i14, 70)));
        if ((this.zy !== 0) && (i14 !== 19)) {
          i13 = i32(this.cy + trunc((fr((fr(fr(((i32((i32((i32(this.skyline - 700)) - (Math.imul(i14, 70)))) - this.cy)))) * this.cos(this.zy))) - (fr(fr(((i32(7000 - this.cz)))) * this.sin(this.zy)))))));
          i12 = i32(this.cz + trunc((fr((fr(fr(((i32((i32((i32(this.skyline - 700)) - (Math.imul(i14, 70)))) - this.cy)))) * this.sin(this.zy))) + (fr(fr(((i32(7000 - this.cz)))) * this.cos(this.zy)))))));
        }
        arrayOfInt1[0] = this.iw;
        if (i14 !== 19) {
          arrayOfInt2[0] = this.ys(i13, i12);
          if (arrayOfInt2[0] > this.h) {
            arrayOfInt2[0] = this.h;
          }
          if (arrayOfInt2[0] < this.ih) {
            arrayOfInt2[0] = this.ih;
          }
        } else {
          arrayOfInt2[0] = this.ih;
        }
        arrayOfInt1[1] = this.iw;
        arrayOfInt2[1] = i8;
        arrayOfInt1[2] = this.w;
        arrayOfInt2[2] = i8;
        arrayOfInt1[3] = this.w;
        arrayOfInt2[3] = arrayOfInt2[0];
        i8 = arrayOfInt2[0];
        i4 = trunc(i4 * 0.991);
        i5 = trunc(i5 * 0.991);
        i7 = trunc(i7 * 0.998);
        if ((arrayOfInt2[1] > this.ih) && (arrayOfInt2[0] < this.h)) {
          paramGraphics2D.setColor(i4, i5, i7);
          paramGraphics2D.fillPolygon(arrayOfInt1, arrayOfInt2, 4);
        }
      }
      if (this.lightson && (this.nst > 0)) {
        this.drawstars(paramGraphics2D);
      }
      this.drawmountains(paramGraphics2D);
      this.drawclouds(paramGraphics2D);
    }
    if (!this.effect[10] && !this.effect[11]) {
      this.groundpolys(paramGraphics2D);
    }
    if (this.cpflik) {
      this.cpflik = false;
    } else {
      this.cpflik = true;
      this.elecr = fr((fr(this.random() * 15.0)) - 6.0);
    }
  }

  redrawpolys(g) {
    let arrayOfInt1 = intArray(4);
    let arrayOfInt2 = intArray(4);
    let fixgrnd = intArray(3);
    for (let i = 0; i < 3; i = i32(i + 1)) {
      fixgrnd[i] = trunc(((((this.cpol[i] * 0.99) + this.cgrnd[i])) / 2.0));
      this.crgrnd[i] = fixgrnd[i];
    }
    let i = this.cgrnd[0];
    let j = this.cgrnd[1];
    let k = this.cgrnd[2];
    let m = this.crgrnd[0];
    let n = this.crgrnd[1];
    let i2 = this.crgrnd[2];
    let i3 = this.h;
    for (let i4 = 0; i4 < 16; i4 = i32(i4 + 1)) {
      let i5 = this.fade[i4];
      let i6 = this.ground;
      if (this.zy !== 0) {
        i6 = i32(this.cy + trunc((fr((fr(fr(((i32(this.ground - this.cy)))) * this.cos(this.zy))) - (fr(fr(((i32(this.fade[i4] - this.cz)))) * this.sin(this.zy)))))));
        i5 = i32(this.cz + trunc((fr((fr(fr(((i32(this.ground - this.cy)))) * this.sin(this.zy))) + (fr(fr(((i32(this.fade[i4] - this.cz)))) * this.cos(this.zy)))))));
      }
      arrayOfInt1[0] = this.iw;
      arrayOfInt2[0] = this.ys(i6, i5);
      if (arrayOfInt2[0] < this.ih) {
        arrayOfInt2[0] = this.ih;
      }
      if (arrayOfInt2[0] > this.h) {
        arrayOfInt2[0] = this.h;
      }
      arrayOfInt1[1] = this.iw;
      arrayOfInt2[1] = i3;
      arrayOfInt1[2] = this.w;
      arrayOfInt2[2] = i3;
      arrayOfInt1[3] = this.w;
      arrayOfInt2[3] = arrayOfInt2[0];
      i3 = arrayOfInt2[0];
      if (i4 > 0) {
        m = idiv(((i32((Math.imul(m, 7)) + this.cfade[0]))), 8);
        n = idiv(((i32((Math.imul(n, 7)) + this.cfade[1]))), 8);
        i2 = idiv(((i32((Math.imul(i2, 7)) + this.cfade[2]))), 8);
        if (i4 < 3) {
          i = idiv(((i32((Math.imul(i, 7)) + this.cfade[0]))), 8);
          j = idiv(((i32((Math.imul(j, 7)) + this.cfade[1]))), 8);
          k = idiv(((i32((Math.imul(k, 7)) + this.cfade[2]))), 8);
        } else {
          i = m;
          j = n;
          k = i2;
        }
      }
      if ((arrayOfInt2[0] < this.h) && (arrayOfInt2[1] > this.ih)) {
        g.setColorOf(new Color(i, j, k, this.glassfade));
        g.fillPolygon(arrayOfInt1, arrayOfInt2, 4);
      }
    }
  }

  watch(paramContO, paramInt1, boost) {
    this.zy = 10;
    let i = ((2.0 + (Math.abs(this.bcxzwatch) / 4.0))) / 15.0;
    if (i > 1.3333333333333333) {
      i = 1.3333333333333333;
    }
    if (Math.abs(this.bcxzwatch) > (i / 15.0)) {
      if (this.bcxzwatch > 0.0) {
        this.bcxzwatch = this.bcxzwatch - (i / 15.0);
      } else {
        this.bcxzwatch = this.bcxzwatch + (i / 15.0);
      }
    } else if (this.bcxzwatch !== 0.0) {
      this.bcxzwatch = 0.0;
    }
    paramInt1 = paramInt1 + this.bcxzwatch;
    this.xz = trunc((-paramInt1));
    System.out.println(new StringBuilder().append(this.xz).toString());
    this.x = i32((i32(paramContO.x - this.cx)) + trunc((i32(-((i32((i32((i32(paramContO.z - 800)) - boost)) - paramContO.z)))) * Math.sin((paramInt1 * 3.141592653589793) / 180.0))));
    this.z = i32((i32(paramContO.z - this.cz)) + trunc((((i32((i32((i32(paramContO.z - 12000)) - boost)) - paramContO.z))) * Math.cos((paramInt1 * 3.141592653589793) / 180.0))));
    this.y = i32((i32((i32(paramContO.y - 3750)) - this.cy)) - boost);
  }

  rot(ai, ai1, i, j, k, l) {
    if (k !== 0) {
      for (let i2 = 0; i2 < l; i2 = i32(i2 + 1)) {
        let j2 = ai[i2];
        let k2 = ai1[i2];
        ai[i2] = i32(i + trunc((fr((fr(fr(((i32(j2 - i)))) * this.cos(k))) - (fr(fr(((i32(k2 - j)))) * this.sin(k)))))));
        ai1[i2] = i32(j + trunc((fr((fr(fr(((i32(j2 - i)))) * this.sin(k))) + (fr(fr(((i32(k2 - j)))) * this.cos(k)))))));
      }
    }
  }

  setsnap(i, j, k) {
    this.snap[0] = i;
    this.snap[1] = j;
    this.snap[2] = k;
    this.osnap[0] = i;
    this.osnap[1] = j;
    this.osnap[2] = k;
  }

  around(paramContO, paramBoolean) {
    if (this.flex !== 0) {
      this.flex = 0;
    }
    if (!paramBoolean) {
      if (!this.vert) {
        this.adv = i32(this.adv + 2);
      } else {
        this.adv = i32(this.adv - 2);
      }
      if (this.adv > 900) {
        this.vert = true;
      }
      if (this.adv < 2000) {
        this.vert = false;
      }
    } else {
      this.adv = i32(this.adv - 14);
    }
    let i = 2500;
    if (paramBoolean && (i < 1300)) {
      i = 1300;
    }
    if (i < 1000) {
      i = 1000;
    }
    this.y = i32(paramContO.y - 2000);
    if (this.y > 10) {
      this.vert = false;
    }
    this.x = i32(paramContO.x + trunc((fr(fr(((i32((i32(paramContO.x - i)) - paramContO.x)))) * this.cos(this.vxz)))));
    this.z = i32(paramContO.z + trunc((fr(fr(((i32((i32(paramContO.x - i)) - paramContO.x)))) * this.sin(this.vxz)))));
    if (!paramBoolean) {
      this.vxz = i32(this.vxz + 2);
    } else {
      this.vxz = i32(this.vxz + 4);
    }
    let j = 0;
    let k = this.y;
    if (k > 0) {
      k = 0;
    }
    let number = i32((i32(paramContO.y - k)) - this.cy);
    if (number === 0) {
      number = 1;
    }
    if (number < 0) {
      j = 2300;
    }
    let m = trunc(Math.sqrt(i32((Math.imul(((i32((i32(paramContO.z - this.z)) + this.cz))), (i32((i32(paramContO.z - this.z)) + this.cz)))) + (Math.imul(((i32((i32(paramContO.x - this.x)) - this.cx))), (i32((i32(paramContO.x - this.x)) - this.cx)))))));
    let n = trunc(((i32(90 + j)) - (Math.atan(idiv(m, number)) / 0.017453292519943295)));
    this.xz = i32(i32(-this.vxz) + 90);
    if (paramBoolean) {
      n = i32(n - 15);
    }
    this.zy = i32(this.zy + (idiv(((i32(n - this.zy))), 10)));
    if (this.trns !== 5) {
      this.trns = 5;
    }
  }

  setgrnd(i, j, k) {
    this.grndcolour[0] = i;
    this.grndcolour[1] = j;
    this.grndcolour[2] = k;
    this.cgrnd[0] = trunc((fr(fr(i) + (fr(fr(i) * ((fr(fr(this.snap[0]) / 100.0))))))));
    if (this.cgrnd[0] > 255) {
      this.cgrnd[0] = 255;
    }
    if (this.cgrnd[0] < 0) {
      this.cgrnd[0] = 0;
    }
    this.cgrnd[1] = trunc((fr(fr(j) + (fr(fr(j) * ((fr(fr(this.snap[1]) / 100.0))))))));
    if (this.cgrnd[1] > 255) {
      this.cgrnd[1] = 255;
    }
    if (this.cgrnd[1] < 0) {
      this.cgrnd[1] = 0;
    }
    this.cgrnd[2] = trunc((fr(fr(k) + (fr(fr(k) * ((fr(fr(this.snap[2]) / 100.0))))))));
    if (this.cgrnd[2] > 255) {
      this.cgrnd[2] = 255;
    }
    if (this.cgrnd[2] < 0) {
      this.cgrnd[2] = 0;
    }
    this.dispolys = 2;
    for (i = 0; i < 3; i = i32(i + 1)) {
      this.crgrnd[i] = trunc(((((this.cpol[i] * 0.99) + this.cgrnd[i])) / 2.0));
      this.ogrnd[i] = trunc(((((this.cpol[i] * 0.99) + this.cgrnd[i])) / 2.0));
    }
  }

  xs(i, j) {
    if (j < this.cz) {
      j = this.cz;
    }
    return i32((idiv((Math.imul(((i32(j - this.focus_point))), (i32(this.cx - i)))), j)) + i);
  }

  adjstfade(f) {
    if (f < 15.0) {
      this.fade[0] = trunc((fr(fr(this.origfade) - (fr(1000.0 * ((fr(15.0 - f))))))));
      if (this.fade[0] < 3000) {
        this.fade[0] = 3000;
      }
      this.fadfrom(this.fade[0]);
    } else if (this.fade[0] !== this.origfade) {
      let fade = this.fade;
      let n = 0;
      fade[n] = i32(fade[n] + 500);
      if (this.fade[0] > this.origfade) {
        this.fade[0] = this.origfade;
      }
      this.fadfrom(this.fade[0]);
    }
  }

  addsp(i, j, k) {
    if (this.nsp !== 101) {
      this.spx[this.nsp] = i;
      this.spz[this.nsp] = j;
      this.sprad[this.nsp] = k;
      this.nsp = i32(this.nsp + 1);
    }
  }

  aroundtrack(checkpoints) {
    this.y = i32(-this.hit);
    if (this.effect[9]) {
      this.y = i32(i32(-this.hit) - 30000);
    }
    this.x = i32((i32(this.cx + i32(this.trx))) + trunc((fr(17000.0 * this.cos(this.vxz)))));
    this.z = i32(i32(this.trz) + trunc((fr(17000.0 * this.sin(this.vxz)))));
    if (this.hit > 5000) {
      if (this.hit === 25000) {
        this.fo = 1.0;
        this.zy = 67;
        this.atrx = ((checkpoints.x[0] - this.trx)) / 116;
        this.atrz = ((checkpoints.z[0] - this.trz)) / 116;
        this.focus_point = 400;
      }
      this.hit = i32(this.hit - this.fallen);
      this.fallen = i32(this.fallen + 7);
      this.trx = this.trx + this.atrx;
      this.trz = this.trz + this.atrz;
      if (this.hit < 17600) {
        this.zy = i32(this.zy - 2);
      }
      if (this.fallen > 500) {
        this.fallen = 500;
      }
      if (this.hit <= 5000) {
        this.hit = 5000;
        this.fallen = 0;
      }
      this.vxz = i32(this.vxz + 3);
    } else {
      this.focus_point = trunc((fr(400.0 * this.fo)));
      if (Math.abs(fr(this.fo - this.gofo)) > 0.005) {
        if (this.fo < this.gofo) {
          this.fo = fr(this.fo + 0.004999999888241291);
        } else {
          this.fo = fr(this.fo - 0.004999999888241291);
        }
      } else {
        this.gofo = fr((0.3499999940395355 + (random() * 1.3)));
      }
      this.vxz = i32(this.vxz + 1);
      this.trx = this.trx - (((this.trx - checkpoints.x[this.ptr])) / 10);
      this.trz = this.trz - (((this.trz - checkpoints.z[this.ptr])) / 10);
      if (this.ptcnt === 7) {
        this.ptr = i32(this.ptr + 1);
        if (this.ptr >= checkpoints.n) {
          this.ptr = 0;
          this.nrnd = i32(this.nrnd + 1);
        }
        this.ptcnt = 0;
      } else {
        this.ptcnt = i32(this.ptcnt + 1);
      }
    }
    if (this.vxz > 360) {
      this.vxz = i32(this.vxz - 360);
    }
    this.xz = i32(i32(-this.vxz) - 90);
    let c = 0;
    if ((i32(i32(-this.y) - this.cy)) < 0) {
      c = 65356;
    }
    Math.sqrt((((((this.trz - this.z) + this.cz)) * (((this.trz - this.z) + this.cz))) + ((((this.trx - this.x) - this.cx)) * (((this.trx - this.x) - this.cx)))));
    if (this.cpflik) {
      this.cpflik = false;
    } else {
      this.cpflik = true;
    }
  }

  setsky(paramInt1, paramInt2, paramInt3) {
    this.osky[0] = paramInt1;
    this.osky[1] = paramInt2;
    this.osky[2] = paramInt3;
    this.skycolour[0] = paramInt1;
    this.skycolour[1] = paramInt2;
    this.skycolour[2] = paramInt3;
    for (let i = 0; i < 3; i = i32(i + 1)) {
      this.clds[i] = idiv(((i32((Math.imul(this.osky[i], this.cldd[3])) + this.cldd[i]))), (i32(this.cldd[3] + 1)));
      this.clds[i] = trunc(fr(fr(this.clds[i]) + ((fr(fr(this.clds[i]) * ((fr(fr(this.snap[i]) / 100.0))))))));
      if (this.clds[i] > 255) {
        this.clds[i] = 255;
      }
      if (this.clds[i] < 0) {
        this.clds[i] = 0;
      }
    }
    this.csky[0] = trunc((fr(fr(paramInt1) + (fr(fr(paramInt1) * ((fr(fr(this.snap[0]) / 100.0))))))));
    if (this.csky[0] > 255) {
      this.csky[0] = 255;
    }
    if (this.csky[0] < 0) {
      this.csky[0] = 0;
    }
    this.csky[1] = trunc((fr(fr(paramInt2) + (fr(fr(paramInt2) * ((fr(fr(this.snap[1]) / 100.0))))))));
    if (this.csky[1] > 255) {
      this.csky[1] = 255;
    }
    if (this.csky[1] < 0) {
      this.csky[1] = 0;
    }
    this.csky[2] = trunc((fr(fr(paramInt3) + (fr(fr(paramInt3) * ((fr(fr(this.snap[2]) / 100.0))))))));
    if (this.csky[2] > 255) {
      this.csky[2] = 255;
    }
    if (this.csky[2] < 0) {
      this.csky[2] = 0;
    }
    let arrayOfFloat = floatArray(3);
    Color.RGBtoHSB(this.csky[0], this.csky[1], this.csky[2], arrayOfFloat);
    this.ocsky[0] = this.csky[0];
    this.ocsky[1] = this.csky[1];
    this.ocsky[2] = this.csky[2];
  }

  fadfrom(paramInt) {
    if (paramInt > 12000) {
      paramInt = 12000;
    }
    for (let i = 0; i < 16; i = i32(i + 1)) {
      this.fade[i] = Math.imul((idiv(paramInt, 2)), (i32(i + 2)));
      this.originalfade[i] = Math.imul((idiv(paramInt, 2)), (i32(i + 2)));
    }
  }

  follow(paramContO, paramInt1, paramInt2, boost) {
    this.zy = 10;
    let i = i32(2 + (idiv((Math.abs(this.bcxz) | 0), 4)));
    if (i > 20) {
      i = 20;
    }
    if (paramInt2 !== 0) {
      if (paramInt2 === 1) {
        if (this.bcxz < 180) {
          this.bcxz = i32(this.bcxz + i);
        }
        if (this.bcxz > 180) {
          this.bcxz = 180;
        }
      }
      if (paramInt2 === -1) {
        if (this.bcxz > -180) {
          this.bcxz = i32(this.bcxz - i);
        }
        if (this.bcxz < -180) {
          this.bcxz = -180;
        }
      }
    } else if ((Math.abs(this.bcxz) | 0) > i) {
      if (this.bcxz > 0) {
        this.bcxz = i32(this.bcxz - i);
      } else {
        this.bcxz = i32(this.bcxz + i);
      }
    } else if (this.bcxz !== 0) {
      this.bcxz = 0;
    }
    paramInt1 = i32(paramInt1 + this.bcxz);
    this.xz = i32(-paramInt1);
    this.x = i32((i32(paramContO.x - this.cx)) + trunc((fr(fr(i32(-((i32((i32((i32(paramContO.z - 800)) - boost)) - paramContO.z))))) * this.sin(paramInt1)))));
    this.z = i32((i32(paramContO.z - this.cz)) + trunc((fr(fr(((i32((i32((i32(paramContO.z - 800)) - boost)) - paramContO.z)))) * this.cos(paramInt1)))));
    this.y = i32((i32((i32(paramContO.y - 250)) - this.cy)) - boost);
  }

  newpolys(i, j, k, l, trackers) {
    this.nrw = i32((idiv(j, trunc((1200.0 * this.reducepolys)))) + 1);
    this.ncl = i32((idiv(l, trunc((1200.0 * this.reducepolys)))) + 1);
    this.sgpx = i;
    this.sgpz = k;
    let i2 = 0;
    let j2 = 0;
    for (let k2 = 0; k2 < (Math.imul(this.nrw, this.ncl)); k2 = i32(k2 + 1)) {
      this.cgpx[k2] = i32((i32(i + trunc(((Math.imul(i2, 1200)) * this.reducepolys)))) + trunc(((random() * 1000.0) - 500.0)));
      this.cgpz[k2] = i32((i32(k + trunc(((Math.imul(j2, 1200)) * this.reducepolys)))) + trunc(((random() * 1000.0) - 500.0)));
      for (let i3 = 0; i3 < trackers.nt; i3 = i32(i3 + 1)) {
        if ((trackers.zy[i3] === 0) && (trackers.xy[i3] === 0)) {
          if ((trackers.radx[i3] < trackers.radz[i3]) && ((Math.abs(i32(this.cgpz[k2] - trackers.z[i3])) | 0) < trackers.radz[i3])) {
            while ((Math.abs(i32(this.cgpx[k2] - trackers.x[i3])) | 0) < trackers.radx[i3]) {
              let cgpx = this.cgpx;
              let n = k2;
              cgpx[n] = trunc(cgpx[n] + ((((random() * trackers.radx[i3]) * 2.0) - trackers.radx[i3])));
            }
          }
          if ((trackers.radz[i3] < trackers.radx[i3]) && ((Math.abs(i32(this.cgpx[k2] - trackers.x[i3])) | 0) < trackers.radx[i3])) {
            while ((Math.abs(i32(this.cgpz[k2] - trackers.z[i3])) | 0) < trackers.radz[i3]) {
              let cgpz = this.cgpz;
              let n2 = k2;
              cgpz[n2] = trunc(cgpz[n2] + ((((random() * trackers.radz[i3]) * 2.0) - trackers.radz[i3])));
            }
          }
        }
      }
      if (++i2 === this.nrw) {
        i2 = 0;
        j2 = i32(j2 + 1);
      }
    }
    let polysize = 1.0;
    for (let l2 = 0; l2 < (Math.imul(this.nrw, this.ncl)); l2 = i32(l2 + 1)) {
      this.ogpx[l2][0] = 0;
      this.ogpz[l2][0] = trunc((100.0 + ((random() * 600.0) * polysize)));
      this.ogpx[l2][1] = trunc(((((100.0 + (random() * 600.0))) * 0.7071) * polysize));
      this.ogpz[l2][1] = this.ogpx[l2][1];
      this.ogpx[l2][2] = trunc((100.0 + ((random() * 600.0) * polysize)));
      this.ogpz[l2][2] = 0;
      this.ogpx[l2][3] = trunc(((((100.0 + (random() * 600.0))) * 0.7071) * polysize));
      this.ogpz[l2][3] = i32(-this.ogpx[l2][3]);
      this.ogpx[l2][4] = 0;
      this.ogpz[l2][4] = i32(-trunc((100.0 + ((random() * 600.0) * polysize))));
      this.ogpx[l2][5] = i32(-trunc(((((100.0 + (random() * 600.0))) * 0.7071) * polysize)));
      this.ogpz[l2][5] = this.ogpx[l2][5];
      this.ogpx[l2][6] = i32(-trunc((100.0 + ((random() * 600.0) * polysize))));
      this.ogpz[l2][6] = 0;
      this.ogpx[l2][7] = i32(-trunc(((((100.0 + (random() * 600.0))) * 0.7071) * polysize)));
      this.ogpz[l2][7] = i32(-this.ogpx[l2][7]);
    }
  }

  transaround(paramContO1, paramContO2, paramInt) {
    if (this.flex !== 0) {
      this.flex = 0;
    }
    let i = idiv(((i32((Math.imul(paramContO1.x, (i32(20 - paramInt)))) + (Math.imul(paramContO2.x, paramInt))))), 20);
    let j = idiv(((i32((Math.imul(paramContO1.y, (i32(20 - paramInt)))) + (Math.imul(paramContO2.y, paramInt))))), 20);
    let k = idiv(((i32((Math.imul(paramContO1.z, (i32(20 - paramInt)))) + (Math.imul(paramContO2.z, paramInt))))), 20);
    if (!this.vert) {
      this.adv = i32(this.adv + 2);
    } else {
      this.adv = i32(this.adv - 2);
    }
    if (this.adv > 900) {
      this.vert = true;
    }
    if (this.adv < 2000) {
      this.vert = false;
    }
    let m = 2500;
    if (m < 1000) {
      m = 1000;
    }
    this.y = i32(j - 2000);
    if (this.y > 10) {
      this.vert = false;
    }
    this.x = i32(i + trunc((fr(fr(((i32((i32(i - m)) - i)))) * this.cos(this.vxz)))));
    this.z = i32(k + trunc((fr(fr(((i32((i32(i - m)) - i)))) * this.sin(this.vxz)))));
    this.vxz = i32(this.vxz + 2);
    let n = 0;
    let i2 = this.y;
    if (i2 > 0) {
      i2 = 0;
    }
    let number = i32((i32(j - i2)) - this.cy);
    if (number === 0) {
      number = 1;
    }
    if (number < 0) {
      n = 2300;
    }
    let i3 = trunc(Math.sqrt(i32((Math.imul(((i32((i32(k - this.z)) + this.cz))), (i32((i32(k - this.z)) + this.cz)))) + (Math.imul(((i32((i32(i - this.x)) - this.cx))), (i32((i32(i - this.x)) - this.cx)))))));
    let i4 = trunc(((i32(90 + n)) - (Math.atan(idiv(i3, number)) / 0.017453292519943295)));
    this.xz = i32(i32(-this.vxz) + 90);
    this.zy = i32(this.zy + (idiv(((i32(i4 - this.zy))), 10)));
    if (this.trns !== 5) {
      this.trns = 5;
    }
  }

  cos(i) {
    while (i >= 360) {
      i = i32(i - 360);
    }
    while (i < 0) {
      i = i32(i + 360);
    }
    return this.tcos[i];
  }
}
