// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/Mod.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { i32, objArray } from '../java.js';
import { DataInputStream, System, charAt, jstr } from './jawt.js';
import { ModInstrument } from './ModInstrument.js';

export class Mod {
  constructor(inputstream) {
    this.name = null;
    this.numtracks = 0;
    this.track_shift = 0;
    this.numpatterns = 0;
    this.patterns = null;
    this.insts = null;
    this.positions = null;
    this.song_length_patterns = 0;
    this.song_repeat_patterns = 0;
    this.s3m = false;
    try {
      this.LoadMod(inputstream);
    } catch (exception) {
      System.out.println('Error loading up a Mod: ' + exception);
    }
  }

  getNumPatterns() {
    return this.numpatterns;
  }

  toString() {
    return ((((((jstr(this.name) + ' (') + this.numtracks) + ' tracks, ') + this.numpatterns) + ' patterns, ') + this.insts.length) + ' samples)';
  }

  static readu16(datainputstream) {
    return (datainputstream.readShort() & 65535);
  }

  static readText(datainputstream, i) {
    let abyte0 = new Int8Array(i);
    datainputstream.readFully(abyte0, 0, i);
    for (let j = i32(i - 1); j >= 0; j = i32(j - 1)) {
      if (abyte0[j] !== 0) {
        return new String(abyte0, 0, 0, i32(j + 1));
      }
    }
    return '';
  }

  readSequence(datainputstream) {
    this.positions = new Int8Array(128);
    this.song_length_patterns = Mod.readu8(datainputstream);
    this.song_repeat_patterns = Mod.readu8(datainputstream);
    datainputstream.readFully(this.positions, 0, 128);
    if (this.song_repeat_patterns > this.song_length_patterns) {
      this.song_repeat_patterns = this.song_length_patterns;
    }
    this.numpatterns = 0;
    for (let i = 0; i < this.positions.length; i = i32(i + 1)) {
      if (this.positions[i] > this.numpatterns) {
        this.numpatterns = this.positions[i];
      }
    }
    this.numpatterns = i32(this.numpatterns + 1);
  }

  LoadMod(inputstream) {
    let datainputstream = new DataInputStream(inputstream);
    let byte0 = 15;
    this.numtracks = 4;
    this.name = Mod.readText(datainputstream, 20);
    datainputstream.mark(1068);
    datainputstream.skip(1060);
    let i = datainputstream.readInt();
    datainputstream.reset();
    for (let j = 0; j < Mod.voice_31_list.length; j = i32(j + 1)) {
      if (i === Mod.voice_31_list[j]) {
        byte0 = 31;
        break;
      }
    }
    if (byte0 === 31) {
      if (i === Mod.voice_8chn) {
        this.numtracks = 8;
      } else if (i === Mod.voice_6chn) {
        this.numtracks = 6;
      } else if (i === Mod.voice_28ch) {
        this.numtracks = 28;
      }
    }
    this.insts = objArray(byte0);
    for (let k = 0; k < byte0; k = i32(k + 1)) {
      this.insts[k] = Mod.readInstrument(datainputstream);
    }
    this.readSequence(datainputstream);
    datainputstream.skipBytes(4);
    this.readPatterns(datainputstream);
    try {
      for (let l = 0; l < byte0; l = i32(l + 1)) {
        Mod.readSampleData(datainputstream, this.insts[l]);
      }
    } catch (_ex) {
      System.out.println('Warning: EOF on MOD file');
    }
    datainputstream.close();
    inputstream.close();
  }

  static readSampleData(datainputstream, modinstrument) {
    datainputstream.readFully(modinstrument.samples, 0, modinstrument.sample_length);
    if (modinstrument.repeat_length > 3) {
      System.arraycopy(modinstrument.samples, modinstrument.repeat_point, modinstrument.samples, modinstrument.sample_length, 8);
    }
  }

  static readInstrument(datainputstream) {
    let modinstrument = new ModInstrument();
    modinstrument.name = Mod.readText(datainputstream, 22);
    modinstrument.sample_length = (Mod.readu16(datainputstream) << 1);
    modinstrument.samples = new Int8Array(i32(modinstrument.sample_length + 8));
    modinstrument.finetune_value = ((((Mod.readu8(datainputstream) << 4))) << 24 >> 24);
    modinstrument.volume = Mod.readu8(datainputstream);
    modinstrument.repeat_point = (Mod.readu16(datainputstream) << 1);
    modinstrument.repeat_length = (Mod.readu16(datainputstream) << 1);
    if (modinstrument.repeat_point > modinstrument.sample_length) {
      modinstrument.repeat_point = modinstrument.sample_length;
    }
    if ((i32(modinstrument.repeat_point + modinstrument.repeat_length)) > modinstrument.sample_length) {
      modinstrument.repeat_length = i32(modinstrument.sample_length - modinstrument.repeat_point);
    }
    return modinstrument;
  }

  static FOURCC(s) {
    return ((((((((charAt(s, 3) & 255))) | (((((charAt(s, 2) & 255))) << 8)))) | (((((charAt(s, 1) & 255))) << 16)))) | (((((charAt(s, 0) & 255))) << 24)));
  }

  getNumTracks() {
    return this.numtracks;
  }

  getName() {
    return this.name;
  }

  readPatterns(datainputstream) {
    let i = Math.imul((Math.imul(this.numtracks, 4)), 64);
    this.patterns = objArray(this.numpatterns);
    for (let j = 0; j < this.numpatterns; j = i32(j + 1)) {
      datainputstream.readFully(this.patterns[j] = new Int8Array(i), 0, i);
    }
  }

  static readu8(datainputstream) {
    return (datainputstream.readByte() & 255);
  }
}
Mod.voice_mk = 0;
Mod.voice_mk2 = 0;
Mod.voice_mk3 = 0;
Mod.voice_flt4 = 0;
Mod.voice_flt8 = 0;
Mod.voice_28ch = 0;
Mod.voice_8chn = 0;
Mod.voice_6chn = 0;
Mod.voice_31_list = null;
