// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/ModInstrument.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.


export class ModInstrument {
  constructor() {
    this.name = null;
    this.samples = null;
    this.sample_length = 0;
    this.finetune_rate = 0;
    this.period_low_limit = 0;
    this.period_high_limit = 0;
    this.finetune_value = 0;
    this.volume = 0;
    this.repeat_point = 0;
    this.repeat_length = 0;
  }
}
