// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/ModSlayer.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { i32, idiv, intArray, objArray } from '../java.js';
import { System } from './jawt.js';
import { ModTrackInfo } from './ModTrackInfo.js';
import { UlawUtils } from './UlawUtils.js';

export class ModSlayer {
  constructor(mod1, i, j, k) {
    this.def_tempo = 0;
    this.def_bpm = 0;
    this.vol_table = null;
    this.vol_adj = null;
    this.vol_shift = 0;
    this.mod = null;
    this.order_pos = 0;
    this.tempo = 0;
    this.tempo_wait = 0;
    this.bpm = 0;
    this.row = 0;
    this.break_row = 0;
    this.bpm_samples = 0;
    this.pattofs = 0;
    this.patt = null;
    this.numtracks = 0;
    this.tracks = null;
    this.mixspeed = 0;
    this.mod_done = false;
    this.bit16 = false;
    this.samplingrate = 0;
    this.oversample = 0;
    this.gain = 0;
    this.nloops = 0;
    this.loud = false;
    this.oln = 0;
    this.mod_done = false;
    this.nloops = 1;
    this.loud = false;
    this.oln = 0;
    this.samplingrate = i;
    this.gain = j;
    this.oversample = 1;
    this.mod = mod1;
    this.def_tempo = 6;
    this.def_bpm = k;
  }

  beattrack(modtrackinfo) {
    if (modtrackinfo.period_low_limit === 0) {
      modtrackinfo.period_low_limit = 1;
    }
    if ((((modtrackinfo.effect & 1))) !== 0) {
      modtrackinfo.volume = i32(modtrackinfo.volume + modtrackinfo.vol_slide);
      if (modtrackinfo.volume < 0) {
        modtrackinfo.volume = 0;
      }
      if (modtrackinfo.volume > 64) {
        modtrackinfo.volume = 64;
      }
    }
    if ((((modtrackinfo.effect & 2))) !== 0) {
      if (((modtrackinfo.period = i32(modtrackinfo.period + modtrackinfo.port_down))) > modtrackinfo.period_high_limit) {
        modtrackinfo.period = modtrackinfo.period_high_limit;
      }
      modtrackinfo.pitch = idiv(modtrackinfo.finetune_rate, modtrackinfo.period);
    }
    if ((((modtrackinfo.effect & 4))) !== 0) {
      if (((modtrackinfo.period = i32(modtrackinfo.period - modtrackinfo.port_up))) < modtrackinfo.period_low_limit) {
        if (this.mod.s3m) {
          modtrackinfo.period = modtrackinfo.period_high_limit;
        } else {
          modtrackinfo.period = modtrackinfo.period_low_limit;
        }
      }
      modtrackinfo.pitch = idiv(modtrackinfo.finetune_rate, modtrackinfo.period);
    }
    if ((((modtrackinfo.effect & 32))) !== 0) {
      if (modtrackinfo.portto < modtrackinfo.period) {
        if (((modtrackinfo.period = i32(modtrackinfo.period + modtrackinfo.port_inc))) > modtrackinfo.portto) {
          modtrackinfo.period = modtrackinfo.portto;
        }
      } else if ((modtrackinfo.portto > modtrackinfo.period) && (((modtrackinfo.period = i32(modtrackinfo.period - modtrackinfo.port_inc))) < modtrackinfo.portto)) {
        modtrackinfo.period = modtrackinfo.portto;
      }
      modtrackinfo.pitch = idiv(modtrackinfo.finetune_rate, modtrackinfo.period);
    }
    if ((((modtrackinfo.effect & 8))) !== 0) {
      modtrackinfo.vibpos = i32(modtrackinfo.vibpos + ((modtrackinfo.vib_rate << 2)));
      let i = ((Math.imul(ModSlayer.sintable[(((modtrackinfo.vibpos >> 2)) & 31)], modtrackinfo.vib_depth)) >> 7);
      if ((((modtrackinfo.vibpos & 128))) !== 0) {
        i = i32(-i);
      }
      i = i32(i + modtrackinfo.period);
      if (i < modtrackinfo.period_low_limit) {
        i = modtrackinfo.period_low_limit;
      }
      if (i > modtrackinfo.period_high_limit) {
        i = modtrackinfo.period_high_limit;
      }
      modtrackinfo.pitch = idiv(modtrackinfo.finetune_rate, i);
    }
    if ((((modtrackinfo.effect & 16))) !== 0) {
      modtrackinfo.pitch = idiv(modtrackinfo.finetune_rate, modtrackinfo.arp[modtrackinfo.arpindex]);
      modtrackinfo.arpindex = i32(modtrackinfo.arpindex + 1);
      if (modtrackinfo.arpindex >= 3) {
        modtrackinfo.arpindex = 0;
      }
    }
  }

  mixtrack_16_mono(modtrackinfo, ai, i, j) {
    let abyte0 = modtrackinfo.samples;
    let k = modtrackinfo.position;
    let j2 = ((Math.imul(this.vol_adj[modtrackinfo.volume], this.gain)) >> (i32(this.vol_shift + 8)));
    let i2 = modtrackinfo.error;
    let k2 = (modtrackinfo.pitch & 4095);
    let l1 = (modtrackinfo.pitch >> 12);
    if (modtrackinfo.replen < 3) {
      let m = modtrackinfo.length;
      if (k >= m) {
        return;
      }
      let j3 = i32(i + j);
      if (modtrackinfo.pitch < 4096) {
        while (k < m) {
          if (i >= j3) {
            break;
          }
          let n = i++;
          ai[n] = i32(ai[n] + (((Math.imul(((i32((Math.imul(abyte0[k], (i32(4096 - i2)))) + (Math.imul(abyte0[i32(k + 1)], i2))))), j2)) >> 12)));
          k = i32(k + (i32(l1 + (((((i2 = i32(i2 + k2))) >> 12))))));
          i2 = (i2 & 4095);
        }
      } else {
        while ((k < m) && (i < j3)) {
          let n2 = i++;
          ai[n2] = i32(ai[n2] + (Math.imul(abyte0[k], j2)));
          k = i32(k + (i32(l1 + (((((i2 = i32(i2 + k2))) >> 12))))));
          i2 = (i2 & 4095);
        }
      }
      modtrackinfo.error = i2;
      modtrackinfo.position = k;
    } else {
      let i3 = i32(modtrackinfo.replen + modtrackinfo.repeat);
      if (modtrackinfo.pitch < 4096) {
        while (j > 0) {
          if (k >= i3) {
            k = i32(k - modtrackinfo.replen);
          }
          let n3 = i++;
          ai[n3] = i32(ai[n3] + (((Math.imul(((i32((Math.imul(abyte0[k], (i32(4096 - i2)))) + (Math.imul(abyte0[i32(k + 1)], i2))))), j2)) >> 12)));
          k = i32(k + (i32(l1 + (((((i2 = i32(i2 + k2))) >> 12))))));
          i2 = (i2 & 4095);
          j = i32(j - 1);
        }
      } else {
        while (j > 0) {
          if (k >= i3) {
            k = i32(k - modtrackinfo.replen);
          }
          let n4 = i++;
          ai[n4] = i32(ai[n4] + (Math.imul(abyte0[k], j2)));
          k = i32(k + (i32(l1 + (((((i2 = i32(i2 + k2))) >> 12))))));
          i2 = (i2 & 4095);
          j = i32(j - 1);
        }
      }
      modtrackinfo.error = i2;
      modtrackinfo.position = k;
    }
  }

  make_vol_table8() {
    this.vol_table = new Int8Array(16640);
    let i = 0;
    do {
      this.vol_table[i] = (((((Math.imul(this.vol_adj[(i >> 8)], ((i) << 24 >> 24))) >> (i32(8 + this.vol_shift))))) << 24 >> 24);
    } while (++i < 16640);
  }

  turnbytesNorm() {
    this.bit16 = true;
    this.startplaying(this.loud);
    let ai = intArray(this.mixspeed);
    let ai2 = intArray(this.mixspeed);
    let abyte0 = new Int8Array(18000000);
    this.oln = 0;
    while (!this.mod_done) {
      if (--this.tempo_wait > 0) {
        for (let l = 0; l < this.numtracks; l = i32(l + 1)) {
          this.beattrack(this.tracks[l]);
        }
      } else {
        this.updatetracks();
      }
      System.arraycopy(ai2, 0, ai, 0, this.bpm_samples);
      for (let i = 0; i < this.numtracks; i = i32(i + 1)) {
        this.mixtrack_16_mono(this.tracks[i], ai, 0, this.bpm_samples);
      }
      let i2 = this.bpm_samples;
      if (this.oversample > 1) {
        let j1 = 0;
        i2 = idiv(this.bpm_samples, this.oversample);
        if (this.oversample === 2) {
          for (let k = 0; k < i2; k = i32(k + 1)) {
            ai[k] = ((i32(ai[j1] + ai[i32(j1 + 1)])) >> 1);
            j1 = i32(j1 + 2);
          }
        } else {
          for (let m = 0; m < i2; m = i32(m + 1)) {
            let k2 = ai[j1++];
            for (let l2 = 1; l2 < this.oversample; l2 = i32(l2 + 1)) {
              k2 = i32(k2 + ai[j1++]);
            }
            ai[m] = idiv(k2, this.oversample);
          }
        }
      }
      if ((i32(this.oln + i2)) < 18000000) {
        ModSlayer.intToBytes16(ai, abyte0, i2, this.oln);
        this.oln = i32(this.oln + i2);
      }
    }
    this.oln = i32(this.oln + 1);
    return abyte0;
  }

  updatetracks() {
    this.tempo_wait = this.tempo;
    if (this.row >= 64) {
      if (this.order_pos >= this.mod.song_length_patterns) {
        this.order_pos = 0;
        this.nloops = i32(this.nloops - 1);
        if (this.nloops === 0) {
          this.mod_done = true;
        }
      }
      this.row = this.break_row;
      this.break_row = 0;
      if (this.mod.positions[this.order_pos] === 255) {
        this.order_pos = 0;
        this.row = 0;
      }
      this.patt = this.mod.patterns[this.mod.positions[this.order_pos]];
      this.pattofs = Math.imul((Math.imul(this.row, 4)), this.numtracks);
      this.order_pos = i32(this.order_pos + 1);
    }
    this.row = i32(this.row + 1);
    for (let i = 0; i < this.numtracks; i = i32(i + 1)) {
      this.pattofs = this.get_track(this.tracks[i], this.patt, this.pattofs);
    }
  }

  get_track(modtrackinfo, abyte0, i) {
    let j = (abyte0[i] & 240);
    let k = ((((abyte0[i++] & 15))) << 8);
    k = (k | (((abyte0[i++] & 255))));
    let l = (abyte0[i] & 15);
    j = (j | (((((abyte0[i++] & 240))) >> 4)));
    let i2 = abyte0[i++];
    modtrackinfo.effect = 0;
    if (j !== 0) {
      j = i32(j - 1);
      let modinstrument = this.mod.insts[j];
      modtrackinfo.volume = modinstrument.volume;
      modtrackinfo.length = modinstrument.sample_length;
      modtrackinfo.repeat = modinstrument.repeat_point;
      modtrackinfo.replen = modinstrument.repeat_length;
      modtrackinfo.finetune_rate = modinstrument.finetune_rate;
      modtrackinfo.samples = modinstrument.samples;
      modtrackinfo.period_low_limit = modinstrument.period_low_limit;
      modtrackinfo.period_high_limit = modinstrument.period_high_limit;
    }
    if (k !== 0) {
      modtrackinfo.portto = k;
      if ((l !== 3) && (l !== 5)) {
        let n = k;
        modtrackinfo.period = n;
        modtrackinfo.start_period = n;
        modtrackinfo.pitch = idiv(modtrackinfo.finetune_rate, k);
        modtrackinfo.position = 0;
      }
    }
    Label_0901: {
      if ((l !== 0) || (i2 !== 0)) {
        switch ((l)) {
          case 0:
            {
              let j2 = 12;
              while ((modtrackinfo.period < ModSlayer.period_set[j2]) && (++j2 < 48)) {
              }
              modtrackinfo.arp[0] = ModSlayer.period_set[j2];
              modtrackinfo.arp[1] = ModSlayer.period_set[i32(j2 + (((i2 & 15))))];
              modtrackinfo.arp[2] = ModSlayer.period_set[i32(j2 + ((((((i2 & 240))) >> 4))))];
              modtrackinfo.arpindex = 0;
              modtrackinfo.effect = (modtrackinfo.effect | 16);
              break;
            }
          case 1:
            {
              modtrackinfo.effect = (modtrackinfo.effect | 4);
              if (i2 !== 0) {
                modtrackinfo.port_up = i2;
                break;
              }
              break;
            }
          case 2:
            {
              modtrackinfo.effect = (modtrackinfo.effect | 2);
              if (i2 !== 0) {
                modtrackinfo.port_down = i2;
                break;
              }
              break;
            }
          case 3:
            {
              if (i2 !== 0) {
                modtrackinfo.port_inc = ((i2 & 255));
              }
              modtrackinfo.effect = (modtrackinfo.effect | 32);
              break;
            }
          case 4:
            {
              if ((((i2 & 15))) !== 0) {
                modtrackinfo.vib_depth = ((i2 & 15));
              }
              if ((((i2 & 240))) !== 0) {
                modtrackinfo.vib_rate = ((((i2 & 240))) >> 4);
              }
              if (k !== 0) {
                modtrackinfo.vibpos = 0;
              }
              modtrackinfo.effect = (modtrackinfo.effect | 8);
              break;
            }
          case 9:
            {
              if (i2 === 0) {
                i2 = modtrackinfo.oldsampofs;
              }
              modtrackinfo.oldsampofs = i2;
              modtrackinfo.position = ((((i2 & 255))) << 8);
              break;
            }
          case 5:
            {
              modtrackinfo.effect = (modtrackinfo.effect | 32);
            }
          case 6:
            {
              if (l === 6) {
                modtrackinfo.effect = (modtrackinfo.effect | 8);
              }
            }
          case 10:
            {
              modtrackinfo.vol_slide = i32(((((((i2 & 240))) >> 4))) - (((i2 & 15))));
              modtrackinfo.effect = (modtrackinfo.effect | 1);
              break;
            }
          case 12:
            {
              if ((i2 > 64) || (i2 < 0)) {
                modtrackinfo.volume = 64;
                break;
              }
              modtrackinfo.volume = i2;
              break;
            }
          case 13:
            {
              this.break_row = i32((Math.imul(((((((i2 & 240))) >> 4))), 10)) + (((i2 & 15))));
              this.row = 64;
              break;
            }
          case 14:
            {
              let k2 = (i2 & 240);
              i2 = (i2 & 15);
              switch ((k2)) {
                default:
                  {
                    break Label_0901;
                  }
                case 1:
                  {
                    modtrackinfo.period = i32(modtrackinfo.period + i2);
                    if (modtrackinfo.period > modtrackinfo.period_high_limit) {
                      modtrackinfo.period = modtrackinfo.period_high_limit;
                    }
                    modtrackinfo.pitch = idiv(modtrackinfo.finetune_rate, modtrackinfo.period);
                    break Label_0901;
                  }
                case 2:
                  {
                    modtrackinfo.period = i32(modtrackinfo.period - i2);
                    if (modtrackinfo.period < modtrackinfo.period_low_limit) {
                      modtrackinfo.period = modtrackinfo.period_low_limit;
                    }
                    modtrackinfo.pitch = idiv(modtrackinfo.finetune_rate, modtrackinfo.period);
                    break Label_0901;
                  }
              }
            }
          case 15:
            {
              if (i2 === 0) {
                break;
              }
              i2 = (i2 & 255);
              if (i2 <= 32) {
                this.tempo = i2;
                this.tempo_wait = i2;
                break;
              }
              this.bpm = i2;
              this.bpm_samples = Math.imul((idiv(this.samplingrate, (((Math.imul(103, i2)) >> 8)))), this.oversample);
              break;
            }
        }
      }
    }
    return i;
  }

  startplaying(flag) {
    this.vol_adj = ((flag ? ModSlayer.loud_vol_adj : ModSlayer.normal_vol_adj));
    this.mixspeed = Math.imul(this.samplingrate, this.oversample);
    this.order_pos = 0;
    let def_tempo = this.def_tempo;
    this.tempo = def_tempo;
    this.tempo_wait = def_tempo;
    this.bpm = this.def_bpm;
    this.row = 64;
    this.break_row = 0;
    this.bpm_samples = Math.imul((idiv(this.samplingrate, (idiv((Math.imul(24, this.bpm)), 60)))), this.oversample);
    this.numtracks = this.mod.numtracks;
    this.tracks = objArray(this.numtracks);
    for (let i = 0; i < this.tracks.length; i = i32(i + 1)) {
      this.tracks[i] = new ModTrackInfo();
    }
    if (this.mod.s3m) {
      for (let j = 0; j < this.mod.insts.length; j = i32(j + 1)) {
        let modinstrument = this.mod.insts[j];
        modinstrument.finetune_rate = idiv(i32(((428 * modinstrument.finetune_value) << 8)), this.mixspeed);
        modinstrument.period_low_limit = 14;
        modinstrument.period_high_limit = 1712;
      }
    } else {
      for (let k = 0; k < this.mod.insts.length; k = i32(k + 1)) {
        let modinstrument2 = this.mod.insts[k];
        modinstrument2.finetune_rate = i32((22748294283264 / ((Math.imul(this.mixspeed, (i32(1536 - modinstrument2.finetune_value)))))));
        modinstrument2.period_low_limit = 113;
        modinstrument2.period_high_limit = 856;
      }
    }
    if (this.numtracks > 8) {
      this.vol_shift = 2;
    } else if (this.numtracks > 4) {
      this.vol_shift = 1;
    } else {
      this.vol_shift = 0;
    }
    if (!this.bit16) {
      this.make_vol_table8();
    }
  }

  static intToBytes16(ai, abyte0, i, j) {
    let k = j;
    for (let l = 0; l < i; l = i32(l + 1)) {
      if (ai[l] < -32767) {
        ai[l] = -32767;
      }
      if (ai[l] > 32767) {
        ai[l] = 32767;
      }
      abyte0[k++] = ((((ai[l] >> 8))) << 24 >> 24);
      abyte0[k] = ((((ai[l] & 255))) << 24 >> 24);
    }
  }

  turnbytesUlaw() {
    this.bit16 = true;
    this.startplaying(this.loud);
    let ai = intArray(this.mixspeed);
    let ai2 = intArray(this.mixspeed);
    let ai3 = intArray(3200000);
    this.oln = 0;
    while (!this.mod_done) {
      if (--this.tempo_wait > 0) {
        for (let k1 = 0; k1 < this.numtracks; k1 = i32(k1 + 1)) {
          this.beattrack(this.tracks[k1]);
        }
      } else {
        this.updatetracks();
      }
      System.arraycopy(ai2, 0, ai, 0, this.bpm_samples);
      for (let i = 0; i < this.numtracks; i = i32(i + 1)) {
        this.mixtrack_16_mono(this.tracks[i], ai, 0, this.bpm_samples);
      }
      let l1 = this.bpm_samples;
      if (this.oversample > 1) {
        let i2 = 0;
        l1 = idiv(this.bpm_samples, this.oversample);
        if (this.oversample === 2) {
          for (let j = 0; j < l1; j = i32(j + 1)) {
            ai[j] = ((i32(ai[i2] + ai[i32(i2 + 1)])) >> 1);
            i2 = i32(i2 + 2);
          }
        } else {
          for (let m = 0; m < l1; m = i32(m + 1)) {
            let k2 = ai[i2++];
            for (let l2 = 1; l2 < this.oversample; l2 = i32(l2 + 1)) {
              k2 = i32(k2 + ai[i2++]);
            }
            ai[m] = idiv(k2, this.oversample);
          }
        }
      }
      for (let l3 = 0; l3 < l1; l3 = i32(l3 + 1)) {
        if (this.oln < 3200000) {
          ai3[this.oln] = ai[l3];
          this.oln = i32(this.oln + 1);
        }
      }
    }
    for (let i3 = 2; i3 < this.oln; i3 = i32(i3 + 1)) {
      ai3[i3] = idiv(((i32(ai3[i3] + ai3[i32(i3 - 2)]))), 2);
    }
    for (let j2 = 57; j2 < this.oln; j2 = i32(j2 + 1)) {
      ai3[j2] = idiv(((i32((i32(ai3[j2] + ai3[j2])) + ai3[i32(j2 - 50)]))), 3);
    }
    let abyte0 = new Int8Array(this.oln);
    for (let j3 = 0; j3 < this.oln; j3 = i32(j3 + 1)) {
      abyte0[j3] = UlawUtils.linear2ulawclip(ai3[j3]);
    }
    return abyte0;
  }
}
ModSlayer.VERSION = '1.0';
ModSlayer.COPYRIGHT = '';
ModSlayer.EFF_VOL_SLIDE = 1;
ModSlayer.EFF_PORT_DOWN = 2;
ModSlayer.EFF_PORT_UP = 4;
ModSlayer.EFF_VIBRATO = 8;
ModSlayer.EFF_ARPEGGIO = 16;
ModSlayer.EFF_PORT_TO = 32;
ModSlayer.EFF_TREMOLO = 64;
ModSlayer.EFF_RETRIG = 128;
ModSlayer.MIX_BUF_SIZE = 2048;
ModSlayer.DEF_TEMPO_NTSC = 6;
ModSlayer.DEF_TEMPO_PAL = 6;
ModSlayer.DEF_BPM_NTSC = 125;
ModSlayer.DEF_BPM_PAL = 145;
ModSlayer.MIDCRATE = 8448;
ModSlayer.MAX_SAMPLES = 100;
ModSlayer.MAX_TRACKS = 32;
ModSlayer.S3M_MAGIC1 = 4122;
ModSlayer.S3M_MAGIC2 = 0;
ModSlayer.S3M_INSTR2 = 0;
ModSlayer.normal_vol_adj = null;
ModSlayer.loud_vol_adj = null;
ModSlayer.sintable = null;
ModSlayer.period_set = null;
ModSlayer.period_set_step = null;
ModSlayer.sunfmt = null;
ModSlayer.ERROR_SHIFT = 12;
ModSlayer.ERROR_MASK = 4095;
ModSlayer.ratediv = 22748294283264;
