// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/ModTrackInfo.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { intArray } from '../java.js';

export class ModTrackInfo {
  constructor() {
    this.samples = null;
    this.position = 0;
    this.length = 0;
    this.repeat = 0;
    this.replen = 0;
    this.volume = 0;
    this.error = 0;
    this.pitch = 0;
    this.old_position = 0;
    this.start_period = 0;
    this.period = 0;
    this.step = 0;
    this.effect = 0;
    this.portto = 0;
    this.vibpos = 0;
    this.trempos = 0;
    this.oldsampofs = 0;
    this.arp = null;
    this.arpindex = 0;
    this.oldperiod = 0;
    this.vol_slide = 0;
    this.port_inc = 0;
    this.port_up = 0;
    this.port_down = 0;
    this.vib_rate = 0;
    this.vib_depth = 0;
    this.trem_rate = 0;
    this.trem_depth = 0;
    this.retrig = 0;
    this.finetune_rate = 0;
    this.period_low_limit = 0;
    this.period_high_limit = 0;
    this.oldperiod = 1;
    this.arp = intArray(3);
  }
}
