// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/RadicalMidi.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { fr, i32, trunc } from '../java.js';
import { File, FileInputStream, System, jstr } from './jawt.js';

export class RadicalMidi {
  constructor(fn) {
    this.is = null;
    this.sequencer = null;
    this.paused = false;
    this.loaded = false;
    this.playing = false;
    this.playingogg = false;
    this.nooggloop = false;
    this.pausedogg = false;
    this.isMp3 = false;
    this.isOgg = false;
    this.s = null;
    this.fi = null;
    this.fl = null;
    this.ogg = null;
    this.player = null;
    this.filePath = null;
    this.loaded = false;
    this.playing = false;
    this.playingogg = false;
    this.pausedogg = false;
    this.nooggloop = false;
    this.isMp3 = false;
    this.isOgg = false;
    if (fn.endsWith('.mp3')) {
      this.s = fn;
      this.isMp3 = true;
      this.isOgg = false;
      this.fl = new File(fn);
      try {
        this.fi = new FileInputStream(this.fl);
        this.player = new PausablePlayer(this.fi);
      } catch (ex) {
        System.out.println('Error loading Mp3!');
        ex.printStackTrace();
      }
    } else if (fn.endsWith('.ogg')) {
      this.s = fn;
      this.isMp3 = false;
      this.isOgg = true;
      this.fl = new File(fn);
      try {
        this.fi = new FileInputStream(this.fl);
        this.ogg = new OggClip(this.fi);
      } catch (e) {
        System.out.println('Error loading Ogg!');
        e.printStackTrace();
      }
    } else {
      this.isMp3 = false;
      this.isOgg = false;
      this.s = fn;
      try {
        this.fi = new FileInputStream(new File(fn));
      } catch (ex2) {
        System.out.println(('Midi file "' + fn) + '" not found!');
        ex2.printStackTrace();
      }
      try {
        (this.sequencer = MidiSystem.getSequencer()).open();
      } catch (ex) {
        System.out.println(('Error loading Midi file "' + fn) + '":');
        ex.printStackTrace();
      }
    }
  }

  load() {
    if (!this.isOgg && !this.isMp3) {
      this.loadMidi();
    }
  }

  play() {
    if (this.isMp3) {
      this.playMp3();
    } else if (this.isOgg) {
      this.ogg.loop();
      this.playingogg = true;
      this.nooggloop = false;
    } else {
      this.playMidi$2();
    }
  }

  play$1(once) {
    if (this.isMp3) {
      this.playMp3();
    } else if (this.isOgg) {
      if (once) {
        this.ogg.play();
        this.nooggloop = true;
      } else {
        this.ogg.loop();
        this.nooggloop = false;
      }
      this.playingogg = true;
    } else {
      this.playMidi$2();
    }
  }

  resume() {
    if (this.isMp3) {
      this.player.resume();
    } else if (this.isOgg) {
      this.ogg.resume();
      this.pausedogg = false;
      this.playingogg = true;
    } else {
      this.resumeMidi$2();
    }
  }

  setPaused(paused) {
    if (this.isOgg || this.isMp3) {
      if (paused) {
        if (this.isMp3) {
          this.player.pause();
        } else if (this.isOgg) {
          this.playingogg = false;
          this.pausedogg = true;
          this.ogg.pause();
        }
      } else if (this.isMp3) {
        this.player.resume();
      } else if (this.isOgg) {
        this.ogg.resume();
        this.playingogg = true;
        this.pausedogg = false;
      }
    } else if (((this.paused !== paused) && (this.sequencer !== null)) && this.sequencer.isOpen()) {
      this.paused = paused;
      if (paused) {
        this.sequencer.stop();
      } else {
        this.sequencer.start();
      }
    }
  }

  stop() {
    if (this.isMp3) {
      this.player.pause();
    } else if (this.isOgg) {
      this.ogg.pause();
    } else {
      this.stopMidi();
    }
  }

  unload() {
    if (this.isMp3) {
      this.player.close();
    } else if (this.isOgg) {
      this.unloadOgg();
    } else {
      this.unloadMidi();
    }
  }

  loadMidi() {
    try {
      this.is = new BufferedInputStream(this.fi);
      this.loaded = true;
    } catch (ex) {
      System.out.println('Error buffering Midi file:');
      ex.printStackTrace();
    }
  }

  resumeMidi(gain, loops) {
    try {
      this.fi = new FileInputStream(new File(this.s));
      this.is = new BufferedInputStream(this.fi);
    } catch (ex) {
      System.out.println('Midi file not found!');
      ex.printStackTrace();
    }
    this.playMidi(gain, loops);
  }

  resumeMidi$1(gain) {
    try {
      this.fi = new FileInputStream(new File(this.s));
      this.is = new BufferedInputStream(this.fi);
    } catch (ex) {
      System.out.println('Midi file not found!');
      ex.printStackTrace();
    }
    this.playMidi$1(gain);
  }

  resumeMidi$2() {
    try {
      this.fi = new FileInputStream(new File(this.s));
      this.is = new BufferedInputStream(this.fi);
    } catch (ex) {
      System.out.println('Midi file not found!');
      ex.printStackTrace();
    }
    this.playMidi$2();
  }

  playMidi(gain, loops) {
    try {
      this.sequencer.setSequence(this.is);
      this.sequencer.setLoopCount(loops);
      if (this.sequencer instanceof Synthesizer) {
        let synthesizer = this.sequencer;
        let channels = synthesizer.getChannels();
        for (let i = 0; i < channels.length; i = i32(i + 1)) {
          channels[i].controlChange(7, trunc((fr(gain) * 1.27)));
        }
      }
      this.sequencer.start();
      this.playing = true;
    } catch (ex) {
      System.out.println('There is a mistake in your Midi code,');
      System.out.println('please re-check!');
      ex.printStackTrace();
    }
  }

  playMidi$1(gain) {
    try {
      this.sequencer.setSequence(this.is);
      this.sequencer.setLoopCount(9999);
      if (this.sequencer instanceof Synthesizer) {
        let synthesizer = this.sequencer;
        let channels = synthesizer.getChannels();
        for (let i = 0; i < channels.length; i = i32(i + 1)) {
          channels[i].controlChange(7, trunc((fr(gain) * 1.27)));
        }
      }
      this.sequencer.start();
      this.playing = true;
    } catch (ex) {
      System.out.println('There is a mistake in your Midi code,');
      System.out.println('please re-check!');
      ex.printStackTrace();
    }
  }

  playMidi$2() {
    try {
      this.sequencer.setSequence(this.is);
      this.sequencer.setLoopCount(9999);
      this.sequencer.start();
      this.playing = true;
    } catch (ex) {
      System.out.println('There is a mistake in your Midi code,');
      System.out.println('please re-check!');
      ex.printStackTrace();
    }
  }

  isPaused() {
    return this.paused;
  }

  stopMidi() {
    System.out.println('Stopping Midi file...');
    try {
      this.sequencer.stop();
      this.playing = false;
    } catch (ex) {
      System.out.println('Error stopping Midi file:');
      ex.printStackTrace();
    }
  }

  unloadMidi() {
    try {
      this.is.close();
      this.loaded = false;
    } catch (ex) {
      System.out.println('Error unloading Midi file:');
      ex.printStackTrace();
    }
  }

  playMp3() {
    try {
      this.player.play();
    } catch (e) {
      e.printStackTrace();
    }
  }

  unloadOgg() {
    this.ogg.stop();
    this.ogg.close();
  }
}
