// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/RadicalMod.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { fr, i32, trunc } from '../java.js';
import { ByteArrayInputStream, System, URL, ZipInputStream, jstr } from './jawt.js';
import { Mod } from './Mod.js';
import { ModSlayer } from './ModSlayer.js';
import { SuperClip } from './SuperClip.js';
import { SuperStream } from './SuperStream.js';

export class RadicalMod {
  constructor(s, applet) {
    this.modf = null;
    this.stream = null;
    this.sClip = null;
    this.suny = false;
    this.playing = false;
    this.loaded = 0;
    this.suny = false;
    this.playing = false;
    this.loaded = 0;
    this.loaded = 1;
    // ext-patch radmod-lazy: web/ext/radmusic.js reads the .radq when loadMod asks
    this.path = s;
  }

  stop() {
    if (this.playing && (this.loaded === 2)) {
      if (this.suny) {
        this.sClip.stop();
      } else {
        try {
          AudioPlayer.player.stop(this.stream);
        } catch (ex) {
        }
      }
      this.playing = false;
    }
  }

  resume() {
    if (!this.playing && (this.loaded === 2)) {
      if (this.suny) {
        this.sClip.resume();
        if (this.sClip.stoped === 0) {
          this.playing = true;
        }
      } else {
        try {
          AudioPlayer.player.start(this.stream);
        } catch (ex) {
        }
        this.playing = true;
      }
    }
  }

  unloadAll() {
    if (this.playing && (this.loaded === 2)) {
      if (this.suny) {
        this.sClip.stop();
      } else {
        try {
          AudioPlayer.player.stop(this.stream);
        } catch (ex) {
        }
      }
    }
    try {
      if (this.suny) {
        this.sClip.close();
        this.sClip = null;
      } else {
        this.stream.close();
        this.stream = null;
      }
    } catch (ex2) {
    }
    try {
      this.modf = null;
    } catch (ex3) {
    }
    void 0;
  }

  play() {
    if (!this.playing && (this.loaded === 2)) {
      if (this.suny) {
        this.sClip.play();
        if (this.sClip.stoped === 0) {
          this.playing = true;
        }
      } else {
        if (this.stream !== null) {
          this.stream.reset();
        }
        try {
          AudioPlayer.player.start(this.stream);
        } catch (ex) {
        }
        this.playing = true;
      }
    }
  }

  unloadMod() {
    if (this.loaded === 2) {
      if (this.playing) {
        if (this.suny) {
          this.sClip.stop();
        } else {
          try {
            AudioPlayer.player.stop(this.stream);
          } catch (ex) {
          }
        }
        this.playing = false;
      }
      try {
        if (this.suny) {
          this.sClip.close();
          this.sClip = null;
        } else {
          this.stream.close();
          this.stream = null;
        }
      } catch (ex2) {
      }
      void 0;
      this.loaded = 1;
    }
  }

  loadMod(i, j, k, flag, flag1) {
    if (this.loaded === 1) {
      this.loaded = 2;
      this.suny = flag;
      let l = 22000;
      if (flag1) {
        this.suny = false;
      }
      if (this.suny) {
        j = trunc((fr((fr((fr(fr(j) / 8000.0)) * 2.0)) * fr(l))));
      }
      if (!this.suny) {
        if (!flag1) {
          i = trunc(i * 1.5);
        } else {
          i = trunc(i * 2.2);
        }
      }
      let mod = new Mod(new ByteArrayInputStream(this.modf));
      let modslayer = new ModSlayer(mod, j, i, k);
      try {
        if (this.suny) {
          let abyte0 = modslayer.turnbytesNorm();
          this.sClip = new SuperClip(abyte0, modslayer.oln, l);
        } else {
          let abyte2 = modslayer.turnbytesUlaw();
          this.stream = new SuperStream(abyte2);
        }
        let obj1 = null;
        let obj2 = null;
        modslayer = null;
      } catch (exception) {
        System.out.println('Error making a Mod: ' + exception);
        this.loaded = 0;
      }
      System.runFinalization();
      void 0;
    }
  }
}
