// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/Record.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { floatArray, fr, i32, idiv, intArray, objArray, trunc } from '../java.js';
import { Color } from './jawt.js';
import { ContO } from './ContO.js';

export class Record {
  constructor(medium, ncars) {
    this.m = null;
    this.caught = 0;
    this.hcaught = false;
    this.prepit = false;
    this.ocar = null;
    this.cntf = 0;
    this.car = null;
    this.squash = null;
    this.fix = null;
    this.dest = null;
    this.x = null;
    this.y = null;
    this.z = null;
    this.xy = null;
    this.zy = null;
    this.xz = null;
    this.wxz = null;
    this.wzy = null;
    this.ns = null;
    this.sspark = null;
    this.sx = null;
    this.sy = null;
    this.sz = null;
    this.smag = null;
    this.scx = null;
    this.scz = null;
    this.fulls = null;
    this.nry = null;
    this.ry = null;
    this.magy = null;
    this.mtouch = null;
    this.nrx = null;
    this.rx = null;
    this.magx = null;
    this.nrz = null;
    this.rz = null;
    this.magz = null;
    this.checkpoint = null;
    this.lastcheck = null;
    this.wasted = 0;
    this.whenwasted = 0;
    this.powered = 0;
    this.closefinish = 0;
    this.starcar = null;
    this.hsquash = null;
    this.hfix = null;
    this.hdest = null;
    this.hx = null;
    this.hy = null;
    this.hz = null;
    this.hxy = null;
    this.hzy = null;
    this.hxz = null;
    this.hwxz = null;
    this.hwzy = null;
    this.hns = null;
    this.hsspark = null;
    this.hsx = null;
    this.hsy = null;
    this.hsz = null;
    this.hsmag = null;
    this.hscx = null;
    this.hscz = null;
    this.hfulls = null;
    this.hnry = null;
    this.hry = null;
    this.hmagy = null;
    this.hnrx = null;
    this.hrx = null;
    this.hmagx = null;
    this.hnrz = null;
    this.hrz = null;
    this.hmagz = null;
    this.hmtouch = null;
    this.hcheckpoint = null;
    this.hlastcheck = null;
    this.cntdest = null;
    this.lastfr = 0;
    this.hfix = Int32Array.from([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]);
    this.hdest = Int32Array.from([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]);
    this.caught = 0;
    this.hcaught = false;
    this.prepit = true;
    this.ocar = objArray(101);
    this.cntf = 50;
    this.car = objArray(6).map(() => objArray(101));
    this.squash = objArray(6).map(() => intArray(101));
    this.fix = intArray(101);
    this.dest = intArray(101);
    this.x = objArray(300).map(() => intArray(101));
    this.y = objArray(300).map(() => intArray(101));
    this.z = objArray(300).map(() => intArray(101));
    this.xy = objArray(300).map(() => intArray(101));
    this.zy = objArray(300).map(() => intArray(101));
    this.xz = objArray(300).map(() => intArray(101));
    this.wxz = objArray(300).map(() => intArray(101));
    this.wzy = objArray(300).map(() => intArray(101));
    this.ns = objArray(101).map(() => intArray(4));
    this.sspark = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.sx = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.sy = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.sz = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.smag = objArray(101).map(() => objArray(4).map(() => floatArray(30)));
    this.scx = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.scz = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.fulls = objArray(101).map(() => objArray(4).map(() => new Array(30).fill(false)));
    this.nry = objArray(101).map(() => intArray(4));
    this.ry = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.magy = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.mtouch = objArray(101).map(() => new Array(7).fill(false));
    this.nrx = objArray(101).map(() => intArray(4));
    this.rx = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.magx = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.nrz = objArray(101).map(() => intArray(4));
    this.rz = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.magz = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.checkpoint = intArray(300);
    this.lastcheck = new Array(300).fill(false);
    this.wasted = 0;
    this.whenwasted = 0;
    this.powered = 0;
    this.closefinish = 0;
    this.starcar = objArray(101);
    this.hsquash = intArray(101);
    this.hx = objArray(300).map(() => intArray(101));
    this.hy = objArray(300).map(() => intArray(101));
    this.hz = objArray(300).map(() => intArray(101));
    this.hxy = objArray(300).map(() => intArray(101));
    this.hzy = objArray(300).map(() => intArray(101));
    this.hxz = objArray(300).map(() => intArray(101));
    this.hwxz = objArray(300).map(() => intArray(101));
    this.hwzy = objArray(300).map(() => intArray(101));
    this.hns = objArray(101).map(() => intArray(4));
    this.hsspark = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.hsx = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.hsy = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.hsz = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.hsmag = objArray(101).map(() => objArray(4).map(() => floatArray(30)));
    this.hscx = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.hscz = objArray(101).map(() => objArray(4).map(() => intArray(30)));
    this.hfulls = objArray(101).map(() => objArray(4).map(() => new Array(30).fill(false)));
    this.hnry = objArray(101).map(() => intArray(4));
    this.hry = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.hmagy = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.hnrx = objArray(101).map(() => intArray(4));
    this.hrx = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.hmagx = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.hnrz = objArray(101).map(() => intArray(4));
    this.hrz = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.hmagz = objArray(101).map(() => objArray(4).map(() => intArray(7)));
    this.hmtouch = objArray(101).map(() => new Array(7).fill(false));
    this.hcheckpoint = intArray(300);
    this.hlastcheck = new Array(300).fill(false);
    this.cntdest = intArray(101);
    this.lastfr = 0;
    this.m = medium;
    this.cotchinow(this.caught = 0, ncars);
  }

  regy(i, f, flag, conto, madness) {
    if (f > 100.0) {
      f = fr(f - 100.0);
      let byte0 = 0;
      let byte2 = 0;
      let j = conto.zy;
      let k = conto.xy;
      while (j < 360) {
        j = i32(j + 360);
      }
      while (j > 360) {
        j = i32(j - 360);
      }
      if ((j < 210) && (j > 150)) {
        byte0 = -1;
      }
      if ((j > 330) || (j < 30)) {
        byte0 = 1;
      }
      while (k < 360) {
        k = i32(k + 360);
      }
      while (k > 360) {
        k = i32(k - 360);
      }
      if ((k < 210) && (k > 150)) {
        byte2 = -1;
      }
      if ((k > 330) || (k < 30)) {
        byte2 = 1;
      }
      if (((Math.imul(byte2, byte0)) === 0) || flag) {
        for (let l = 0; l < conto.npl; l = i32(l + 1)) {
          let f2 = 0.0;
          for (let k2 = 0; k2 < conto.p[l].n; k2 = i32(k2 + 1)) {
            if ((conto.p[l].wz === 0) && (this.py(conto.keyx[i], conto.p[l].ox[k2], conto.keyz[i], conto.p[l].oz[k2]) < madness.clrad[madness.cn])) {
              f2 = fr((fr(f / 20.0)) * this.m.random());
              let oz = conto.p[l].oz;
              let n = k2;
              oz[n] = trunc(fr(fr(oz[n]) + ((fr(f2 * this.m.sin(j))))));
              let ox = conto.p[l].ox;
              let n2 = k2;
              ox[n2] = trunc(fr(fr(ox[n2]) - ((fr(f2 * this.m.sin(k))))));
            }
          }
          if (f2 !== 0.0) {
            if (Math.abs(f2) >= 1.0) {
              conto.p[l].chip = 1;
              conto.p[l].ctmag = f2;
            }
            if (!conto.p[l].nocol && (conto.p[l].glass !== 1)) {
              if ((conto.p[l].bfase > 20) && (conto.p[l].hsb[1] > 0.2)) {
                conto.p[l].hsb[1] = 0.20000000298023224;
              }
              if (conto.p[l].bfase > 30) {
                if (conto.p[l].hsb[2] < 0.5) {
                  conto.p[l].hsb[2] = 0.5;
                }
                if (conto.p[l].hsb[1] > 0.1) {
                  conto.p[l].hsb[1] = 0.10000000149011612;
                }
              }
              if (conto.p[l].bfase > 40) {
                conto.p[l].hsb[1] = 0.05000000074505806;
              }
              if (conto.p[l].bfase > 50) {
                if (conto.p[l].hsb[2] > 0.8) {
                  conto.p[l].hsb[2] = 0.800000011920929;
                }
                conto.p[l].hsb[0] = 0.07500000298023224;
                conto.p[l].hsb[1] = 0.05000000074505806;
              }
              if (conto.p[l].bfase > 60) {
                conto.p[l].hsb[0] = 0.05000000074505806;
              }
              let plane = conto.p[l];
              plane.bfase = trunc(fr(fr(plane.bfase) + f2));
              new Color(conto.p[l].c[0], conto.p[l].c[1], conto.p[l].c[2]);
              let color = Color.getHSBColor(conto.p[l].hsb[0], conto.p[l].hsb[1], conto.p[l].hsb[2]);
              conto.p[l].c[0] = color.getRed();
              conto.p[l].c[1] = color.getGreen();
              conto.p[l].c[2] = color.getBlue();
            }
            if (conto.p[l].glass === 1) {
              let plane2 = conto.p[l];
              plane2.gr = trunc(plane2.gr + Math.abs(f2 * 1.5));
            }
          }
        }
      }
      if ((Math.imul(byte2, byte0)) === -1) {
        let i2 = 0;
        let j2 = 1;
        for (let l2 = 0; l2 < conto.npl; l2 = i32(l2 + 1)) {
          let f3 = 0.0;
          for (let i3 = 0; i3 < conto.p[l2].n; i3 = i32(i3 + 1)) {
            if (conto.p[l2].wz === 0) {
              f3 = fr((fr(f / 15.0)) * this.m.random());
              if (((((Math.abs(i32((i32(conto.p[l2].oy[i3] - madness.flipy[madness.cn])) - this.squash[0][madness.im])) | 0) < (Math.imul(madness.msquash[madness.cn], 3))) || (conto.p[l2].oy[i3] < (i32(madness.flipy[madness.cn] + this.squash[0][madness.im]))))) && (this.squash[0][madness.im] < madness.msquash[madness.cn])) {
                let oy = conto.p[l2].oy;
                let n3 = i3;
                oy[n3] = trunc(fr(fr(oy[n3]) + f3));
                i2 = trunc(fr(fr(i2) + f3));
                j2 = i32(j2 + 1);
              }
            }
          }
          if (conto.p[l2].glass === 1) {
            let plane3 = conto.p[l2];
            plane3.gr = i32(plane3.gr + 5);
          } else if (f3 !== 0.0) {
            let plane4 = conto.p[l2];
            plane4.bfase = trunc(fr(fr(plane4.bfase) + f3));
          }
          if (Math.abs(f3) >= 1.0) {
            conto.p[l2].chip = 1;
            conto.p[l2].ctmag = f3;
          }
        }
        let array = this.squash[0];
        let im = madness.im;
        array[im] = i32(array[im] + (idiv(i2, j2)));
      }
    }
  }

  reset(aconto, ncars) {
    this.caught = 0;
    this.hcaught = false;
    this.wasted = 0;
    this.whenwasted = 0;
    this.closefinish = 0;
    this.powered = 0;
    let i = 0;
    do {
      if (this.prepit) {
        this.starcar[i] = new ContO(1, aconto[i], 0, 0, 0, 0);
      }
      this.fix[i] = -1;
      this.dest[i] = -1;
      this.cntdest[i] = 0;
    } while (++i < ncars);
    i = 0;
    do {
      let j = 0;
      do {
        this.car[i][j] = new ContO(1, aconto[j], 0, 0, 0, 0);
        this.squash[i][j] = 0;
      } while (++j < ncars);
    } while (++i < 6);
    i = 0;
    do {
      let k = 0;
      do {
        let l = 0;
        do {
          this.sspark[i][k][l] = -1;
          this.ns[i][k] = 0;
        } while (++l < 30);
        l = 0;
        do {
          this.ry[i][k][l] = -1;
          this.nry[i][k] = 0;
          this.rx[i][k][l] = -1;
          this.nrx[i][k] = 0;
          this.rz[i][k][l] = -1;
          this.nrz[i][k] = 0;
        } while (++l < 7);
      } while (++k < 4);
    } while (++i < ncars);
    this.prepit = false;
  }

  playh(conto, madness, i, j) {
    conto.x = this.hx[j][i];
    conto.y = this.hy[j][i];
    conto.z = this.hz[j][i];
    conto.zy = this.hzy[j][i];
    conto.xy = this.hxy[j][i];
    conto.xz = this.hxz[j][i];
    conto.wxz = this.hwxz[j][i];
    conto.wzy = this.hwzy[j][i];
    if (i === 0) {
      conto.m.checkpoint = this.hcheckpoint[j];
      conto.m.lastcheck = this.hlastcheck[j];
    }
    if (j === 0) {
      this.cntdest[i] = 0;
    }
    if (this.hdest[i] === j) {
      this.cntdest[i] = 7;
    }
    if ((j === 0) && (this.hdest[i] < -1)) {
      for (let k = 0; k < conto.npl; k = i32(k + 1)) {
        if (((conto.p[k].wz === 0) || (conto.p[k].gr === -17)) || (conto.p[k].gr === -16)) {
          conto.p[k].embos = 13;
        }
      }
    }
    if (this.cntdest[i] !== 0) {
      for (let l = 0; l < conto.npl; l = i32(l + 1)) {
        if (((conto.p[l].wz === 0) || (conto.p[l].gr === -17)) || (conto.p[l].gr === -16)) {
          conto.p[l].embos = 1;
        }
      }
      let cntdest = this.cntdest;
      --cntdest[i];
    }
    let i2 = 0;
    do {
      let j2 = 0;
      do {
        if (this.hsspark[i][i2][j2] === j) {
          conto.stg[i2] = 1;
          conto.dov[i2] = -1;
          conto.sx[i2] = this.hsx[i][i2][j2];
          conto.sy[i2] = this.hsy[i][i2][j2];
          conto.sz[i2] = this.hsz[i][i2][j2];
          conto.smag[i2] = this.hsmag[i][i2][j2];
          conto.scx[i2] = this.hscx[i][i2][j2];
          conto.scz[i2] = this.hscz[i][i2][j2];
          conto.fulls[i2] = this.hfulls[i][i2][j2];
        }
      } while (++j2 < 30);
      j2 = 0;
      do {
        if ((this.hry[i][i2][j2] === j) && (this.lastfr !== j)) {
          this.regy(i2, fr(this.hmagy[i][i2][j2]), this.hmtouch[i][j2], conto, madness);
        }
        if (this.hrx[i][i2][j2] === j) {
          if (this.lastfr !== j) {
            this.regx(i2, fr(this.hmagx[i][i2][j2]), conto, madness);
          } else {
            this.chipx(i2, fr(this.hmagx[i][i2][j2]), conto, madness);
          }
        }
        if (this.hrz[i][i2][j2] === j) {
          if (this.lastfr !== j) {
            this.regz(i2, fr(this.hmagz[i][i2][j2]), conto, madness);
          } else {
            this.chipz(i2, fr(this.hmagz[i][i2][j2]), conto, madness);
          }
        }
      } while (++j2 < 7);
    } while (++i2 < 4);
    this.lastfr = j;
  }

  chipz(i, f, conto, madness) {
    if (Math.abs(f) > 100.0) {
      if (f > 100.0) {
        f = fr(f - 100.0);
      }
      if (f < -100.0) {
        f = fr(f + 100.0);
      }
      for (let j = 0; j < conto.npl; j = i32(j + 1)) {
        let f2 = 0.0;
        for (let k = 0; k < conto.p[j].n; k = i32(k + 1)) {
          if ((conto.p[j].wz === 0) && (this.py(conto.keyx[i], conto.p[j].ox[k], conto.keyz[i], conto.p[j].oz[k]) < madness.clrad[madness.cn])) {
            f2 = fr((fr(f / 20.0)) * this.m.random());
          }
        }
        if ((f2 !== 0.0) && (Math.abs(f2) >= 1.0)) {
          conto.p[j].chip = 1;
          conto.p[j].ctmag = f2;
        }
      }
    }
  }

  regz(i, f, conto, madness) {
    if (Math.abs(f) > 100.0) {
      if (f > 100.0) {
        f = fr(f - 100.0);
      }
      if (f < -100.0) {
        f = fr(f + 100.0);
      }
      for (let j = 0; j < conto.npl; j = i32(j + 1)) {
        let f2 = 0.0;
        for (let k = 0; k < conto.p[j].n; k = i32(k + 1)) {
          if ((conto.p[j].wz === 0) && (this.py(conto.keyx[i], conto.p[j].ox[k], conto.keyz[i], conto.p[j].oz[k]) < madness.clrad[madness.cn])) {
            f2 = fr((fr(f / 20.0)) * this.m.random());
            let oz = conto.p[j].oz;
            let n = k;
            oz[n] = trunc(fr(fr(oz[n]) + ((fr((fr(f2 * this.m.cos(conto.xz))) * this.m.cos(conto.zy))))));
            let ox = conto.p[j].ox;
            let n2 = k;
            ox[n2] = trunc(fr(fr(ox[n2]) + ((fr((fr(f2 * this.m.sin(conto.xz))) * this.m.cos(conto.xy))))));
          }
        }
        if (f2 !== 0.0) {
          if (Math.abs(f2) >= 1.0) {
            conto.p[j].chip = 1;
            conto.p[j].ctmag = f2;
          }
          if (!conto.p[j].nocol && (conto.p[j].glass !== 1)) {
            if ((conto.p[j].bfase > 20) && (conto.p[j].hsb[1] > 0.2)) {
              conto.p[j].hsb[1] = 0.20000000298023224;
            }
            if (conto.p[j].bfase > 30) {
              if (conto.p[j].hsb[2] < 0.5) {
                conto.p[j].hsb[2] = 0.5;
              }
              if (conto.p[j].hsb[1] > 0.1) {
                conto.p[j].hsb[1] = 0.10000000149011612;
              }
            }
            if (conto.p[j].bfase > 40) {
              conto.p[j].hsb[1] = 0.05000000074505806;
            }
            if (conto.p[j].bfase > 50) {
              if (conto.p[j].hsb[2] > 0.8) {
                conto.p[j].hsb[2] = 0.800000011920929;
              }
              conto.p[j].hsb[0] = 0.07500000298023224;
              conto.p[j].hsb[1] = 0.05000000074505806;
            }
            if (conto.p[j].bfase > 60) {
              conto.p[j].hsb[0] = 0.05000000074505806;
            }
            let plane = conto.p[j];
            plane.bfase = trunc(fr(fr(plane.bfase) + Math.abs(f2)));
            new Color(conto.p[j].c[0], conto.p[j].c[1], conto.p[j].c[2]);
            let color = Color.getHSBColor(conto.p[j].hsb[0], conto.p[j].hsb[1], conto.p[j].hsb[2]);
            conto.p[j].c[0] = color.getRed();
            conto.p[j].c[1] = color.getGreen();
            conto.p[j].c[2] = color.getBlue();
          }
          if (conto.p[j].glass === 1) {
            let plane2 = conto.p[j];
            plane2.gr = trunc(plane2.gr + Math.abs(f2 * 1.5));
          }
        }
      }
    }
  }

  play(conto, madness, i, j) {
    conto.x = this.x[j][i];
    conto.y = this.y[j][i];
    conto.z = this.z[j][i];
    conto.zy = this.zy[j][i];
    conto.xy = this.xy[j][i];
    conto.xz = this.xz[j][i];
    conto.wxz = this.wxz[j][i];
    conto.wzy = this.wzy[j][i];
    if (i === 0) {
      conto.m.checkpoint = this.checkpoint[j];
      conto.m.lastcheck = this.lastcheck[j];
    }
    if (j === 0) {
      this.cntdest[i] = 0;
    }
    if (this.dest[i] === j) {
      this.cntdest[i] = 7;
    }
    if ((j === 0) && (this.dest[i] < -1)) {
      for (let k = 0; k < conto.npl; k = i32(k + 1)) {
        if (((conto.p[k].wz === 0) || (conto.p[k].gr === -17)) || (conto.p[k].gr === -16)) {
          conto.p[k].embos = 13;
        }
      }
    }
    if (this.cntdest[i] !== 0) {
      for (let l = 0; l < conto.npl; l = i32(l + 1)) {
        if (((conto.p[l].wz === 0) || (conto.p[l].gr === -17)) || (conto.p[l].gr === -16)) {
          conto.p[l].embos = 1;
        }
      }
      let cntdest = this.cntdest;
      --cntdest[i];
    }
    let i2 = 0;
    do {
      let j2 = 0;
      do {
        if (this.sspark[i][i2][j2] === j) {
          conto.stg[i2] = 1;
          conto.dov[i2] = -1;
          conto.sx[i2] = this.sx[i][i2][j2];
          conto.sy[i2] = this.sy[i][i2][j2];
          conto.sz[i2] = this.sz[i][i2][j2];
          conto.smag[i2] = this.smag[i][i2][j2];
          conto.scx[i2] = this.scx[i][i2][j2];
          conto.scz[i2] = this.scz[i][i2][j2];
          conto.fulls[i2] = this.fulls[i][i2][j2];
        }
      } while (++j2 < 30);
      j2 = 0;
      do {
        if (this.ry[i][i2][j2] === j) {
          this.regy(i2, fr(this.magy[i][i2][j2]), this.mtouch[i][j2], conto, madness);
        }
        if (this.rx[i][i2][j2] === j) {
          this.regx(i2, fr(this.magx[i][i2][j2]), conto, madness);
        }
        if (this.rz[i][i2][j2] === j) {
          this.regz(i2, fr(this.magz[i][i2][j2]), conto, madness);
        }
      } while (++j2 < 7);
    } while (++i2 < 4);
  }

  rec(conto, i, j, k, l, ncars) {
    if (i === 0) {
      this.caught = i32(this.caught + 1);
    }
    if (this.cntf === 50) {
      let i2 = 0;
      do {
        this.car[i2][i] = new ContO(1, this.car[i32(i2 + 1)][i], 0, 0, 0, 0);
        this.squash[i2][i] = this.squash[i32(i2 + 1)][i];
      } while (++i2 < 5);
      this.car[5][i] = new ContO(1, conto, 0, 0, 0, 0);
      this.squash[5][i] = j;
      this.cntf = 0;
    } else {
      this.cntf = i32(this.cntf + 1);
    }
    let fix = this.fix;
    --fix[i];
    if (l !== 0) {
      let dest = this.dest;
      --dest[i];
    }
    if (this.dest[i] === 230) {
      if (i === 0) {
        this.cotchinow(0, ncars);
        this.whenwasted = 229;
      } else if (k !== 0) {
        this.cotchinow(i, ncars);
        this.whenwasted = i32(165 + k);
      }
    }
    let j2 = 0;
    do {
      this.x[j2][i] = this.x[i32(j2 + 1)][i];
      this.y[j2][i] = this.y[i32(j2 + 1)][i];
      this.z[j2][i] = this.z[i32(j2 + 1)][i];
      this.zy[j2][i] = this.zy[i32(j2 + 1)][i];
      this.xy[j2][i] = this.xy[i32(j2 + 1)][i];
      this.xz[j2][i] = this.xz[i32(j2 + 1)][i];
      this.wxz[j2][i] = this.wxz[i32(j2 + 1)][i];
      this.wzy[j2][i] = this.wzy[i32(j2 + 1)][i];
    } while (++j2 < 299);
    this.x[299][i] = conto.x;
    this.y[299][i] = conto.y;
    this.z[299][i] = conto.z;
    this.xy[299][i] = conto.xy;
    this.zy[299][i] = conto.zy;
    this.xz[299][i] = conto.xz;
    this.wxz[299][i] = trunc(conto.wxz);
    this.wzy[299][i] = conto.wzy;
    if (i === 0) {
      j2 = 0;
      do {
        this.checkpoint[j2] = this.checkpoint[i32(j2 + 1)];
        this.lastcheck[j2] = this.lastcheck[i32(j2 + 1)];
      } while (++j2 < 299);
      this.checkpoint[299] = conto.m.checkpoint;
      this.lastcheck[299] = conto.m.lastcheck;
    }
    j2 = 0;
    do {
      if (conto.stg[j2] === 1) {
        this.sspark[i][j2][this.ns[i][j2]] = 300;
        this.sx[i][j2][this.ns[i][j2]] = conto.sx[j2];
        this.sy[i][j2][this.ns[i][j2]] = conto.sy[j2];
        this.sz[i][j2][this.ns[i][j2]] = conto.sz[j2];
        this.smag[i][j2][this.ns[i][j2]] = conto.smag[j2];
        this.scx[i][j2][this.ns[i][j2]] = conto.scx[j2];
        this.scz[i][j2][this.ns[i][j2]] = conto.scz[j2];
        this.fulls[i][j2][this.ns[i][j2]] = conto.fulls[j2];
        let array = this.ns[i];
        let n = j2;
        ++array[n];
        if (this.ns[i][j2] === 30) {
          this.ns[i][j2] = 0;
        }
      }
      let k2 = 0;
      do {
        let array2 = this.sspark[i][j2];
        let n2 = k2;
        --array2[n2];
      } while (++k2 < 30);
      k2 = 0;
      do {
        let array3 = this.ry[i][j2];
        let n3 = k2;
        --array3[n3];
        let array4 = this.rx[i][j2];
        let n4 = k2;
        --array4[n4];
        let array5 = this.rz[i][j2];
        let n5 = k2;
        --array5[n5];
      } while (++k2 < 7);
    } while (++j2 < 4);
  }

  recx(i, f, j) {
    this.rx[j][i][this.nry[j][i]] = 300;
    this.magx[j][i][this.nry[j][i]] = trunc(f);
    let array = this.nrx[j];
    ++array[i];
    if (this.nrx[j][i] === 7) {
      this.nrx[j][i] = 0;
    }
  }

  recy(i, f, flag, j) {
    this.ry[j][i][this.nry[j][i]] = 300;
    this.magy[j][i][this.nry[j][i]] = trunc(f);
    this.mtouch[j][this.nry[j][i]] = flag;
    let array = this.nry[j];
    ++array[i];
    if (this.nry[j][i] === 7) {
      this.nry[j][i] = 0;
    }
  }

  cotchinow(i, ncars) {
    if (this.caught >= 300) {
      this.wasted = i;
      let j = 0;
      do {
        this.starcar[j] = new ContO(1, this.car[0][j], 0, 0, 0, 0);
        this.hsquash[j] = this.squash[0][j];
        this.hfix[j] = this.fix[j];
        this.hdest[j] = this.dest[j];
      } while (++j < ncars);
      j = 0;
      do {
        let k = 0;
        do {
          this.hx[j][k] = this.x[j][k];
          this.hy[j][k] = this.y[j][k];
          this.hz[j][k] = this.z[j][k];
          this.hxy[j][k] = this.xy[j][k];
          this.hzy[j][k] = this.zy[j][k];
          this.hxz[j][k] = this.xz[j][k];
          this.hwxz[j][k] = this.wxz[j][k];
          this.hwzy[j][k] = this.wzy[j][k];
        } while (++k < ncars);
        this.hcheckpoint[j] = this.checkpoint[j];
        this.hlastcheck[j] = this.lastcheck[j];
      } while (++j < 300);
      j = 0;
      do {
        let l = 0;
        do {
          this.hns[j][l] = this.ns[j][l];
          let k2 = 0;
          do {
            this.hsspark[j][l][k2] = this.sspark[j][l][k2];
            this.hsx[j][l][k2] = this.sx[j][l][k2];
            this.hsy[j][l][k2] = this.sy[j][l][k2];
            this.hsz[j][l][k2] = this.sz[j][l][k2];
            this.hsmag[j][l][k2] = this.smag[j][l][k2];
            this.hscx[j][l][k2] = this.scx[j][l][k2];
            this.hscz[j][l][k2] = this.scz[j][l][k2];
            this.hfulls[j][l][k2] = this.fulls[j][l][k2];
          } while (++k2 < 30);
        } while (++l < 4);
      } while (++j < ncars);
      j = 0;
      do {
        let i2 = 0;
        do {
          this.hnry[j][i2] = this.nry[j][i2];
          this.hnrx[j][i2] = this.nrx[j][i2];
          this.hnrz[j][i2] = this.nrz[j][i2];
          let l2 = 0;
          do {
            this.hry[j][i2][l2] = this.ry[j][i2][l2];
            this.hmagy[j][i2][l2] = this.magy[j][i2][l2];
            this.hrx[j][i2][l2] = this.rx[j][i2][l2];
            this.hmagx[j][i2][l2] = this.magx[j][i2][l2];
            this.hrz[j][i2][l2] = this.rz[j][i2][l2];
            this.hmagz[j][i2][l2] = this.magz[j][i2][l2];
          } while (++l2 < 7);
        } while (++i2 < 4);
      } while (++j < ncars);
      j = 0;
      do {
        let j2 = 0;
        do {
          this.hmtouch[j][j2] = this.mtouch[j][j2];
        } while (++j2 < 7);
      } while (++j < ncars);
      this.hcaught = true;
    }
  }

  chipx(i, f, conto, madness) {
    if (Math.abs(f) > 100.0) {
      if (f > 100.0) {
        f = fr(f - 100.0);
      }
      if (f < -100.0) {
        f = fr(f + 100.0);
      }
      for (let j = 0; j < conto.npl; j = i32(j + 1)) {
        let f2 = 0.0;
        for (let k = 0; k < conto.p[j].n; k = i32(k + 1)) {
          if ((conto.p[j].wz === 0) && (this.py(conto.keyx[i], conto.p[j].ox[k], conto.keyz[i], conto.p[j].oz[k]) < madness.clrad[madness.cn])) {
            f2 = fr((fr(f / 20.0)) * this.m.random());
          }
        }
        if ((f2 !== 0.0) && (Math.abs(f2) >= 1.0)) {
          conto.p[j].chip = 1;
          conto.p[j].ctmag = f2;
        }
      }
    }
  }

  regx(i, f, conto, madness) {
    if (Math.abs(f) > 100.0) {
      if (f > 100.0) {
        f = fr(f - 100.0);
      }
      if (f < -100.0) {
        f = fr(f + 100.0);
      }
      for (let j = 0; j < conto.npl; j = i32(j + 1)) {
        let f2 = 0.0;
        for (let k = 0; k < conto.p[j].n; k = i32(k + 1)) {
          if ((conto.p[j].wz === 0) && (this.py(conto.keyx[i], conto.p[j].ox[k], conto.keyz[i], conto.p[j].oz[k]) < madness.clrad[madness.cn])) {
            f2 = fr((fr(f / 20.0)) * this.m.random());
            let oz = conto.p[j].oz;
            let n = k;
            oz[n] = trunc(fr(fr(oz[n]) - ((fr((fr(f2 * this.m.sin(conto.xz))) * this.m.cos(conto.zy))))));
            let ox = conto.p[j].ox;
            let n2 = k;
            ox[n2] = trunc(fr(fr(ox[n2]) + ((fr((fr(f2 * this.m.cos(conto.xz))) * this.m.cos(conto.xy))))));
          }
        }
        if (f2 !== 0.0) {
          if (Math.abs(f2) >= 1.0) {
            conto.p[j].chip = 1;
            conto.p[j].ctmag = f2;
          }
          if (!conto.p[j].nocol && (conto.p[j].glass !== 1)) {
            if ((conto.p[j].bfase > 20) && (conto.p[j].hsb[1] > 0.2)) {
              conto.p[j].hsb[1] = 0.20000000298023224;
            }
            if (conto.p[j].bfase > 30) {
              if (conto.p[j].hsb[2] < 0.5) {
                conto.p[j].hsb[2] = 0.5;
              }
              if (conto.p[j].hsb[1] > 0.1) {
                conto.p[j].hsb[1] = 0.10000000149011612;
              }
            }
            if (conto.p[j].bfase > 40) {
              conto.p[j].hsb[1] = 0.05000000074505806;
            }
            if (conto.p[j].bfase > 50) {
              if (conto.p[j].hsb[2] > 0.8) {
                conto.p[j].hsb[2] = 0.800000011920929;
              }
              conto.p[j].hsb[0] = 0.07500000298023224;
              conto.p[j].hsb[1] = 0.05000000074505806;
            }
            if (conto.p[j].bfase > 60) {
              conto.p[j].hsb[0] = 0.05000000074505806;
            }
            let plane = conto.p[j];
            plane.bfase = trunc(fr(fr(plane.bfase) + Math.abs(f2)));
            new Color(conto.p[j].c[0], conto.p[j].c[1], conto.p[j].c[2]);
            let color = Color.getHSBColor(conto.p[j].hsb[0], conto.p[j].hsb[1], conto.p[j].hsb[2]);
            conto.p[j].c[0] = color.getRed();
            conto.p[j].c[1] = color.getGreen();
            conto.p[j].c[2] = color.getBlue();
          }
          if (conto.p[j].glass === 1) {
            let plane2 = conto.p[j];
            plane2.gr = trunc(plane2.gr + Math.abs(f2 * 1.5));
          }
        }
      }
    }
  }

  recz(i, f, j) {
    this.rz[j][i][this.nry[j][i]] = 300;
    this.magz[j][i][this.nry[j][i]] = trunc(f);
    let array = this.nrz[j];
    ++array[i];
    if (this.nrz[j][i] === 7) {
      this.nrz[j][i] = 0;
    }
  }

  py(i, j, k, l) {
    return i32((Math.imul(((i32(i - j))), (i32(i - j)))) + (Math.imul(((i32(k - l))), (i32(k - l)))));
  }
}
