// The special power of each of Extended's 39 cars, as the car select describes it
// (xtGraphics.carselect, specialboost 1 = Free Play). A new car borrows one by its
// extspecial line (extlines.js). specials.test.js re-derives this from xtGraphics.js.
// Car 21 (Agent Racer): the game draws no description.
export const SPECIALS = [
  ['A random car gets reduced speed.', 'Strength/Defence boost: 50%/30%'],
  ['15% speed boost.', 'Swaps its strength with a random car.', 'Unlimited power.'],
  ['Unlimited power.', 'Strength/Defence boost: 45%/30%', "Drains a random car's health."],
  ['Reduces the defence of the car in first.', 'Speed/Stunting boost: 30%/75%'],
  ['70% strength boost.', "Reduces a random car's defence."],
  ['30% strength and 25% speed boost.', 'These boosts double past 50% damage.'],
  ['Strength/Speed boost: 50%/15%', "Drains a random car's health."],
  ['Strength/Defence boost: 60%/50%'],
  ['100% control boost.', '45% strength boost.', '30% speed boost.'],
  ['A random car gets reduced speed.', 'Strength/Speed boost: 40%/10%', 'You get unlimited power.'],
  ['30% speed boost.', 'Strength/Defence boost: 35%/40%', "Reduces a random car's defence."],
  ['Strength/Speed boost: 40%/30%.', "Drains a random car's health."],
  ['25% speed boost.', 'You get unlimited power.', 'Reduces the defence of the car in first.'],
  ['40% strength/defence boost.', "Reduces a random car's defence."],
  ['Speed/Stunting boost: 15%/100%.', 'Strength/Defence boost: 40%/70%.', 'A random car gets reduced speed.'],
  ['Every stat increases by 30%.'],
  ['Unlimited power.', 'Strength/Speed boost: 30%/15%.', 'Control boost: 50%', "Drains a random car's health."],
  ['Unlimited power.', '50% defence boost.', '15% speed boost.'],
  ['20% speed boost.', '25% strength/defence boost.', 'Reduces the defence of a random car.'],
  ['Strength/Speed boost: 20%/10%.', '30% defence boost.', 'Reduces the speed of a random car.'],
  ['Strength/Defence boost: 60%/40%.', '10% speed cut.', 'Reduces the defence of a random car.'],
  [],
  ['Strength/Speed boost: 15%.', 'Defence boost: 30%.', 'Acceleration boost: 100%.', 'Unlimited power.'],
  ['A random car gets reduced speed.', 'Strength/Defence boost: 55%/30%'],
  ['15% speed boost.', 'Swaps its strength with a random car.', 'Unlimited power.'],
  ['Unlimited power.', 'Strength/Defence boost: 45%/30%', "Drains a random car's health."],
  ['Reduces the defence of the car in first.', 'Speed/Stunting boost: 35%/60%'],
  ['70% strength boost.', "Reduces a random car's defence."],
  ['30% strength and 25% speed boost.', 'These boosts double past 50% damage.'],
  ['Strength/Speed boost: 50%/15%', "Drains a random car's health."],
  ['Strength/Defence boost: 60%/50%'],
  ['75% control boost.', '40% strength boost.', '20% speed boost.'],
  ['A random car gets reduced speed.', 'Strength/Speed boost: 35%/10%', 'You get unlimited power.'],
  ['20% speed/strength boost.', 'Strength/Defence boost: 30%', "Reduces a random car's defence."],
  ['Strength/Speed boost: 30%/20%.', "Drains a random car's health."],
  ['20% speed boost.', 'You get unlimited power.', 'Reduces the defence of the car in first.'],
  ['30% strength/defence boost.', "Reduces a random car's defence."],
  ['Speed boost: 15%', 'Strength/Defence boost: 35%/50%.', 'A random car gets reduced speed.'],
  ['Every stat increases by 20%.'],
];
