// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/SuperClip.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { fr } from '../java.js';
import { ByteArrayInputStream, System, Thread, jstr } from './jawt.js';

export class SuperClip {
  constructor(abyte0, i, j) {
    this.skiprate = 0;
    this.cliper = null;
    this.stoped = 0;
    this.source = null;
    this.stream = null;
    this.skiprate = 0;
    this.stoped = 1;
    this.source = null;
    this.stoped = 2;
    this.skiprate = j;
    this.stream = new ByteArrayInputStream(abyte0, 0, i);
  }

  *run() {
    let flag = false;
    try {
      let info = new DataLine.Info(SourceDataLine.class, new AudioFormat(Encoding.PCM_SIGNED, -1.0, 16, 2, 4, -1.0, true));
      (this.source = AudioSystem.getLine(info)).open(new AudioFormat(fr(this.skiprate), 16, 1, false, false));
      this.source.start();
    } catch (exception) {
      this.stoped = 1;
    }
    while (this.stoped === 0) {
      try {
        if ((this.source.available() < this.skiprate) || !flag) {
          let abyte0 = new Int8Array(this.skiprate);
          let i = this.stream.read(abyte0, 0, abyte0.length);
          if (i === -1) {
            this.stream.reset();
            this.stream.read(abyte0, 0, abyte0.length);
          }
          this.source.write(abyte0, 0, abyte0.length);
          flag = true;
        }
      } catch (exception2) {
        System.out.println('play error: ' + exception2);
        this.stoped = 1;
      }
      try {
        let _tmp = this.cliper;
        (yield 200);
      } catch (ex) {
      }
    }
    this.source.stop();
    this.source.close();
    this.source = null;
    this.stoped = 2;
  }

  play() {
    if (this.stoped === 2) {
      this.stoped = 0;
      try {
        this.stream.reset();
      } catch (ex) {
      }
      (this.cliper = new Thread(this)).start();
    }
  }

  resume() {
    if (this.stoped === 2) {
      this.stoped = 0;
      (this.cliper = new Thread(this)).start();
    }
  }

  stop() {
    if (this.stoped === 0) {
      this.stoped = 1;
      if (this.source !== null) {
        this.source.stop();
      }
    }
  }

  close() {
    try {
      this.stream.close();
      this.stream = null;
    } catch (ex) {
    }
  }
}
