// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/SuperStream.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { i32 } from '../java.js';

export class SuperStream {
  constructor(abyte0) {
  }

  read() {
    let i = this.super.read();
    if (i === -1) {
      this.reset();
      i = this.super.read();
    }
    return i;
  }

  read$1(abyte0, i, j) {
    let k = 0;
    while (k < j) {
      let l = this.super.read(abyte0, i32(i + k), i32(j - k));
      if (l >= 0) {
        k = i32(k + l);
      } else {
        this.reset();
      }
    }
    return k;
  }
}
