// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/Trackers.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { intArray, objArray } from '../java.js';

export class Trackers {
  constructor() {
    this.sequ = null;
    this.x = null;
    this.y = null;
    this.z = null;
    this.xy = null;
    this.zy = null;
    this.skd = null;
    this.sx = 0;
    this.sz = 0;
    this.ncx = 0;
    this.ncz = 0;
    this.dam = null;
    this.notwall = null;
    this.sect = null;
    this.tracksReady = false;
    this.oc = null;
    this.c = null;
    this.radx = null;
    this.radz = null;
    this.rady = null;
    this.nt = 0;
    this.sequ = ['Access Denied !', 'This game will not run under this http:/ loaction:', 'Please contact radicalplay.com for details.'];
    this.sx = 0;
    this.sz = 0;
    this.ncx = 0;
    this.ncz = 0;
    this.sect = null;
    this.x = intArray(67000);
    this.y = intArray(67000);
    this.z = intArray(67000);
    this.xy = intArray(67000);
    this.zy = intArray(67000);
    this.skd = intArray(67000);
    this.dam = intArray(67000);
    this.notwall = new Array(67000).fill(false);
    this.tracksReady = false;
    this.oc = objArray(67000).map(() => intArray(3));
    this.c = objArray(67000).map(() => intArray(3));
    this.radx = intArray(67000);
    this.radz = intArray(67000);
    this.rady = intArray(67000);
    this.nt = 0;
  }
}
