// GENERATED by decompilation/extended/j2js/J2JS.java from
// decompilation/extended/java-src/UlawUtils.java -- do not edit by hand;
// fix the transpiler or the source and regenerate.

import { i32 } from '../java.js';

export class UlawUtils {
  constructor() {
  }

  static linear2ulawclip(i) {
    if (i < -32767) {
      i = -32767;
    }
    if (i > 32767) {
      i = 32767;
    }
    return UlawUtils.s2u_lut[(((i >> 3)) & 8191)];
  }

  static linear2ulaw(byte0) {
    return UlawUtils.s2u_lut[i32(((((((byte0 & 255))) << 5))) + 15)];
  }

  static linear2ulaw$1(i) {
    return UlawUtils.s2u_lut[(i >> 3)];
  }
}
UlawUtils.s2u_lut = null;
