"""Generate web/stagemaker/parts.js from decompilation/java-src/StageMaker.java.

The Stage Maker's part catalogue lives in the applet as four list-filling
methods (partroads/partramps/partobst/partrees), a long if-chain mapping each
list position to a part number `sp`, and discp[] -- each part's description,
indexed by sp. Run from the repo root:  python web/tools/gen-stage-parts.py
"""
import json
import re

src = open('decompilation/java-src/StageMaker.java', encoding='utf-8').read()

names = {}
for fn in ['partroads', 'partramps', 'partobst', 'partrees']:
    m = re.search(r'public void ' + fn + r'\(\) \{(.*?)\n    \}', src, re.S)
    names[fn] = re.findall(r'this\.part\.add\(this\.rd, "([^"]+)"\)', m.group(1))

start = src.index('                if (this.sptyp == 0) {\n                    if (this.spart == 0) {')
maps, cur, sp = {}, None, None
for line in src[start:start + 20000].split('\n'):
    m = re.match(r'\s{16}if \(this\.sptyp == (\d+)\) \{', line)
    if m:
        cur = int(m.group(1))
        maps.setdefault(cur, {})
        continue
    m = re.match(r'\s+if \(this\.spart == (\d+)\) \{', line)
    if m:
        sp = int(m.group(1))
        continue
    m = re.match(r'\s+this\.sp = (\d+);', line)
    if m and cur is not None:
        maps[cur].setdefault(sp, int(m.group(1)))   # the pile branch after sptyp 5 also sets sp

dm = re.search(r'this\.discp = new String\[\] \{ (.*?) \};', src, re.S)
discp = [json.loads('"' + s + '"') for s in re.findall(r'"((?:[^"\\]|\\.)*)"', dm.group(1))]

cats = [('roads', 'Roads', 'partroads', 0), ('ramps', 'Ramps', 'partramps', 1),
        ('obstacles', 'Obstacles', 'partobst', 2), ('trees', 'Trees', 'partrees', 5)]
out = [
    "// The Stage Maker's part catalogue, GENERATED by web/tools/gen-stage-parts.py",
    '// from StageMaker.java: the partroads/partramps/partobst/partrees lists, the',
    "// spart -> sp mapping the applet applies to them, and discp[] (each part's",
    '// description, by sp). Regenerate rather than edit by hand.',
    '',
    'export const CATEGORIES = [',
]
for key, label, fn, t in cats:
    items = [{'name': n, 'sp': maps[t][i]} for i, n in enumerate(names[fn])]
    out.append('  { key: %s, label: %s, parts: %s },' % (json.dumps(key), json.dumps(label), json.dumps(items)))
out.append("  { key: 'checkpoints', label: 'Checkpoints', parts: [{ \"name\": \"Checkpoint\", \"sp\": 30 }, { \"name\": \"Fixing Hoop\", \"sp\": 31 }] },")
out.append("  { key: 'start', label: 'Start', parts: [{ \"name\": \"The Start1\", \"sp\": 37 }, { \"name\": \"The Start2\", \"sp\": 38 }] },")
out.append('];')
out.append('')
out.append("/** discp[sp]: the applet's own description of each part. */")
out.append('export const DESCRIPTIONS = %s;' % json.dumps(discp, ensure_ascii=False))
out.append('')
out.append('/** Roads a checkpoint mounts on: asphalt takes sp 30, dirt sp 32 (StageMaker.java:256). */')
out.append('export const ASPHALT_CHECKPOINT_ROADS = [0, 1, 2, 3, 4, 12, 13, 37];')
out.append('export const DIRT_CHECKPOINT_ROADS = [5, 6, 7, 11, 14, 33, 34, 38];')
open('web/stagemaker/parts.js', 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print(len(discp), 'descriptions;', {k: len(names[f]) for k, _, f, _ in cats})
